/* batch9_data.js — Viz, Tools & Engineering */

window.BATCH_ID    = 'batch9';
window.BATCH_TITLE = 'Batch 9 — Viz, Tools & Engineering';

window.TOPIC_COLORS = {
  'Matplotlib': '#1A237E',
  'Power BI':   '#4A148C',
  'Tableau':    '#004D40',
  'Streamlit':  '#BF360C',
  'Jupyter':    '#880E4F',
  'VS Code':    '#E65100',
  'SQL':        '#1B5E20',
  'Git':        '#0D47A1',
  'GitHub':     '#37474F',
};

window.FLASHCARD_DATA = [

  // MATPLOTLIB
  { id:'mpl_01', topic:'Matplotlib', subtopic:'Definition',
    theory:'Matplotlib is the foundational Python plotting library. Almost every other Python visualisation tool (Seaborn, pandas .plot()) is built on top of it. Two interfaces: pyplot (simple, good for quick plots) and object-oriented (explicit Figure and Axes, better for complex layouts and production code). Figure is the whole window/page; Axes is one individual plot inside.',
    interview:'Matplotlib is the main Python plotting library. The simple way is pyplot — just call plt.plot() and plt.show(). The better way for production is to create a Figure and Axes object, which gives more control. A Figure is the whole image. An Axes is one chart inside it. We can have multiple charts in one Figure using subplots.',
    code:'import matplotlib.pyplot as plt\nimport numpy as np\n\n# Pyplot (quick)\nplt.plot([1,2,3],[4,5,6])\nplt.title("Quick Plot")\nplt.show()\n\n# Object-oriented (recommended)\nfig, ax = plt.subplots(figsize=(8,5))\nax.plot([1,2,3],[4,5,6],\n        label="Line 1",\n        color="steelblue",\n        linewidth=2)\nax.set_title("OO Interface")\nax.set_xlabel("X Axis")\nax.legend()\nfig.tight_layout()\nfig.savefig("plot.png", dpi=150)',
    realworld:'The scikit-learn documentation uses Matplotlib for all its example plots — confusion matrices, ROC curves, learning curves. When a data scientist shows training loss curves in a Jupyter notebook, that is almost always Matplotlib under the hood.' },

  { id:'mpl_02', topic:'Matplotlib', subtopic:'Common Plot Types',
    theory:'Line plot: show trends over time. Bar chart: compare categories. Histogram: show distribution of a single variable. Scatter plot: show relationship between two variables. Box plot: show distribution summary (median, quartiles, outliers) per category. Heatmap: show a 2D matrix — used for confusion matrices and correlation matrices. Choose the right chart type for the data relationship you are showing.',
    interview:'The main chart types are: line plots for trends over time, bar charts to compare categories, histograms to see how values are distributed, scatter plots to see the relationship between two variables, and heatmaps to visualise matrices like confusion matrices. Choosing the right chart type matters — using a line chart for categories is wrong because it implies continuity.',
    code:'import matplotlib.pyplot as plt\nimport numpy as np\n\nfig, axes = plt.subplots(2, 3,\n                          figsize=(14, 8))\naxes[0,0].plot([1,2,3,4],[10,8,12,9])\naxes[0,0].set_title("Line Plot")\n\naxes[0,1].bar(["A","B","C"],[4,7,5],\n               color="steelblue")\naxes[0,1].set_title("Bar Chart")\n\naxes[0,2].hist(np.random.randn(500),\n               bins=30, edgecolor="white")\naxes[0,2].set_title("Histogram")\n\nmatrix = np.random.rand(4,4)\nim = axes[1,2].imshow(matrix, cmap="Blues")\nplt.colorbar(im, ax=axes[1,2])\n\nfig.tight_layout()\nplt.show()',
    realworld:'A data analyst at Flipkart uses a combination of chart types: line chart for daily revenue trend, bar chart comparing revenue by category, histogram showing order value distribution, and scatter plot of ad spend vs conversion rate. Each chart type answers a different business question.' },

  { id:'mpl_03', topic:'Matplotlib', subtopic:'Subplots and Styling',
    theory:'plt.subplots(rows, cols) creates a grid of axes. figsize controls overall figure dimensions in inches. tight_layout() adjusts spacing so plots do not overlap. plt.style.use() applies pre-defined aesthetics. Annotations with ax.annotate() add text with arrows. These details matter for presentation-quality charts.',
    interview:'Subplots let us show multiple charts in one figure. plt.subplots(2,2) creates a 2x2 grid. We apply a style like seaborn-whitegrid for a clean background, set specific colours using hex codes, and add annotations pointing to important features. These details matter when presenting to non-technical audiences.',
    code:'import matplotlib.pyplot as plt\nimport numpy as np\n\nplt.style.use("seaborn-v0_8-whitegrid")\n\nfig, axes = plt.subplots(2, 2,\n                          figsize=(10, 8))\naxes[0,0].plot([1,2,3])\naxes[0,1].bar([1,2,3],[4,5,6])\naxes[1,0].scatter([1,2,3],[4,5,6])\naxes[1,1].hist(np.random.randn(100))\n\nfig.suptitle("Model Evaluation",\n              fontsize=14)\nfig.tight_layout()\n\n# Annotation\naxes[0,0].annotate(\n    "Best model",\n    xy=(2, 2), xytext=(3, 1),\n    arrowprops=dict(arrowstyle="->")\n)',
    realworld:'A model evaluation report uses a 2x2 subplot: training/validation loss curves, confusion matrix heatmap, ROC curve with AUC, and feature importance bar chart. All four in one figure gives a complete picture of model performance that can be saved as a single image for the presentation.' },

  // POWER BI
  { id:'pbi_01', topic:'Power BI', subtopic:'Definition',
    theory:'Power BI is Microsoft\'s business intelligence platform. Connect to data sources, transform data with Power Query, build interactive dashboards, share across an organisation. Components: Power BI Desktop (free, build reports), Power BI Service (cloud, share), Power BI Mobile (view on phone). DAX (Data Analysis Expressions) is the formula language for calculated columns and measures. Reports are interactive — users can filter and drill down.',
    interview:'Power BI is a Microsoft tool for building interactive business dashboards. We connect to data sources like Excel or databases, clean the data in Power Query, and build charts and tables. DAX is the formula language we use to create calculated metrics like total sales, year-to-date totals, and percentage of total. Business users can click on a chart to filter all other charts on the page.',
    code:'-- DAX measure examples\n\n-- Total sales\nTotal Sales = SUM(Sales[Amount])\n\n-- Filtered measure\nOnline Sales =\n    CALCULATE(\n        SUM(Sales[Amount]),\n        Sales[Channel] = "Online"\n    )\n\n-- Year-to-date\nSales YTD =\n    TOTALYTD(\n        SUM(Sales[Amount]),\n        \'Date\'[Date]\n    )\n\n-- YoY Growth\nYoY Growth % =\n    DIVIDE(\n        [Total Sales] - [Sales Last Year],\n        [Sales Last Year]\n    ) * 100',
    realworld:'A retail chain\'s operations team uses Power BI to monitor daily performance across 200 stores. Clicking on any region filters all visuals. Store managers access the dashboard on their phones every morning without needing the data team.' },

  { id:'pbi_02', topic:'Power BI', subtopic:'DAX Measures vs Calculated Columns',
    theory:'Calculated columns: computed row by row when data loads, stored in the model, use for properties of each row (e.g., profit margin per row). Measures: computed at query time based on the current filter context, not stored as a column, only visible in visuals. Measures are almost always the right choice for aggregations. CALCULATE() is the most important DAX function — it evaluates an expression in a modified filter context.',
    interview:'Calculated columns compute a value for every row and store it — like adding a profit margin column to a sales table. Measures compute on the fly based on what filters are active — like total sales, which changes depending on which region or month is selected. Measures are the right choice for aggregations. CALCULATE is the most powerful DAX function — it lets us change the filter context to compute things like last year\'s sales.',
    code:'-- Calculated column (row-level, stored)\nProfit Margin =\n    DIVIDE(\n        Sales[Profit],\n        Sales[Revenue]\n    ) * 100\n-- Each row gets its own margin\n\n-- Measure (aggregation, context-aware)\nAvg Profit Margin =\n    AVERAGEX(\n        Sales,\n        DIVIDE(Sales[Profit], Sales[Revenue])\n    ) * 100\n-- Changes based on active filter\n\n-- CALCULATE - change filter context\nSales Last Year =\n    CALCULATE(\n        SUM(Sales[Amount]),\n        SAMEPERIODLASTYEAR(\'Date\'[Date])\n    )',
    realworld:'A telecom churn dashboard uses calculated columns to categorise each customer as high/medium/low value, and measures to compute churn rate and YoY comparison. When a regional manager filters to their region, all measures recalculate automatically for just that region\'s data.' },

  // TABLEAU
  { id:'tab_01', topic:'Tableau', subtopic:'Definition',
    theory:'Tableau is a drag-and-drop data visualisation and BI tool. Known for fast, interactive charts with minimal coding. Key concepts: Dimensions (categorical fields — Region, Product) and Measures (numeric fields — Sales, Profit). Drag dimensions to rows/columns to create breakdowns. Drag measures to the Marks card to control size, colour, and labels. Published dashboards on Tableau Server allow interactive filtering.',
    interview:'Tableau is a drag-and-drop tool for building interactive charts. We drag dimension fields like Region or Product to rows and columns to break down the data. We drag measure fields like Sales to control what is displayed. Calculated fields are like Excel formulas for creating custom metrics. LOD expressions compute at a different aggregation level than the current view.',
    code:'-- Tableau calculated field examples\n\n-- Profit Ratio\nProfit Ratio =\n    SUM([Profit]) / SUM([Sales])\n\n-- Running Total\nRunning Total =\n    RUNNING_SUM(SUM([Sales]))\n\n-- LOD: Fixed - customer lifetime value\n-- (regardless of current date filter)\nCustomer LTV =\n    {FIXED [Customer ID]:\n        SUM([Sales])}\n\n-- LOD: Exclude - total ignoring region\nTotal All Regions =\n    {EXCLUDE [Region]:\n        SUM([Sales])}\n\nRegion % of Total =\n    SUM([Sales]) / [Total All Regions]',
    realworld:'A sales analytics team at an FMCG company uses Tableau to build a territory management dashboard. Brand managers drag Region to Rows, Month to Columns, and Sales to the colour shelf to instantly create a heat map. No code, no waiting for IT. Updated daily from the data warehouse.' },

  // STREAMLIT
  { id:'slt_01', topic:'Streamlit', subtopic:'Definition',
    theory:'Streamlit is a Python library for building interactive web apps for data science and ML, purely in Python with no web development knowledge needed. The entire script reruns from top to bottom on every user interaction. Key components: st.title/header/text for content, st.slider/selectbox/text_input for widgets, st.dataframe for data display, st.pyplot/plotly_chart for visualisations.',
    interview:'Streamlit lets us build interactive web apps in pure Python. We just write a Python script using Streamlit commands. st.slider creates a slider widget. st.selectbox creates a dropdown. st.dataframe shows a table. st.pyplot shows a Matplotlib chart. When the user moves the slider, Streamlit reruns the whole script with the new value. No HTML or JavaScript needed.',
    code:'import streamlit as st\nimport pandas as pd\nimport numpy as np\n\nst.title("ML Model Dashboard")\n\nthreshold = st.sidebar.slider(\n    "Decision Threshold", 0.0, 1.0, 0.5)\nmodel_name = st.sidebar.selectbox(\n    "Model", ["Random Forest", "XGBoost"])\n\ndf = pd.DataFrame(\n    np.random.randn(50, 3),\n    columns=["Feature A","Feature B","Score"])\nst.dataframe(df)\n\nif st.button("Run Prediction"):\n    st.success("Prediction complete!")\n    st.metric(\n        label="Accuracy",\n        value="87.3%",\n        delta="+2.1%")\n\n# Run: streamlit run app.py',
    realworld:'A data scientist at a bank builds a loan approval demo in one afternoon. Input fields for income, credit score, and loan amount. When the user clicks Predict, it calls the trained model and shows approval probability. The business team can test scenarios without running Python. Deploying to Streamlit Community Cloud takes 5 minutes and is free.' },

  { id:'slt_02', topic:'Streamlit', subtopic:'Caching and Session State',
    theory:'st.cache_resource: cache objects expensive to create and shared across all users — like loading an ML model. Only created once when the server starts. st.cache_data: cache function return values for expensive data loading. st.session_state: a dictionary that persists between reruns for a single user session. Use it to store conversation history, form progress, or accumulated results.',
    interview:'Caching in Streamlit is important because the script reruns on every user interaction. Without caching, the model would reload from disk every time the user moves a slider — very slow. cache_resource loads the model once and reuses it for all users. cache_data caches data loading results. session_state stores data that should persist between reruns for a specific user — like a chatbot\'s conversation history.',
    code:'import streamlit as st\nimport joblib, pandas as pd\n\n@st.cache_resource\ndef load_model():\n    return joblib.load("model.pkl")\n\n@st.cache_data\ndef load_data(filepath):\n    return pd.read_csv(filepath)\n\nmodel = load_model()   # cached\ndf    = load_data("data.csv")  # cached\n\n# Session state: persists per user\nif "history" not in st.session_state:\n    st.session_state.history = []\n\nuser_input = st.text_input("Ask a question")\n\nif st.button("Submit") and user_input:\n    answer = model.predict([user_input])\n    st.session_state.history.append(\n        {"q": user_input, "a": answer})',
    realworld:'A RAG chatbot in Streamlit uses cache_resource to load the embedding model and vector store once at startup (30 seconds otherwise). session_state stores the full conversation history so all previous messages appear. Each new message reruns the script, but model and history are available instantly.' },

  // JUPYTER
  { id:'jup_01', topic:'Jupyter', subtopic:'Definition',
    theory:'Jupyter Notebook is an interactive computing environment where code, output, text, and visualisations live in the same document. Made up of cells: code cells (execute Python and show output directly below) and markdown cells. The key advantage is iterative development — run one cell, see the result, adjust, run again. Widely used for data exploration, EDA, and model prototyping.',
    interview:'Jupyter Notebook lets us write and run Python code in small cells and see the output immediately below each cell. This is great for exploring data because we can run one step, check the result, and decide what to do next. Magic commands add extra functionality — %timeit measures how fast code runs, %matplotlib inline shows charts in the notebook.',
    code:'# Jupyter magic commands\n\n# Time a single line\n%timeit model.predict(X_test[:1])\n\n# Show matplotlib inline\n%matplotlib inline\n\n# List variables\n%whos\n\n# Run shell commands\n!pip install seaborn\n!ls -la\n\n# Auto-reload edited modules\n%load_ext autoreload\n%autoreload 2\n\n# Convert to script\n# jupyter nbconvert --to script notebook.ipynb',
    realworld:'Kaggle competitions are almost entirely done in Jupyter notebooks. Data scientists load data, explore cell by cell, train models and see metrics immediately. Kaggle provides free GPU-powered notebooks so anyone can train deep learning models in the browser.' },

  { id:'jup_02', topic:'Jupyter', subtopic:'Best Practices',
    theory:'Common pitfalls: Hidden state — cells run out of order leave stale variables. Fix: always restart kernel and run all cells top to bottom before trusting results. Large outputs: clear before committing to Git (use nbstripout). Long notebooks: split into focused notebooks or refactor repeated code into .py modules. Documentation: use markdown cells to explain each section.',
    interview:'Jupyter notebooks can cause problems if not used carefully. The biggest issue is running cells out of order — a variable set in cell 10 might be used in cell 5, which only works if cell 10 was run first. Always restart the kernel and run all cells in order before sharing. Clear outputs before committing to Git. Use markdown cells to document what each section does.',
    code:'# Best practices\n\n# 1. Always restart before presenting:\n# Kernel -> Restart & Run All\n\n# 2. Clear outputs before Git:\n# pip install nbstripout\n# nbstripout notebook.ipynb\n\n# 3. Set seeds at top:\nimport numpy as np\nnp.random.seed(42)\n\n# 4. Document with markdown:\n# ## Data Loading\n# ## EDA\n# ## Feature Engineering\n# ## Model Training\n# ## Evaluation\n\n# 5. Convert for production:\n# jupyter nbconvert --to script nb.ipynb\n# python nb.py',
    realworld:'A team shares a notebook with impressive results. A new member cannot reproduce them after restarting the kernel. Investigation reveals data leakage: the scaler was fitted before the train/test split in cell 8, but the split was done in cell 3. Running in order worked but a fresh restart fails. Rewriting in logical top-to-bottom order reveals the bug.' },

  // VS CODE
  { id:'vsc_01', topic:'VS Code', subtopic:'Definition',
    theory:'VS Code is the most popular code editor for Python and data science. Free, lightweight, extensible through extensions. Key features: Python extension (linting, IntelliSense, formatting), Jupyter extension (run notebooks in VS Code), integrated terminal, Git integration, debugger, Remote SSH (code on a server from your laptop). Command palette (Ctrl+Shift+P) gives access to all commands.',
    interview:'VS Code is the most popular code editor for Python. The Python extension gives autocomplete, error highlighting, and formatting. The integrated terminal means we can run code without leaving the editor. The debugger lets us set breakpoints and step through code to find bugs. Remote SSH lets us edit code on a GPU server as if it were on our local machine.',
    code:'# Essential VS Code shortcuts\n\n# Ctrl+Shift+P  -> Command palette\n# Ctrl+P        -> Quick file open\n# Ctrl+`        -> Toggle terminal\n# Ctrl+B        -> Toggle sidebar\n\n# Editing\n# Ctrl+D        -> Select next match\n# Alt+Up/Down   -> Move line\n# Ctrl+/        -> Toggle comment\n# Ctrl+Shift+K  -> Delete line\n\n# Python\n# F5            -> Start debugging\n# F9            -> Toggle breakpoint\n# Shift+Enter   -> Run selection',
    realworld:'Data science teams at Microsoft and Google standardise on VS Code for Python. The Remote SSH extension allows data scientists to write and debug code on a GPU server from their laptop, seeing the full IDE as if files were local. The Jupyter extension means they never need to switch between browser and editor.' },

  { id:'vsc_02', topic:'VS Code', subtopic:'Debugging',
    theory:'The VS Code debugger is one of its most powerful features. Set breakpoints by clicking left of the line number. Press F5 to start debugging. Execution pauses at breakpoints. Inspect variable values in the Variables panel. Step Over (F10): execute current line. Step Into (F11): enter the called function. Step Out (Shift+F11): finish current function. Debug console evaluates expressions in the current scope.',
    interview:'Debugging in VS Code means setting breakpoints — markers that tell the program to pause at that line. When paused, we can see the exact value of every variable. We can step through code line by line to watch what is happening. This is much more powerful than adding print statements everywhere. The debug console lets us run any Python expression at the paused point.',
    code:'# VS Code debugging workflow\n\n# 1. Click left of line number to set breakpoint\n\n# 2. launch.json (if needed):\n# {\n#   "configurations": [{\n#     "name": "Python: Current File",\n#     "type": "python",\n#     "request": "launch",\n#     "program": "${file}"\n#   }]\n# }\n\n# 3. Press F5 to start\n\n# 4. Debug toolbar:\n# Continue  F5\n# Step Over F10\n# Step Into F11\n# Step Out  Shift+F11\n\n# 5. Debug console:\n# > len(df)\n# > model.feature_importances_',
    realworld:'A data scientist spends 2 hours adding print statements trying to find why their preprocessing function is wrong. A colleague shows them how to set a breakpoint and step through it. They find the bug in 5 minutes — a column name typo that only appears on certain data shapes. Debugging skills directly translate to faster bug resolution.' },

  // SQL
  { id:'sql_01', topic:'SQL', subtopic:'Definition',
    theory:'SQL (Structured Query Language) is the standard language for relational databases. Every data science role requires SQL because data lives in databases. Core operations: SELECT (retrieve), FROM (specify table), WHERE (filter rows), GROUP BY (aggregate per group), HAVING (filter after aggregation), ORDER BY (sort), JOIN (combine tables), LIMIT (restrict count). SQL is declarative — describe what you want, not how to get it.',
    interview:'SQL is the language for querying databases. SELECT says which columns we want. FROM says which table. WHERE filters rows by a condition. GROUP BY groups rows together so we can aggregate per group. HAVING filters the groups after aggregation. ORDER BY sorts the results. JOIN combines data from two tables. Every data science job requires SQL because raw data is almost always in a database.',
    code:'-- Core SQL structure\nSELECT\n    customer_id,\n    COUNT(*)       AS order_count,\n    SUM(amount)    AS total_spend,\n    AVG(amount)    AS avg_order,\n    MAX(order_date) AS last_order\nFROM orders\nWHERE\n    status    = \'completed\'\n    AND order_date >= \'2024-01-01\'\nGROUP BY customer_id\nHAVING total_spend > 1000\nORDER BY total_spend DESC\nLIMIT 100;\n\n-- Use in Python\nimport pandas as pd, sqlite3\nconn = sqlite3.connect("db.sqlite")\ndf   = pd.read_sql_query(\n    "SELECT * FROM orders", conn)',
    realworld:'Netflix uses SQL to query their data warehouse for content performance analytics. A query selects all shows, groups by genre and country, calculates average watch time and completion rate, filters to shows with more than 1 million views, and orders by completion rate. Analysts use this to identify which content types drive the most engagement.' },

  { id:'sql_02', topic:'SQL', subtopic:'Joins',
    theory:'JOINs combine rows from two tables based on a matching condition. INNER JOIN: only rows with a match in both tables. LEFT JOIN: all rows from the left table, matching rows from the right (NULL for no match). RIGHT JOIN: opposite. FULL OUTER JOIN: all rows from both tables. In data science: LEFT JOIN is most common — keep all records from the main table and bring in optional related data.',
    interview:'JOINs combine data from two tables using a shared column. INNER JOIN gives only rows where both tables have a match — customers with no orders do not appear. LEFT JOIN gives all rows from the left table and adds data from the right where it matches — customers with no orders appear but with NULL for order columns. LEFT JOIN is the most common in data work.',
    code:'-- INNER JOIN: only matched rows\nSELECT\n    o.order_id,\n    c.name    AS customer_name,\n    o.amount\nFROM orders o\nINNER JOIN customers c\n    ON o.customer_id = c.id;\n\n-- LEFT JOIN: all orders, customer if exists\nSELECT\n    o.order_id,\n    c.name,      -- NULL if no match\n    o.amount\nFROM orders o\nLEFT JOIN customers c\n    ON o.customer_id = c.id;\n\n-- Multi-table join\nSELECT o.order_id, c.name,\n       p.product_name, o.amount\nFROM orders o\nJOIN customers c ON o.customer_id = c.id\nJOIN products  p ON o.product_id  = p.id;',
    realworld:'A churn analysis pipeline uses multiple LEFT JOINs: customers table, LEFT JOIN to orders (some customers may have no orders), LEFT JOIN to support_tickets, LEFT JOIN to product_usage. Using INNER JOIN would accidentally exclude customers with no orders — exactly the churn candidates most important to identify.' },

  { id:'sql_03', topic:'SQL', subtopic:'Window Functions',
    theory:'Window functions compute aggregations across rows related to the current row without collapsing rows like GROUP BY does. OVER() defines the window. PARTITION BY divides rows into groups but keeps all rows. Key functions: ROW_NUMBER(), RANK(), DENSE_RANK(), LAG(col, n) for value n rows before, LEAD(col, n) for value n rows ahead, SUM/AVG with OVER for running totals.',
    interview:'Window functions are like GROUP BY but they do not collapse rows. They add a new column to every existing row. ROW_NUMBER gives each order a sequential number within each customer\'s orders. Running total adds up amounts as we go down the table. LAG gets the value from the previous row so we can calculate the change from yesterday. Very powerful for time-series analysis and ranking.',
    code:'-- Row number per customer\nSELECT\n    order_id, customer_id, amount,\n    ROW_NUMBER() OVER (\n        PARTITION BY customer_id\n        ORDER BY order_date\n    ) AS order_num\nFROM orders;\n\n-- Running total\nSELECT\n    order_date, amount,\n    SUM(amount) OVER (\n        ORDER BY order_date\n    ) AS running_total\nFROM orders;\n\n-- Compare to previous row\nSELECT\n    order_date, amount,\n    LAG(amount, 1) OVER (\n        ORDER BY order_date) AS prev_amount,\n    amount - LAG(amount,1) OVER (\n        ORDER BY order_date) AS diff\nFROM daily_sales;',
    realworld:'An e-commerce team uses ROW_NUMBER() partitioned by customer_id and ordered by order_date. order_num=1 identifies first purchases, order_num=2 identifies second purchases. Filtering to order_num=2 reveals what customers buy after their first order — key insight for email marketing.' },

  { id:'sql_04', topic:'SQL', subtopic:'CTEs and Subqueries',
    theory:'CTEs (Common Table Expressions) with the WITH clause create named temporary result sets that can be referenced multiple times. CTEs make complex queries readable and maintainable. Subqueries are nested queries — CTEs are more readable for multi-step logic, subqueries are fine for simple one-time use. Multiple CTEs can be chained together with commas.',
    interview:'CTEs let us break a complex query into named steps. Instead of one long nested query, we write WITH customer_totals AS (step 1), segmented AS (step 2), then the final SELECT uses these named results. Each CTE is like a named temporary table that only exists for that query. Complex queries that take a week to understand become readable in minutes with CTEs.',
    code:'-- CTE: readable multi-step query\nWITH\ncustomer_totals AS (\n    SELECT\n        customer_id,\n        COUNT(*)    AS order_count,\n        SUM(amount) AS total_spend\n    FROM orders\n    WHERE status = \'completed\'\n    GROUP BY customer_id\n),\nsegmented AS (\n    SELECT customer_id, total_spend,\n        CASE\n            WHEN total_spend > 10000 THEN \'VIP\'\n            WHEN total_spend > 1000  THEN \'Regular\'\n            ELSE \'Low Value\'\n        END AS segment\n    FROM customer_totals\n)\nSELECT segment, COUNT(*), AVG(total_spend)\nFROM segmented\nGROUP BY segment;',
    realworld:'A fraud analytics team writes a detection query using four CTEs: baseline_behaviour, recent_activity, anomaly_scores, and flagged_customers. Each step builds on the last. The same logic written as nested subqueries would be nearly unreadable. CTEs make it maintainable and easy to test each step independently.' },

  // GIT
  { id:'git_01', topic:'Git', subtopic:'Definition',
    theory:'Git is the standard version control system for tracking changes to code over time. Every change is recorded as a commit with a message. This means you can: go back to any previous state, see what changed and when, work on multiple features using branches, and collaborate without overwriting each other\'s work. Git works locally. GitHub/GitLab are remote hosting services.',
    interview:'Git tracks every change we make to our code over time. Every time we make a meaningful change we commit it with a message. This creates a history we can go back to at any point. Branches let us work on a new feature without affecting the working main code. When the feature is done we merge the branch back to main. git log shows the history. git status shows what has changed.',
    code:'git init                  # new repo\ngit clone URL             # copy remote\n\ngit status                # what changed?\ngit add .                 # stage all\ngit add file.py           # stage one file\ngit commit -m "feat: add feature X"\n\ngit log --oneline -10     # recent commits\ngit diff                  # what changed?\n\n# Branches\ngit checkout -b feature/new-model\ngit checkout main\ngit merge feature/new-model\n\n# Undo\ngit restore file.py       # discard changes\ngit revert HEAD           # undo last commit\ngit reset --soft HEAD~1   # undo, keep changes',
    realworld:'The scikit-learn project on GitHub has over 30,000 commits from 2,000+ contributors over 15 years. Every contributor works on their own branch, submits a pull request, gets reviewed, and maintainers merge it. If a commit introduces a bug, git bisect finds exactly which commit caused it.' },

  { id:'git_02', topic:'Git', subtopic:'Git for ML Best Practices',
    theory:'.gitignore: exclude data files (too large), model files (.pkl, .pt), virtual environments, and .env files with secrets. DVC (Data Version Control) works like Git for large data files and model artefacts. Commit before each experiment so results are always associated with specific code. Use meaningful commit messages that include what changed and why.',
    interview:'For ML projects we must exclude data files and model files from Git because they are too large. The .gitignore file tells Git to ignore specific file types. We commit before each experiment so the code that produced each result is recorded. Meaningful commit messages like "LSTM 2 layers hidden=128 RMSE=4.2" make it easy to understand what each commit changed without reading the code.',
    code:'# .gitignore for ML projects\ndata/          # exclude all data\n*.pkl          # sklearn models\n*.pt           # PyTorch models\n*.h5           # Keras models\nvenv/          # virtual env\n.env           # secrets\n__pycache__/\nmlruns/        # MLflow runs\n\n# Good ML commit messages:\ngit commit -m "exp: LSTM 2 layers hidden=128 RMSE=4.2"\ngit commit -m "fix: correct data leakage in scaler"\ngit commit -m "feat: add lag-7 and lag-30 features"\n\n# Tag important versions:\ngit tag -a v1.0 -m "Production model v1.0"\ngit push origin v1.0',
    realworld:'A Kaggle grandmaster maintains competition solutions in Git with one commit per experiment. The commit message includes CV score and key hyperparameters. After 50+ experiments, they can quickly compare by reading git log and instantly checkout any previous experiment.' },

  // GITHUB
  { id:'gh_01', topic:'GitHub', subtopic:'Definition',
    theory:'GitHub is the most popular platform for hosting Git repositories. It adds collaboration features: Pull Requests (propose and review code changes), Issues (track bugs), Actions (automate CI/CD pipelines), Projects (kanban boards), Wiki (documentation). For ML engineers, GitHub hosts code, not data. A strong GitHub profile is important for job applications.',
    interview:'GitHub hosts our Git repositories in the cloud. We push our local code to GitHub and teammates can clone it. Pull Requests are how we propose changes — instead of pushing directly to main, we push to a branch and open a PR for review. Issues track what needs to be done. GitHub Actions automates testing and deployment when code is pushed.',
    code:'# Core GitHub workflow\n\n# Clone your fork\ngit clone https://github.com/YOU/repo.git\n\n# Create a feature branch\ngit checkout -b feature/my-improvement\n\n# Commit and push\ngit add .\ngit commit -m "feat: improve accuracy"\ngit push origin feature/my-improvement\n\n# Then open a Pull Request on GitHub.com\n\n# Connect local to remote:\ngit remote add origin https://github.com/YOU/repo\ngit push -u origin main\n\n# Sync with original repo:\ngit remote add upstream https://github.com/ORIG/repo\ngit fetch upstream\ngit merge upstream/main',
    realworld:'Every major ML library lives on GitHub — scikit-learn, PyTorch, TensorFlow, LangChain, Hugging Face. When companies interview data scientists, they look at GitHub profiles to see: what projects have they built, how clean is their code, do they write good commit messages. A strong GitHub profile is often more compelling than a resume.' },

  { id:'gh_02', topic:'GitHub', subtopic:'GitHub Actions for ML',
    theory:'GitHub Actions automates workflows triggered by Git events. Pushes and PRs can trigger: running tests, checking code formatting, training models, evaluating performance, and building Docker images. For ML: automatically run model evaluation tests when code changes, check that model performance does not degrade. Workflows are defined in YAML files in .github/workflows/.',
    interview:'GitHub Actions automates things that happen when we push code. The most basic use is running tests automatically every time someone pushes or opens a PR. If tests fail, the PR cannot be merged. For ML projects we can automatically evaluate the model on a test set and fail the check if accuracy drops below a threshold. This prevents accidentally deploying a worse model.',
    code:'# .github/workflows/ml_checks.yml\nname: ML Quality Checks\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v3\n\n      - name: Set up Python\n        uses: actions/setup-python@v4\n        with:\n          python-version: "3.11"\n\n      - name: Install dependencies\n        run: pip install -r requirements.txt\n\n      - name: Run tests\n        run: pytest tests/\n\n      - name: Model performance check\n        run: |\n          python evaluate.py\n          # Fails if accuracy < 0.85',
    realworld:'Spotify\'s ML platform uses GitHub Actions to run automated model evaluation on every PR. The action trains on a fixed dataset, evaluates on a holdout set, and compares against the current production model. If the new code reduces accuracy by more than 1%, the PR is automatically blocked. This guardrail prevents regression bugs from reaching production.' },
];
