/* batch7p1_data.js — GenAI & RAG Pipeline */

window.BATCH_ID    = 'batch7p1';
window.BATCH_TITLE = 'Batch 7 Part 1 — GenAI & RAG Pipeline';

window.TOPIC_COLORS = {
  'RAG':              '#1A237E',
  'Embedding':        '#4A148C',
  'Semantic Search':  '#004D40',
  'Vector Database':  '#BF360C',
  'Pinecone':         '#880E4F',
  'Chunking':         '#E65100',
  'Top-k Retrieval':  '#1B5E20',
  'Relevance':        '#0D47A1',
};

window.FLASHCARD_DATA = [

  { id:'rag_01', topic:'RAG', subtopic:'Definition',
    theory:'RAG (Retrieval-Augmented Generation) combines information retrieval with LLM generation. Instead of relying purely on what an LLM learned during training, RAG first retrieves relevant documents from a knowledge base, then provides those documents as context when generating the answer. This grounds the response in actual facts, reduces hallucination, and enables answers about information not in the LLM\'s training data.',
    interview:'RAG stands for Retrieval-Augmented Generation. It has three steps. First Retrieve — search a database for documents related to the question. Second Augment — put those documents into the prompt as context. Third Generate — the LLM answers using only the retrieved context. The LLM is not guessing from training data but answering from real specific documents. It is the main way to build chatbots over company documents.',
    code:'query = "What is the return policy?"\n\n# Step 1: Retrieve\ndocs = vectorstore.similarity_search(\n    query, k=3)\ncontext = "\\n\\n".join(\n    [d.page_content for d in docs])\n\n# Step 2: Augment\nprompt = f"""Answer ONLY from context.\nContext: {context}\nQuestion: {query}"""\n\n# Step 3: Generate\nfrom langchain_openai import ChatOpenAI\nllm      = ChatOpenAI(model="gpt-4o-mini")\nresponse = llm.invoke(prompt)\nprint(response.content)',
    realworld:'Notion AI uses RAG to answer questions about a user\'s own notes. When you ask "What did we decide in the product meeting last month?", it retrieves relevant meeting notes and generates a summary. Without RAG the LLM could never answer about your private notes since they are not in its training data.' },

  { id:'rag_02', topic:'RAG', subtopic:'Retrieval Step',
    theory:'The retrieval step finds the most relevant documents for a given query. The query is converted to an embedding vector, compared against pre-stored document embeddings using cosine similarity, and top-k most similar documents are returned. Quality of retrieval directly determines quality of the final answer — if wrong documents are retrieved, even a perfect LLM cannot give a correct answer.',
    interview:'The retrieval step is the most important part of RAG. We convert the user question into a vector and find the most similar document vectors in our database. The documents with the highest similarity are retrieved and passed to the LLM. If we retrieve wrong documents, the LLM gives a wrong answer even if it is very capable. Improving retrieval quality has the biggest impact on the system.',
    code:'from langchain_openai import OpenAIEmbeddings\nfrom langchain_community.vectorstores import FAISS\n\nembeddings  = OpenAIEmbeddings()\nvectorstore = FAISS.from_documents(\n    documents, embeddings)\n\nquery = "How do I reset my password?"\n\ndocs_scores = (\n    vectorstore\n    .similarity_search_with_score(query, k=3))\nfor doc, score in docs_scores:\n    print(f"Score: {score:.4f}")\n    print(doc.page_content[:100])',
    realworld:'A legal tech company builds a contract review tool. When a lawyer asks "What are the termination clauses?", retrieval searches 500 contracts and returns the 3 most relevant sections. Getting retrieval right is critical — returning a payment terms section instead of termination clauses gives a completely wrong answer.' },

  { id:'rag_03', topic:'RAG', subtopic:'Augmentation Step',
    theory:'The augmentation step constructs the final prompt by combining retrieved documents with the user question and a system instruction. Tell the LLM to answer ONLY from the context, say "I don\'t know" if the answer is not in the context, and cite the source. Context window size limits how many documents can be included.',
    interview:'The augmentation step builds the final prompt. We combine the retrieved documents and the user question into one prompt. We give clear instructions to only use the context and say "I do not know" if the answer is not there. Including the source of each document allows the answer to be cited. The quality of this prompt template has a big impact on how well the LLM uses the retrieved context.',
    code:'from langchain_core.prompts import (\n    ChatPromptTemplate)\n\ndef build_context(docs):\n    return "\\n\\n---\\n\\n".join([\n        f"Source: {d.metadata.get(\\"source\\",\\"?\\")}\\n"\n        f"{d.page_content}"\n        for d in docs\n    ])\n\nprompt_template = ChatPromptTemplate\\\n    .from_template("""\nAnswer ONLY from the context below.\nIf not in context, say: \'I don\'t know.\'\n\nContext: {context}\nQuestion: {question}\nAnswer:""")',
    realworld:'GitHub Copilot Chat augments each query with current file, related files, and error messages. The augmentation includes instructions like "Answer only about the code shown. Reference specific line numbers." This prevents suggestions that do not match the project\'s coding style.' },

  { id:'rag_04', topic:'RAG', subtopic:'Generation Step',
    theory:'The generation step is where the LLM reads the augmented prompt and generates the final answer. Key settings: temperature=0 for factual Q&A to reduce hallucination. LCEL (LangChain Expression Language) uses the | operator to chain prompt, LLM, and output parser. Streaming sends the answer word by word for better user experience.',
    interview:'The generation step is where the LLM reads our prompt with the retrieved documents and writes an answer. We set temperature to 0 for factual questions so the model gives consistent answers. LCEL chains the prompt template, LLM, and output parser together with the pipe symbol. Streaming sends the answer word by word which feels much more responsive than waiting for the full answer.',
    code:'from langchain_openai import ChatOpenAI\nfrom langchain_core.output_parsers import (\n    StrOutputParser)\n\nllm = ChatOpenAI(\n    model="gpt-4o-mini",\n    temperature=0,\n    max_tokens=500\n)\n\nchain = (\n    prompt_template\n    | llm\n    | StrOutputParser()\n)\n\nresponse = chain.invoke({\n    "context":  context,\n    "question": "What is the refund policy?"\n})\n\n# Streaming:\nfor chunk in chain.stream({"context": context,\n    "question": "What is the refund policy?"}):\n    print(chunk, end="", flush=True)',
    realworld:'Perplexity AI formats answers with inline citations like [1][2] pointing to source documents. Post-processing verifies every factual claim is supported by at least one retrieved source, catching cases where the LLM added unretrieved facts. Temperature near 0 ensures consistent factual responses.' },

  { id:'rag_05', topic:'RAG', subtopic:'RAG vs Fine-tuning',
    theory:'Two ways to adapt an LLM for specific knowledge. RAG adds knowledge at inference time through retrieval — no retraining needed. Fine-tuning bakes knowledge into model weights through additional training. RAG is better when knowledge changes frequently, is confidential, or citations are needed. Fine-tuning is better when specific style or tone is needed. Most production systems use both: fine-tune for style, RAG for current knowledge.',
    interview:'RAG retrieves documents at query time. Fine-tuning trains the model on new data so it memorises information. RAG is better when information changes frequently or needs citations. Fine-tuning is better for specific writing style. Most real systems use both — fine-tune for how to communicate, RAG for what the current facts are.',
    code:'# RAG: knowledge at inference time\n# Pros: updateable, citable, no retraining\n# Cons: retrieval latency, context limits\n\n# Fine-tuning: knowledge in weights\n# Pros: faster inference, specific style\n# Cons: expensive, knowledge goes stale\n\n# Hybrid (best of both):\n# Fine-tune -> style + reasoning\n# RAG       -> up-to-date facts\n\n# Example hybrid system prompt:\n# System: You are a formal banking\n#         assistant. (fine-tuned style)\n# Context: [retrieved policy docs] (RAG)\n# Question: [user query]',
    realworld:'A customer service platform fine-tunes GPT-4o-mini on customer service conversations to learn the bank\'s formal tone. Then applies RAG to retrieve current product terms and interest rates that change monthly. Fine-tuning handles communication style. RAG handles current facts.' },

  // EMBEDDING
  { id:'emb_01', topic:'Embedding', subtopic:'Definition',
    theory:'An embedding is a dense numerical vector representing the meaning of text in a high-dimensional space. Text with similar meaning produces vectors close to each other. Text with different meaning produces vectors far apart. Embeddings capture semantic meaning — "king" and "monarch" have similar embeddings even though the words differ. Created by encoder transformer models trained on massive text corpora.',
    interview:'An embedding is a list of numbers that represents the meaning of a piece of text. Text with similar meaning has vectors close together. So the vector for "What is ML?" and "Explain machine learning" are very close even though the words differ. This is what makes semantic search work — we search by meaning not exact words.',
    code:'from sentence_transformers import (\n    SentenceTransformer)\n\nmodel = SentenceTransformer(\n    "all-MiniLM-L6-v2")\nvec = model.encode(\n    "What is machine learning?")\nprint(f"Shape: {vec.shape}")  # (384,)\n\n# Batch encode\ntexts = ["Hello world", "ML is useful"]\nvecs  = model.encode(texts)\nprint(vecs.shape)  # (2, 384)\n\n# OpenAI (costs money, higher quality)\nfrom langchain_openai import OpenAIEmbeddings\nembeddings = OpenAIEmbeddings(\n    model="text-embedding-3-small")  # 1536 dims',
    realworld:'Spotify uses embeddings to represent both songs and user listening history as vectors. A user who listens to indie folk has a profile vector close to indie folk songs. When recommending, Spotify finds songs whose vectors are closest to the user profile — discovering similar music by meaning rather than metadata tags.' },

  { id:'emb_02', topic:'Embedding', subtopic:'Cosine Similarity',
    theory:'Cosine similarity measures the angle between two vectors — how similar their directions are. It ignores magnitude and focuses on direction. Value ranges from -1 (completely opposite) to +1 (identical direction). For normalised embeddings, cosine similarity equals the dot product, which is faster to compute. Standard metric for comparing text embeddings. Above 0.8 usually indicates very similar meaning.',
    interview:'Cosine similarity measures how similar two vectors are by the angle between them. Score of 1 means identical meaning. Score of 0 means unrelated. When we search a vector database we compute cosine similarity between the query vector and all document vectors and return the most similar ones. We normalise vectors first so dot product equals cosine similarity which is faster to compute.',
    code:'import numpy as np\nfrom sklearn.metrics.pairwise import (\n    cosine_similarity)\nfrom sentence_transformers import (\n    SentenceTransformer)\n\nmodel = SentenceTransformer("all-MiniLM-L6-v2")\n\nvec1 = model.encode("What is ML?")\nvec2 = model.encode("Explain machine learning")\nvec3 = model.encode("How do I cook pasta?")\n\nsim_12 = cosine_similarity([vec1],[vec2])[0][0]\nsim_13 = cosine_similarity([vec1],[vec3])[0][0]\nprint(f"ML vs ML:    {sim_12:.4f}")  # ~0.92\nprint(f"ML vs pasta: {sim_13:.4f}")  # ~0.15',
    realworld:'LinkedIn matches job postings with candidate profiles using cosine similarity. A job for "Senior Data Scientist" and a profile with "Machine Learning Engineer, 5 years experience" have similarity ~0.87 — semantically similar even though exact titles differ. This enables relevant job recommendations beyond keyword matching.' },

  // SEMANTIC SEARCH
  { id:'sem_01', topic:'Semantic Search', subtopic:'Definition',
    theory:'Semantic search finds documents based on meaning rather than exact keyword matching. Traditional keyword search fails when the query and document use different words for the same concept ("car" vs "automobile", "fix" vs "resolve"). Semantic search converts both query and documents to embeddings and finds closest matches in vector space. It understands paraphrases, synonyms, and conceptual relationships.',
    interview:'Semantic search finds documents by meaning not exact words. If you search "car problems", keyword search misses documents saying "vehicle issues". Semantic search finds them because car and vehicle have similar embeddings. We convert the query to a vector, compare it with all document vectors, and return the most similar ones. Much better than keyword matching for finding relevant information.',
    code:'from sentence_transformers import SentenceTransformer\nfrom sklearn.metrics.pairwise import cosine_similarity\nimport numpy as np\n\nmodel = SentenceTransformer("all-MiniLM-L6-v2")\n\ndocs = [\n    "How to reset your password",\n    "Steps to change login credentials",\n    "Refund and return policy",\n]\ndoc_embs = model.encode(docs)\n\nquery = "I forgot my password"\nq_emb = model.encode([query])\n\nsims  = cosine_similarity(q_emb, doc_embs)[0]\ntop_k = np.argsort(sims)[::-1][:2]\nfor i in top_k:\n    print(f"{sims[i]:.3f}: {docs[i]}")',
    realworld:'Stack Overflow uses semantic search to find duplicate questions. "Why does my Python loop not stop?" finds existing answers to "Python infinite while loop debugging" and "How to break out of a loop in Python" — different words but same meaning. This reduces duplicate answers and helps users find solutions faster.' },

  { id:'sem_02', topic:'Semantic Search', subtopic:'Hybrid Search',
    theory:'Hybrid search combines keyword search (BM25) and semantic search for better results than either alone. Keyword search: fast, works well for exact terms like product codes, technical terms. Fails on paraphrases. Semantic search: finds conceptually similar content. Can struggle with rare technical terms. Hybrid: run both, merge results using Reciprocal Rank Fusion (RRF). Consistently outperforms either method alone.',
    interview:'Keyword search looks for exact word matches — fast and good for product codes. Semantic search looks for meaning matches — better for questions and concepts. Hybrid search combines both and gives the best of both worlds. For a customer support chatbot, keyword search finds exact product names and semantic search finds related questions phrased in different ways.',
    code:'from langchain_community.retrievers import (\n    BM25Retriever)\nfrom langchain.retrievers import (\n    EnsembleRetriever)\n\nbm25   = BM25Retriever.from_documents(documents)\nbm25.k = 3\n\nvector = vectorstore.as_retriever(\n    search_kwargs={"k": 3})\n\nhybrid = EnsembleRetriever(\n    retrievers=[bm25, vector],\n    weights=[0.4, 0.6]  # 40% BM25, 60% semantic\n)\n\ndocs = hybrid.invoke("password reset steps")',
    realworld:'Elasticsearch\'s hybrid search combines BM25 with dense vector search. A search for "comfortable running shoes for flat feet" uses BM25 to match "running shoes" exactly and semantic search to find "arch support trainers". Combined results are 34% more likely to lead to a purchase than keyword-only search.' },

  // VECTOR DATABASE
  { id:'vdb_01', topic:'Vector Database', subtopic:'Definition',
    theory:'A vector database is purpose-built for storing, indexing, and querying high-dimensional vectors efficiently. Regular databases store structured rows and columns. Vector databases support fast approximate nearest-neighbour (ANN) search. Also support metadata filtering alongside vector search. Options: FAISS (local, in-memory), Chroma (local, persists to disk), Pinecone (managed cloud), Weaviate, Qdrant.',
    interview:'A vector database stores embedding vectors and lets us search them very quickly. When we add documents to a RAG system, we convert them to vectors and store in the vector database. When a question comes in, we convert it to a vector and the database finds the most similar stored vectors in milliseconds — even across millions of documents.',
    code:'# FAISS - local, in-memory\nimport faiss, numpy as np\n\ndim   = 384\nindex = faiss.IndexFlatIP(dim)\nvectors = np.random.rand(1000, dim).astype("float32")\nfaiss.normalize_L2(vectors)\nindex.add(vectors)\n\nquery = np.random.rand(1, dim).astype("float32")\nfaiss.normalize_L2(query)\nD, I = index.search(query, k=5)\n\n# Chroma - persists to disk\nimport chromadb\nclient = chromadb.PersistentClient(path="./chroma_db")\ncol    = client.get_or_create_collection("my_docs")',
    realworld:'Airbnb uses a vector database to power listing search. Every listing is a vector capturing location, amenities, style, and reviews. When a user searches "cosy cabin near mountains for family", the query vector is compared against millions of listing vectors and the 20 most similar are returned in under 50ms — impossible with traditional SQL.' },

  { id:'vdb_02', topic:'Vector Database', subtopic:'FAISS',
    theory:'FAISS (Facebook AI Similarity Search) by Meta is an open-source library for efficient similarity search. Runs in memory with no external dependencies. Index types: IndexFlatL2 (exact, accurate but slow for large collections), IndexFlatIP (inner product, normalise vectors first for cosine), IndexIVFFlat (approximate, clusters vectors, much faster for millions of vectors). LangChain\'s FAISS wrapper adds easy document management.',
    interview:'FAISS is a free library from Meta for fast similarity search. We store all our document vectors in a FAISS index in memory. When we search, FAISS finds the most similar stored vectors very fast. IndexIVFFlat groups vectors into clusters and only searches relevant ones — much faster for millions of vectors. LangChain wraps FAISS to make it easy to use with documents.',
    code:'from langchain_community.vectorstores import FAISS\nfrom langchain_openai import OpenAIEmbeddings\n\nembeddings  = OpenAIEmbeddings()\nvectorstore = FAISS.from_documents(\n    documents, embeddings)\n\n# Save to disk\nvectorstore.save_local("faiss_index")\n\n# Load from disk\nvectorstore = FAISS.load_local(\n    "faiss_index",\n    embeddings,\n    allow_dangerous_deserialization=True\n)\n\ndocs = vectorstore.similarity_search(\n    "reset password", k=3)',
    realworld:'Meta uses FAISS internally to search across billions of post vectors for content recommendation. Instagram\'s content discovery finds posts similar to ones you have engaged with, from a pool of 100 billion indexed posts. The scale and speed requirements made FAISS necessary.' },

  { id:'vdb_03', topic:'Vector Database', subtopic:'Chroma',
    theory:'Chroma is an open-source vector database designed for AI applications. Easy to set up, runs locally with automatic disk persistence, clean Python API. Supports metadata filtering alongside vector search. Integrates natively with LangChain. Good for development and small-to-medium production. Supports multiple collections. Can also run as a server for multi-user access.',
    interview:'Chroma is an easy-to-use vector database that saves data to your local disk automatically. We just add documents and search. The metadata filter is very useful — we can search only within a specific document category or date range. Chroma is the most common choice for RAG prototypes and small production systems because it requires no infrastructure setup.',
    code:'from langchain_community.vectorstores import Chroma\nfrom langchain_openai import OpenAIEmbeddings\n\nembeddings  = OpenAIEmbeddings()\nvectorstore = Chroma(\n    collection_name="my_docs",\n    embedding_function=embeddings,\n    persist_directory="./chroma_db"\n)\n\nvectorstore.add_documents(documents)\n\n# Search with metadata filter\ndocs = vectorstore.similarity_search(\n    query="return policy",\n    k=3,\n    filter={"source": "policy_doc.pdf"}\n)',
    realworld:'A legal startup stores contract clauses in Chroma with metadata including contract_type, company, and date. When a lawyer queries "liability limitation clauses for SaaS contracts from 2023", Chroma restricts the search by metadata, returning only relevant clauses from that specific category and year.' },

  // PINECONE
  { id:'pin_01', topic:'Pinecone', subtopic:'Definition',
    theory:'Pinecone is a fully managed cloud vector database. No infrastructure to set up — it handles scaling, replication, and updates automatically. Key features: serverless and pod-based tiers, namespaces for logical data separation per user or tenant, metadata filtering, hybrid search. Best for production applications where reliability and scale matter. Trade-off: costs money vs self-hosted free options.',
    interview:'Pinecone is a managed vector database in the cloud. We do not set up servers — Pinecone handles everything. We create an index, upload vectors with metadata, and query. It scales automatically as data grows. Namespaces separate different users\' data. It costs more than running FAISS locally but saves a lot of engineering time for production systems that need high availability.',
    code:'from pinecone import Pinecone, ServerlessSpec\n\npc = Pinecone(api_key="YOUR_KEY")\n\npc.create_index(\n    name="my-index",\n    dimension=1536,\n    metric="cosine",\n    spec=ServerlessSpec(\n        cloud="aws", region="us-east-1")\n)\n\nidx = pc.Index("my-index")\n\nidx.upsert(vectors=[\n    ("id1", [0.1]*1536,\n     {"source": "doc1", "page": 1}),\n])\n\nresult = idx.query(\n    vector=[0.1]*1536,\n    top_k=5,\n    include_metadata=True)',
    realworld:'Notion uses Pinecone to power AI search across user workspaces. Each user\'s notes are stored with the user ID as namespace. When a user searches, Pinecone restricts results to only their namespace. Pinecone\'s managed scaling handles millions of users without Notion engineers managing vector database infrastructure.' },

  { id:'pin_02', topic:'Pinecone', subtopic:'Namespaces',
    theory:'Namespaces provide logical separation within a single Pinecone index. Vectors in different namespaces are completely isolated — a query against namespace "user_123" only searches that namespace. Use cases: separate data per user in a multi-tenant app, separate data versions, separate dev and prod. No extra cost for namespaces. Essential for SaaS products where each customer has their own documents.',
    interview:'Namespaces in Pinecone separate data for different users in the same index. User A\'s search only returns results from their namespace. User B cannot see User A\'s data. This is essential for SaaS products where each customer has their own documents. Without namespaces we would need a separate index per customer which is expensive.',
    code:'idx = pc.Index("rag-index")\n\ndef upsert_for_tenant(tenant_id,\n                       chunks, embeddings):\n    vectors = [\n        {\n            "id":     f"{tenant_id}_{i}",\n            "values": emb,\n            "metadata": {"text": chunk}\n        }\n        for i, (chunk, emb)\n        in enumerate(zip(chunks, embeddings))\n    ]\n    idx.upsert(\n        vectors=vectors,\n        namespace=tenant_id\n    )\n\ndef query_for_tenant(tenant_id, query_emb):\n    return idx.query(\n        vector=query_emb,\n        top_k=5,\n        namespace=tenant_id,\n        include_metadata=True\n    )',
    realworld:'A B2B document intelligence SaaS uses Pinecone namespaces to serve 500 enterprise clients from one index. Each client\'s documents are under their company ID namespace. This satisfies enterprise data privacy requirements at the database level, not just application code.' },

  // CHUNKING
  { id:'chu_01', topic:'Chunking', subtopic:'Definition',
    theory:'Chunking is splitting large documents into smaller pieces before embedding and storing in a vector database. We cannot embed an entire 100-page PDF as one vector — the embedding model has a token limit, and one vector for 100 pages cannot capture all specific details. Smaller chunks allow more precise retrieval. Chunk size and overlap are the key parameters that significantly affect RAG quality.',
    interview:'Chunking means splitting a large document into smaller pieces. We cannot embed an entire book as one vector because the model has a size limit and one vector cannot capture all the specific details. By splitting into chunks of say 500 characters, we embed each chunk separately and retrieve the specific chunk that answers the question. Chunk size and overlap are important parameters to tune.',
    code:'from langchain.text_splitter import (\n    RecursiveCharacterTextSplitter)\n\nsplitter = RecursiveCharacterTextSplitter(\n    chunk_size=500,\n    chunk_overlap=50,\n    separators=[\n        "\\n\\n",  # paragraph first\n        "\\n",    # then line\n        ". ",    # then sentence\n        " ",     # then word\n        ""       # then character\n    ]\n)\n\nchunks = splitter.split_documents(pages)\nprint(f"Chunks: {len(chunks)}")\nprint(chunks[0].page_content[:200])',
    realworld:'A legal tech company processes 500-page M&A contracts. Chunking by paragraph with 50-token overlap gives 2,400 chunks per contract. Without chunking, one vector per document cannot pinpoint which clause answers "What are the indemnification limits?" Paragraph-level chunks retrieve the exact relevant clause.' },

  { id:'chu_02', topic:'Chunking', subtopic:'Chunk Size Trade-offs',
    theory:'Too small (less than 100 tokens): chunks lack context, a sentence alone may be ambiguous, retrieval returns many small irrelevant fragments. Too large (more than 1000 tokens): fewer chunks means less precise retrieval, embedding averages too much text losing specificity. Sweet spot: 200-500 tokens with 10-20% overlap. Overlap ensures information at chunk boundaries is not lost between adjacent chunks.',
    interview:'Chunk size controls the trade-off between precision and context. Small chunks are precise but may lack context — a sentence like "it was rejected" is meaningless alone. Larger chunks have more context but are harder to match precisely. We start with 500 characters and 50 character overlap, test with real questions, and adjust based on what works best.',
    code:'from langchain.text_splitter import (\n    RecursiveCharacterTextSplitter)\n\n# Small - precise but may lack context\nsmall = RecursiveCharacterTextSplitter(\n    chunk_size=200, chunk_overlap=20)\n\n# Medium - good balance (start here)\nmed   = RecursiveCharacterTextSplitter(\n    chunk_size=500, chunk_overlap=50)\n\n# Large - more context, less precise\nlarge = RecursiveCharacterTextSplitter(\n    chunk_size=1000, chunk_overlap=100)\n\n# Evaluate hit rate:\ndef hit_rate(questions, answers,\n             vectorstore, k=3):\n    hits = sum(\n        any(a in d.page_content\n            for d in vectorstore\n            .similarity_search(q, k=k))\n        for q, a in zip(questions, answers)\n    )\n    return hits / len(questions)',
    realworld:'Notion tested chunk sizes for AI search. 512 tokens with 64 token overlap was optimal for structured notes. Smaller chunks (128 tokens) gave too many irrelevant fragments. Larger chunks (2048 tokens) worked for summary questions but poorly for specific facts.' },

  // TOP-K RETRIEVAL
  { id:'topk_01', topic:'Top-k Retrieval', subtopic:'Definition',
    theory:'Top-k retrieval returns the k most similar documents to a query. k is a hyperparameter. Too small: might miss the document that actually answers the question. Too large: includes noisy irrelevant context that confuses the LLM and wastes context window tokens. Typical values: k=3 to k=10. Evaluate by checking how often the correct document appears in top-k results (hit rate).',
    interview:'Top-k means we retrieve the k most similar documents to the question. If k=3 we get 3 documents. Too small and we might miss the right answer. Too large and we flood the LLM with irrelevant context. We start with k=3 to k=5 and test with real questions. An adaptive approach uses a similarity threshold instead of a fixed k.',
    code:'docs = vectorstore.similarity_search(\n    query, k=5)\n\n# With scores:\ndocs_scores = (\n    vectorstore\n    .similarity_search_with_score(query, k=5))\nfor doc, score in docs_scores:\n    print(f"{score:.4f}: "\n          f"{doc.page_content[:80]}")\n\n# Adaptive threshold:\ndef retrieve_adaptive(query,\n                      threshold=0.7,\n                      max_k=10):\n    docs_scores = (\n        vectorstore\n        .similarity_search_with_score(\n            query, k=max_k))\n    return [\n        doc for doc, score\n        in docs_scores\n        if score >= threshold\n    ]',
    realworld:'Slack\'s search uses adaptive k — starts with k=10 candidates, scores with a reranker, returns top 3. For simple queries the top 1 is usually sufficient. For complex queries requiring synthesis, up to 8 are included. The adaptive approach balances precision and recall better than fixed k.' },

  { id:'topk_02', topic:'Top-k Retrieval', subtopic:'Re-ranking',
    theory:'Re-ranking is a two-stage retrieval approach. Stage 1: fast top-k vector retrieval with large k (e.g., k=20). Stage 2: a cross-encoder model re-scores all retrieved documents by reading query and document together — much more accurate than cosine similarity alone. Return top-3 to top-5 from re-ranked list. Cross-encoders understand query-document relationships better than bi-encoder cosine similarity.',
    interview:'Re-ranking is a two-stage process to improve retrieval quality. First we retrieve a larger set like top-20 using fast vector search. Then a cross-encoder model reads the query and each document together and gives a more accurate relevance score. We re-order by this score and return the top 3 or 5. This is slower but gives much better results.',
    code:'from sentence_transformers import CrossEncoder\n\n# Stage 1: fast broad retrieval\ndocs_initial = vectorstore.similarity_search(\n    query, k=20)\n\n# Stage 2: cross-encoder re-ranking\nreranker = CrossEncoder(\n    "cross-encoder/ms-marco-MiniLM-L-6-v2")\n\npairs  = [(query, doc.page_content)\n          for doc in docs_initial]\nscores = reranker.predict(pairs)\n\nranked = sorted(\n    zip(scores, docs_initial),\n    key=lambda x: x[0], reverse=True\n)\n\ntop_docs = [doc for _, doc in ranked[:5]]',
    realworld:'Cohere\'s Rerank API is used by enterprise RAG systems. A legal research tool retrieves top-50 case law chunks using FAISS, then uses Cohere Rerank to score each against the query. Re-ranking increases correct answers from 67% to 84%, at a cost of 50ms additional latency.' },

  // RELEVANCE
  { id:'rel_01', topic:'Relevance', subtopic:'RAGAS Metrics',
    theory:'RAGAS provides automated metrics for RAG quality. Faithfulness (0-1): what fraction of claims in the answer are supported by retrieved context — low score means LLM is hallucinating. Answer Relevancy (0-1): how relevant is the answer to the question. Context Precision (0-1): what fraction of retrieved context is actually relevant — low means wrong documents retrieved. Context Recall (0-1): what fraction of necessary information was retrieved.',
    interview:'RAGAS gives four scores. Faithfulness tells us if the LLM stuck to context or made things up. Answer relevancy tells us if the answer actually addressed the question. Context precision tells us if retrieved documents were relevant. Context recall tells us if we retrieved all needed information. If faithfulness is low we fix the prompt. If context precision is low we fix the chunking or embedding model.',
    code:'from ragas import evaluate\nfrom ragas.metrics import (\n    faithfulness,\n    answer_relevancy,\n    context_precision,\n    context_recall\n)\nfrom datasets import Dataset\n\ndata = {\n    "question":     [q1, q2],\n    "answer":       [a1, a2],\n    "contexts":     [[c1_1, c1_2], [c2_1]],\n    "ground_truth": [gt1, gt2]\n}\ndataset = Dataset.from_dict(data)\n\nresult = evaluate(\n    dataset=dataset,\n    metrics=[\n        faithfulness, answer_relevancy,\n        context_precision, context_recall\n    ]\n)\nprint(result)',
    realworld:'A fintech company evaluates their regulatory compliance chatbot monthly using RAGAS. After a chunking improvement, context precision improved from 0.61 to 0.79. After a prompt revision instructing the LLM to cite specific regulation numbers, faithfulness improved from 0.71 to 0.91.' },
];
