/* batch10_data.js — Professional Skills */

window.BATCH_ID    = 'batch10';
window.BATCH_TITLE = 'Batch 10 — Professional Skills';

window.TOPIC_COLORS = {
  'Stakeholder Communication': '#1A237E',
  'Business Impact':           '#4A148C',
  'Project Lifecycle':         '#004D40',
  'Professional Skills':       '#BF360C',
};

window.FLASHCARD_DATA = [

  // STAKEHOLDER COMMUNICATION
  { id:'sc_01', topic:'Stakeholder Communication', subtopic:'Definition',
    theory:'A stakeholder is anyone who is affected by or has an interest in your project. Types: business owners (want business outcomes and ROI), product managers (want features on time), data engineers (need data requirements), DevOps (need deployment specs), end users (need the product to work well), executives (want high-level business impact). Understanding who your stakeholders are and what they care about is the first step to effective communication.',
    interview:'A stakeholder is anyone who cares about the project. Different stakeholders want different things. Executives want to know the business impact in money or percentage improvements. Managers want to know if the project is on track and what the risks are. Data engineers want technical specifications. The mistake most data scientists make is explaining everything in technical terms to everyone — we need to adjust what we say based on who we are talking to.',
    code:'# Stakeholder communication templates:\n\n# What each stakeholder wants:\n# Executive:    business impact + ROI\n# Manager:      project status + risks\n# Data Engineer: data pipeline specs\n# End user:     does it work? is it fast?\n# Regulator:    compliance + auditability\n\n# Stakeholder map:\n# HIGH INTEREST / HIGH POWER -> Manage closely\n# HIGH INTEREST / LOW POWER  -> Keep informed\n# LOW INTEREST / HIGH POWER  -> Keep satisfied\n# LOW INTEREST / LOW POWER   -> Monitor',
    realworld:'Google\'s AlphaFold team communicated the same breakthrough to three audiences: scientific journals (full technical detail), pharma executives (which drug discovery problems this solves and cost reduction), and the general public (they solved a 50-year-old biology problem). Same achievement, completely different communication for each audience.' },

  { id:'sc_02', topic:'Stakeholder Communication', subtopic:'Translating Technical Results',
    theory:'The most important communication skill for a data scientist is translating technical metrics into business language. Nobody outside the data team understands RMSE, AUC, or F1 score. Translation framework: technical metric → what it means in operation → what that means for the business. Always pair a metric with context: "87% accuracy means we now correctly approve 160 more legitimate loan applications per day while blocking the same number of fraudulent ones."',
    interview:'Translating technical results means turning numbers like accuracy or RMSE into business language that managers and executives can understand. Instead of saying "our F1 score improved from 0.74 to 0.89", we say "we reduced false alarms from 30 per day to 5 per day, which saves the operations team 2 hours of investigation time daily." We always answer the "so what" question — why does this metric improvement matter for the business?',
    code:'# Metric translation templates:\n\n# Accuracy improvement:\n# "Model accuracy improved from 71% to 87%"\n# -> "We now correctly handle 160 more\n#    cases per day"\n# -> "Saves Rs 83L in manual review\n#    costs per year"\n\n# RMSE reduction:\n# "RMSE reduced from 18 to 6"\n# -> "Forecasts off by 6 units on average\n#    instead of 18"\n# -> "Better forecasting = Rs 30L less in\n#    overstock/stockout costs annually"\n\n# Always ask: "So what? Why does this\n# number matter to the business?"',
    realworld:'Netflix\'s recommendation team presents to executives: "Our new model increased average viewing time by 4 minutes per user per day. With 200 million subscribers, that is 800 million additional viewing minutes daily. Each extra minute of daily viewing reduces monthly churn by 0.02%, saving approximately $40 million in annual subscription revenue."' },

  { id:'sc_03', topic:'Stakeholder Communication', subtopic:'Update Structure',
    theory:'Clear update structure helps stakeholders understand project status quickly. The pyramid principle: lead with the conclusion, then provide supporting detail. Structure: (1) Bottom line upfront — current status in one sentence. (2) Key achievements this period. (3) Metrics — what the numbers say. (4) Blockers. (5) Next steps. This format respects the stakeholder\'s time and lets them stop reading at any point and still have the key information.',
    interview:'A good project update follows the pyramid principle — the most important information first. Start with one sentence saying whether the project is on track or not. Then key achievements. Then metrics in a simple table comparing baseline, current, and target. Then blockers. Then next steps. A busy manager should be able to read just the first two lines and know if they need to worry.',
    code:'# Update template:\n\n# STATUS UPDATE: [Project Name]\n# Date: [Date]\n# Status: ON TRACK / AT RISK / BLOCKED\n\n# SUMMARY (1 sentence):\n# Model training complete, deploying\n# to staging this week.\n\n# THIS WEEK:\n# - Trained final XGBoost model\n# - F1: 0.87 (target: 0.85) [ACHIEVED]\n\n# METRICS:\n# Metric    | Baseline | Current | Target\n# Accuracy  | 71%      | 87%     | 85%\n# Latency   | -        | 45ms    | <100ms\n\n# BLOCKERS:\n# - Awaiting data team to fix null\n#   values in vendor_id column\n\n# NEXT STEPS:\n# - Deploy to staging by Friday\n# - Production go-live: Jan 20',
    realworld:'Amazon\'s internal project updates follow a 6-page memo format starting with an executive summary. Jeff Bezos famously banned PowerPoint presentations internally because they hide weak thinking behind bullet points. The narrative format forces clear thinking, and the pyramid structure ensures the most important information is always at the top.' },

  { id:'sc_04', topic:'Stakeholder Communication', subtopic:'Presenting to Different Audiences',
    theory:'Tailor depth and language to the audience. Executive (C-Suite): 1-2 slides, business metrics only, no technical terms, lead with recommendation. Manager update: 5-10 minutes, project status, risks, blockers, metrics vs targets. Technical peer review: full detail, methodology, assumptions, limitations. End user training: hands-on demo, focus on what they need to do. Rule: if your audience cannot explain your point to someone else after your presentation, you pitched at the wrong level.',
    interview:'We adjust how we present based on who we are talking to. For an executive, two slides maximum — one showing the business outcome in rupees saved, one asking for the decision or budget. For a manager, a 10-minute update covering status and blockers. For a technical team, 30 minutes with full methodology. For end users, a hands-on demo. The same presentation for all audiences is always wrong for all of them.',
    code:'# EXECUTIVE (C-Suite) - 2 slides:\n# Slide 1: Business outcome\n#   "Fraud detection saved Rs 2.4Cr\n#    in Q3, 34% reduction in fraud losses"\n# Slide 2: Decision needed\n#   "Approve production deployment?\n#    Investment: 2 weeks eng time"\n\n# MANAGER - 10 min update:\n#   Status, metrics table, blockers, ETA\n\n# TECHNICAL TEAM - 30 min review:\n#   Data pipeline, model architecture,\n#   evaluation, edge cases, monitoring plan\n\n# END USER - 20 min training:\n#   What the tool does\n#   How to use it (demo)\n#   What to do if it is wrong\n#   Who to call if stuck',
    realworld:'Palantir sends three different people to present the same analytics platform: CEO meeting gets 15-minute business outcomes summary, operations manager gets 1-hour workflow demonstration, IT team gets 2-hour technical architecture deep-dive. Same product, completely different presentation. This approach dramatically improves deal closure rates.' },

  // BUSINESS IMPACT
  { id:'bi_01', topic:'Business Impact', subtopic:'Quantifying Impact',
    theory:'Every ML project needs a clear business impact statement. Framework: (1) Identify the metric that changes. (2) Measure the baseline. (3) Measure the improvement. (4) Convert to business value (multiply by volume and unit cost). Example: reducing manual review time from 10 minutes to 2 minutes per case, with 500 cases per day at Rs 500 per hour = 500 cases × 8 minutes × Rs 8.33 per minute = Rs 33,300 saved daily = Rs 1 crore saved annually.',
    interview:'Quantifying impact means converting model improvements into rupees or percentages that the business cares about. We find the baseline before our project, measure the improvement, then multiply by volume and unit cost to get financial impact. Presenting this number is much more powerful than presenting an F1 score.',
    code:'# Business impact calculation template:\n\n# Format:\n# [Metric] improved from [baseline]\n# to [current] on [volume] units\n# = [business value] per [time period]\n\n# Fraud detection:\n# False negative rate: 40% -> 12%\n# Daily transactions: 50,000\n# Average fraud amount: Rs 2,000\n# Annual fraud prevented:\n# 50000 * 365 * 0.28 * 2000 = Rs 102Cr\n\n# Processing time:\n# Review time: 10min -> 2min per case\n# Volume: 500 cases/day\n# Cost: Rs 500/hour = Rs 8.33/min\n# Daily saving: 500 * 8min * 8.33 = Rs 33,300\n# Annual: Rs 33,300 * 250 = Rs 83 lakh',
    realworld:'Uber\'s pricing ML team quantifies: "Dynamic pricing optimisation increased revenue per ride by 3.2% while maintaining driver utilisation above 85%. At 20 million rides per day globally, a 3.2% revenue improvement at average Rs 250 per ride = Rs 16 crore additional daily revenue." This number, not the model\'s RMSE, gets the CEO\'s attention.' },

  { id:'bi_02', topic:'Business Impact', subtopic:'ROI and Cost-Benefit Analysis',
    theory:'ROI (Return on Investment) = (Benefit - Cost) / Cost × 100%. Every ML project needs a cost-benefit analysis. Costs: engineering time (development + maintenance), infrastructure (cloud compute, storage), data labelling, monitoring. Benefits: revenue increase, cost reduction, risk reduction, time saved. Payback period: how long until benefits exceed costs. Presenting ROI is the most compelling way to justify continued investment.',
    interview:'ROI is return on investment — how much we get back for every rupee we spend. We add up all costs — developer time, cloud computing, maintenance — and compare to all benefits — money saved, revenue increased. A 662% ROI means for every rupee invested we got back 6.62 rupees. This number justifies the project to any executive.',
    code:'# ROI calculation:\n\n# COSTS:\n# Development: 4 engineers x 3 months\n#              At Rs 1.5L/month = Rs 18L\n# Infrastructure: Rs 50K/month = Rs 6L/yr\n# Maintenance: 0.5 engineer/year = Rs 9L\n# Total Year 1: Rs 18L + 6L = Rs 24L\n\n# BENEFITS:\n# Fraud prevented: Rs 1Cr/year\n# Manual review saved: Rs 83L/year\n# Total annual benefit: Rs 1.83Cr\n\n# ROI Year 1:\n# (1.83Cr - 24L) / 24L = 662%\n\n# Payback period:\n# 24L / (1.83Cr/12) = 1.6 months\n\n# Presentation:\n# Investment: Rs 24L\n# Annual benefit: Rs 1.83Cr\n# ROI: 662% | Payback: 1.6 months',
    realworld:'DataRobot showed a tier-1 Indian bank: development cost Rs 45L, annual benefit Rs 3.2Cr (reduced defaults + faster approvals = more customers). ROI = 611% in year 1, payback in 1.7 months. This ROI analysis converted a pilot into a company-wide rollout covering 15 million loan applications annually. Technical metrics did not close the deal. The ROI calculation did.' },

  { id:'bi_03', topic:'Business Impact', subtopic:'Failure and Risk Communication',
    theory:'Communicating failures and risks honestly is as important as presenting successes. When a model performs worse than expected: own it, explain the root cause, and present a concrete recovery plan. Never hide bad news — it damages trust far more when discovered later. Framework: (1) State the situation clearly. (2) Explain root cause. (3) State the impact. (4) Present mitigation plan. (5) Give revised timeline.',
    interview:'When something goes wrong with a model in production, we communicate it clearly and quickly. We say what happened, why it happened, what the impact is in business terms, what we are doing right now, and when it will be fixed. We never hide bad news or use vague language. Being direct and having a plan already builds trust even when delivering bad news.',
    code:'# Bad news communication template:\n\n# SITUATION:\n# Model performance below target.\n# Current: 79% (target: 85%)\n\n# ROOT CAUSE:\n# Data drift identified:\n# - feature "device_type" has new\n#   categories added in January\n#   not in training data\n\n# IMPACT:\n# Estimated Rs 2L/day in additional\n# manual review costs\n\n# MITIGATION PLAN:\n# Short term (this week):\n#   Revert to rule-based fallback\n# Medium term (2 weeks):\n#   Retrain with new categories\n# Long term (1 month):\n#   Implement automated drift detection\n\n# REVISED TIMELINE:\n# Full performance restored: Feb 7',
    realworld:'When Amazon\'s recommendation model had a bug for 6 hours, the team sent a clear incident report within 2 hours: estimated impact Rs 15Cr, root cause (caching bug), immediate fix applied, post-mortem scheduled. Rapid transparent communication maintained trust. Contrast with a startup that hid model degradation for 3 weeks — when the client discovered it independently, the contract was terminated immediately.' },

  // PROJECT LIFECYCLE
  { id:'pl_01', topic:'Project Lifecycle', subtopic:'ML Project Phases',
    theory:'A typical ML project phases: (1) Problem definition — translate business problem into ML task, define success metrics, estimate feasibility. (2) Data collection and EDA. (3) Feature engineering. (4) Modelling — baseline, iteration, tuning. (5) Evaluation — honest assessment on held-out data, business metric calculation. (6) Deployment — serving infrastructure, monitoring setup. (7) Monitoring and maintenance — ongoing tracking, periodic retraining.',
    interview:'An ML project has clear phases. First we define the problem and success metrics with the business team. Then we explore the data. Then we engineer features and train models. Then we evaluate honestly on held-out data. Then we deploy and set up monitoring. Each phase has a clear deliverable and a stakeholder checkpoint. Skipping phases — like going straight to modelling without problem definition — is the most common cause of ML projects that technically work but deliver no business value.',
    code:'# ML project timeline template:\n\n# Week 1-2: Problem Definition\n# - Define success metrics with business\n# - Assess data availability\n# - Feasibility check\n# Deliverable: project charter\n\n# Week 3-4: Data & EDA\n# - Data collection and cleaning\n# - EDA and feature assessment\n# Deliverable: EDA report\n\n# Week 5-7: Modelling\n# - Baseline model\n# - Feature engineering iteration\n# Deliverable: validated model\n\n# Week 8: Evaluation & Sign-off\n# - Business metric calculation\n# - Stakeholder review\n\n# Week 9-10: Deployment\n# - API + staging + monitoring\n\n# Ongoing: Monitoring\n# - Weekly performance reports',
    realworld:'Spotify\'s annual Wrapped feature follows strict phase gates: problem definition in July, data exploration in August, modelling September-October, staging deployment in November, production launch in December. Each phase has a go/no-go checkpoint with the product team. Missing the December launch is not an option so the phase gates keep the team on track.' },

  { id:'pl_02', topic:'Project Lifecycle', subtopic:'Scoping and Feasibility',
    theory:'Before starting any ML project, assess feasibility. Key questions: Is there enough data? (Rule of thumb: at least 1000 labelled examples per class for classification.) Is the signal in the data sufficient? (Try a simple baseline.) Is the business value worth the effort? What is the minimum viable solution? Define a clear success criterion agreed with stakeholders before building — otherwise the definition of success keeps moving.',
    interview:'Scoping means asking hard questions before starting. Do we have enough data? Is the signal strong enough? We build a simple baseline first — if a model that always predicts the most common class gets 95% accuracy, the data might be highly imbalanced and we need a better metric. We agree on success criteria with stakeholders before building. If we do not do this upfront, the finish line keeps moving and the project never ends.',
    code:'# Feasibility checklist:\n\n# Data feasibility:\n# - Min 1000 labelled samples per class?\n# - Is data labelled? Cost to label more?\n# - How fresh is data? Any leakage risk?\n# - Class imbalance > 10:1 ratio?\n\n# Signal feasibility:\n# Build a simple baseline first:\nfrom sklearn.dummy import DummyClassifier\nbaseline = DummyClassifier(\n    strategy="most_frequent")\nbaseline.fit(X_train, y_train)\nprint(f"Baseline: "\n      f"{baseline.score(X_test, y_test):.2%}")\n# If ML cannot significantly beat this,\n# the problem may not be solvable\n# with the current data',
    realworld:'A startup spent 6 months building an NLP model. At the end, stakeholders said 87% accuracy was not good enough and they needed 95%. A feasibility check upfront would have shown that noisy short-text data could not exceed 89% with any method. They would have solved a different problem or set realistic expectations from day one.' },

  // PROFESSIONAL SKILLS
  { id:'ps_01', topic:'Professional Skills', subtopic:'Handling Interview Questions',
    theory:'Data science interviews have three types: technical (coding, ML concepts, statistics), behavioural (tell me about a project, handling conflict), and case study (solve this business problem). For technical: think out loud, admit when unsure but show reasoning. For behavioural: use STAR format (Situation, Task, Action, Result) and always end with a quantified result. For case study: ask clarifying questions first, define success metric, suggest simple baseline first.',
    interview:'Interview questions come in three types. For technical questions we think out loud and show our reasoning. For behavioural questions we use the STAR format — Situation, Task, Action, Result. Always end with a number — not "accuracy improved" but "accuracy improved from 62% to 91%". For case study questions we ask clarifying questions first, define what success looks like, suggest a simple baseline before anything complex. Numbers and structure separate good answers from great ones.',
    code:'# STAR format for behavioural questions:\n\n# Q: "Tell me about a challenging\n#     ML project you worked on"\n\n# SITUATION:\n# "In my ANPR project, we needed to\n#  recognise vehicle licence plates\n#  from CCTV footage in real time."\n\n# TASK:\n# "My responsibility was to build the\n#  OCR pipeline for plate text extraction."\n\n# ACTION:\n# "I preprocessed images with OpenCV\n#  (grayscale, adaptive threshold,\n#  deskew), used Tesseract with PSM 7\n#  and a digit/letter whitelist."\n\n# RESULT:\n# "OCR accuracy improved from 62% to 91%.\n#  System processes 200 plates per minute."',
    realworld:'Google\'s hiring committee evaluates behavioural responses on three dimensions: complexity of the situation (was it actually hard?), quality of the action (did they show initiative?), and impact of the result (is the outcome quantified?). A response ending with "the model performed better" gets a low score. "Accuracy improved 23 percentage points, reducing customer complaints by 40%" gets a high score.' },

  { id:'ps_02', topic:'Professional Skills', subtopic:'Documentation and Reproducibility',
    theory:'Professional data scientists document their work so anyone can understand and reproduce it. A model without documentation is a liability — when the original developer leaves, the model becomes a black box. Minimum documentation: README with overview and setup, data dictionary, model card (what the model does, training data, performance, known limitations, intended use), experiment logs (what was tried, what worked, what did not).',
    interview:'Documentation means writing down how everything works so someone else — or future you — can understand and reproduce it. A README explains what the project does and how to run it. A model card describes what the model does, what data it was trained on, how well it performs, and what it should not be used for. Experiment logs record what we tried so we do not repeat failed experiments. Good documentation is the difference between a project that dies when the developer leaves and one that lives on.',
    code:'# README.md structure:\n# ## Project Overview\n# What problem does this solve?\n# ## Setup\n# pip install -r requirements.txt\n# ## Usage\n# python train.py --config config.yaml\n# ## Model Performance\n# F1: 0.87, AUC: 0.93, Latency: 45ms\n# ## Known Limitations\n\n# Model card template:\nmodel_card = {\n    "model_name":    "FraudDetector_v2",\n    "task":          "Binary classification",\n    "training_data": "Jan-Dec 2023 transactions",\n    "performance":   {"F1": 0.87, "AUC": 0.93},\n    "limitations":   "Low accuracy on new merchants",\n    "intended_use":  "Flag suspicious transactions",\n    "not_for":       "Sole basis for legal action"\n}',
    realworld:'The EU AI Act legally requires documentation for high-risk AI systems including credit scoring, hiring, and medical diagnosis models. Companies without proper model cards and data documentation face fines up to 3% of global annual revenue. Hugging Face\'s model card standard is becoming the industry norm.' },

  { id:'ps_03', topic:'Professional Skills', subtopic:'Working in a Team',
    theory:'Data science rarely works in isolation. Key collaboration skills: code reviews (review and accept feedback professionally), standups (daily 15-minute sync), sprint planning (prioritise in 2-week iterations), retrospectives (what went well, what to improve). Data scientists work closely with data engineers (data pipelines), software engineers (APIs and services), and product managers (requirements).',
    interview:'Working in a team means communicating clearly, reviewing each other\'s code professionally, and raising blockers early. The daily standup is three sentences — what I did yesterday, what I am doing today, and any blockers. Code reviews should be about the code not the person — suggest improvements politely and explain why. Raise blockers the moment you see them, not at the end of the week when the whole sprint is delayed.',
    code:'# Daily standup format (3 sentences):\n# Yesterday: Trained LSTM model,\n#            RMSE = 4.2 on validation\n# Today:     Hyperparameter tuning,\n#            targeting RMSE < 3.5\n# Blockers:  Need data team to fix\n#            nulls in vendor_id column\n\n# Code review etiquette:\n# DO: "Consider using StandardScaler\n#     to prevent data leakage"\n# DO: "Is this intentional? If so,\n#     add a comment explaining why"\n# DON\'T: "This is wrong"\n# DON\'T: "Why would you do this?"\n# Reviews are about code, not people',
    realworld:'Airbnb\'s data science team runs two-week sprints with Monday planning, daily standups, and Friday retrospectives. Code reviews require two approvals before merging — one for correctness and one for data science methodology (checking for leakage). This process found a data leakage bug in a pricing model before production that would have caused Rs 2Cr in incorrect pricing per day.' },

  { id:'ps_04', topic:'Professional Skills', subtopic:'Continuous Learning',
    theory:'The ML field moves extremely fast. A technique state-of-the-art two years ago may now be obsolete. Professional data scientists stay current through: reading papers (arXiv, Papers With Code), following practitioners, taking online courses (fast.ai, DeepLearning.AI, Hugging Face courses), building side projects, participating in Kaggle competitions. The key is active learning — building projects, not just watching tutorials. One project teaches more than ten tutorial videos.',
    interview:'The ML field changes very fast. New models, techniques, and tools come out every few months. We stay current by reading papers on arXiv, following ML practitioners online, and most importantly building projects. The rule is: for every concept we want to learn, build one project using it. Watching tutorials without building gives a false sense of knowledge. Building a RAG chatbot even if imperfect teaches more than watching 10 hours of RAG tutorials.',
    code:'# Learning resources by topic:\n\n# Papers:\n# arxiv.org/list/cs.LG/recent\n# paperswithcode.com  (code included)\n\n# Courses:\n# fast.ai         -> practical DL\n# deeplearning.ai -> structured ML\n# huggingface.co/learn -> NLP/GenAI\n# kaggle.com/learn -> short courses\n\n# Practice:\n# kaggle.com      -> competitions\n# github.com      -> open source\n\n# Rule - 1 project per concept:\n# Learn RAG -> build a RAG chatbot\n# Learn LSTM -> build a forecaster\n# NOT: watch 10 hours of tutorials\n# YES: build one working project',
    realworld:'Andrej Karpathy (former Tesla AI director) publicly advocates learning by building. His "Neural Networks: Zero to Hero" series shows building everything from scratch. His philosophy: implementing backpropagation from scratch in NumPy in a weekend creates permanent understanding. The best data scientists have GitHub profiles full of small finished projects demonstrating each technique they learned.' },
];
