/* batch6_data.js — Time Series & Forecasting */

window.BATCH_ID    = 'batch6';
window.BATCH_TITLE = 'Batch 6 — Time Series & Forecasting';

window.TOPIC_COLORS = {
  'Time Series':                  '#1A237E',
  'Forecasting Models':           '#4A148C',
  'Temporal Pattern Recognition': '#004D40',
};

window.FLASHCARD_DATA = [

  { id:'ts_01', topic:'Time Series', subtopic:'Definition',
    theory:'A time series is a sequence of data points collected at successive points in time, usually at regular intervals. Unlike tabular data where rows are independent, time series has temporal ordering — the sequence matters. Each observation is dependent on previous ones. Examples: stock prices daily, temperature hourly, monthly sales. Time series analysis focuses on understanding patterns in temporal data and using them to make forecasts.',
    interview:'A time series is data collected over time in order — like stock prices every day or temperature every hour. The key difference from normal data is that the order matters and each value is related to the values before it. We cannot shuffle time series data. The goal is usually to understand patterns in the past and use them to predict the future.',
    code:'import pandas as pd\nimport matplotlib.pyplot as plt\n\ndf = pd.read_csv("sales.csv",\n    parse_dates=["date"],\n    index_col="date")\n\ndf["sales"].plot(\n    figsize=(12,4), title="Monthly Sales")\nplt.show()\n\n# Resample to different frequency\ndf_monthly = df.resample("M").sum()\ndf_weekly  = df.resample("W").mean()',
    realworld:'Amazon tracks daily product sales as time series for millions of products. They analyse patterns to predict how many units to stock in each warehouse for the next 30 days. Even a 1% improvement in forecast accuracy saves tens of millions in inventory costs.' },

  { id:'ts_02', topic:'Time Series', subtopic:'Components',
    theory:'Time series can be decomposed into four components: Trend — long-term increase or decrease. Seasonality — regular repeating patterns at fixed periods (daily, weekly, yearly). Cyclical — irregular waves longer than a year, related to economic cycles. Residual/Noise — random variation left after removing the other three. Understanding these helps choose the right forecasting model.',
    interview:'Time series has four parts. Trend is the overall direction — are sales going up or down over years? Seasonality is repeating patterns — sales always peak in December. Cyclical patterns are longer irregular waves like economic boom and bust. Residual is the random noise left after removing the other three. We decompose the series to understand each part before building a forecast model.',
    code:'from statsmodels.tsa.seasonal import (\n    seasonal_decompose)\nimport matplotlib.pyplot as plt\n\nresult = seasonal_decompose(\n    df["sales"],\n    model="additive",\n    period=12)  # monthly data\n\nresult.plot()\nplt.tight_layout()\nplt.show()\n\n# Components:\ntrend    = result.trend\nseasonal = result.seasonal\nresidual = result.resid',
    realworld:'Swiggy decomposes their order volume and finds: upward trend (more users each month), weekly seasonality (Friday/Saturday dinner orders 3x higher than Monday), and yearly seasonality (Diwali week spikes 5x). Understanding these separately allows them to staff kitchens correctly for each day, week, and festival season.' },

  { id:'ts_03', topic:'Time Series', subtopic:'Stationarity',
    theory:'A stationary time series has statistical properties that do not change over time — constant mean, variance, and autocorrelation. Most statistical forecasting models (ARIMA) require stationarity. A series with a trend is not stationary because the mean changes. To make stationary: differencing (subtract previous value), log transformation (stabilises variance), or seasonal differencing. The ADF test checks for stationarity.',
    interview:'Stationarity means the statistical properties of the series do not change over time — the average stays the same, the variance stays the same. Most forecasting models need stationary data. If a series has an upward trend, the mean is increasing so it is not stationary. We fix this by differencing — subtracting the previous value from the current one. The ADF test tells us if it is stationary — p-value less than 0.05 means stationary.',
    code:'from statsmodels.tsa.stattools import adfuller\nimport numpy as np\n\ndef check_stationarity(series):\n    result = adfuller(series.dropna())\n    print(f"ADF:   {result[0]:.4f}")\n    print(f"p-val: {result[1]:.4f}")\n    if result[1] < 0.05:\n        print("STATIONARY")\n    else:\n        print("NON-STATIONARY")\n\ncheck_stationarity(df["sales"])\n\n# Fix by differencing:\ndf["diff1"]    = df["sales"].diff(1)\ndf["log_diff"] = np.log(df["sales"]).diff(1)\ncheck_stationarity(df["log_diff"])',
    realworld:'A financial analyst builds an ARIMA model for stock prices. The raw price series has an upward trend — ADF test gives p=0.89 (non-stationary). Taking first differences (daily returns) gives p=0.001. The differenced returns are stationary and suitable for ARIMA modelling.' },

  { id:'ts_04', topic:'Time Series', subtopic:'Autocorrelation',
    theory:'Autocorrelation measures how much a time series is correlated with its own past values. ACF (AutoCorrelation Function) shows correlation between the series and its lags. PACF (Partial AutoCorrelation Function) shows correlation at each lag after removing the effect of all shorter lags. Essential for choosing ARIMA parameters: p from PACF, q from ACF. Spikes at seasonal periods reveal seasonality.',
    interview:'Autocorrelation measures how much today\'s value is related to past values. ACF plot shows correlations with all past lags. PACF shows the direct correlation with each lag after removing the effect of all lags in between. We use these plots to choose the right ARIMA parameters. A spike at lag 7 in ACF suggests weekly seasonality.',
    code:'from statsmodels.graphics.tsaplots import (\n    plot_acf, plot_pacf)\nimport matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(2, 1,\n                          figsize=(10, 6))\nplot_acf(df["sales"].dropna(),\n         lags=40, ax=axes[0])\naxes[0].set_title("ACF")\n\nplot_pacf(df["sales"].dropna(),\n          lags=40, ax=axes[1])\naxes[1].set_title("PACF")\n\nplt.tight_layout()\nplt.show()',
    realworld:'A data scientist building a demand forecast for a bakery plots ACF and finds strong spikes at lags 7, 14, 21, 28 — clear weekly seasonality. Bread sales every Monday are strongly correlated with sales from the previous Monday. The PACF shows a single spike at lag 7, suggesting a seasonal AR(1) model.' },

  { id:'ts_05', topic:'Time Series', subtopic:'Train-Test Split for Time Series',
    theory:'Time series train/test splits must respect temporal order — you cannot randomly shuffle. The test set must always be the most recent data. Random splitting would allow the model to see future data during training — massive data leakage. Typical split: last 20% of time as test. For cross-validation, use TimeSeriesSplit which creates forward-chaining folds where validation is always after training.',
    interview:'For time series we always split by time — training data is older data and test data is the most recent. We never randomly shuffle because that would let the model see future data during training. If we train on 2020-2023, we test on 2024. TimeSeriesSplit does cross-validation the right way — each fold always tests on data that comes after the training data.',
    code:'from sklearn.model_selection import (\n    TimeSeriesSplit)\n\nn = len(df)\ntrain_size = int(n * 0.8)\n\n# NEVER do this:\n# X_tr, X_te = train_test_split(X)  # leaks!\n\n# CORRECT: maintain time order\nX_train = X[:train_size]\nX_test  = X[train_size:]\n\n# Time series cross-validation:\ntscv = TimeSeriesSplit(n_splits=5)\nfor train_idx, test_idx in tscv.split(X):\n    X_tr = X[train_idx]\n    X_te = X[test_idx]  # always AFTER train',
    realworld:'A hedge fund building a stock prediction model: a junior analyst uses random train_test_split and gets 87% directional accuracy. The senior quant identifies the leakage. Correcting to temporal split reveals the actual accuracy is 53% — barely better than random. The leakage inflated results by 34 percentage points.' },

  { id:'ts_06', topic:'Time Series', subtopic:'Evaluation Metrics',
    theory:'Time series forecasting uses regression metrics. RMSE: penalises large errors more, good when big errors are costly. MAE: average error, robust to outliers. MAPE (Mean Absolute Percentage Error): error as percentage of actual, easy to communicate to business stakeholders. SMAPE: handles zero values better. For business use, MAPE is most commonly reported ("our forecast is accurate within 8%").',
    interview:'We evaluate forecasting models with metrics that measure how far off predictions are. MAE is the average absolute error in the same unit as the data. RMSE penalises big errors more. MAPE is the error as a percentage — saying the forecast is within 5% of actual sales is much more meaningful to a business person than saying RMSE is 234 units.',
    code:'import numpy as np\nfrom sklearn.metrics import (\n    mean_absolute_error,\n    mean_squared_error)\n\ny_true = np.array([100, 120, 130, 115])\ny_pred = np.array([105, 115, 128, 120])\n\nmae  = mean_absolute_error(y_true, y_pred)\nrmse = np.sqrt(mean_squared_error(\n               y_true, y_pred))\nmape = np.mean(\n    np.abs((y_true-y_pred)/y_true)) * 100\n\nprint(f"MAE:  {mae:.2f}")\nprint(f"RMSE: {rmse:.2f}")\nprint(f"MAPE: {mape:.2f}%")',
    realworld:'Walmart evaluates demand forecasting using MAPE per category. Staples (bread, milk) achieve MAPE of 4% — excellent. Seasonal products (Christmas decorations) achieve 18% — acceptable. Electronics during sale events achieve 35% — needs improvement. Percentage metrics help non-technical managers understand forecast quality directly.' },

  // FORECASTING MODELS
  { id:'fm_01', topic:'Forecasting Models', subtopic:'ARIMA',
    theory:'ARIMA (AutoRegressive Integrated Moving Average) is a classical statistical model. Three components: AR(p) — uses past p values to predict current value. I(d) — number of times differencing is applied to make series stationary. MA(q) — uses past q forecast errors to adjust prediction. Choosing p, d, q: d from ADF test, p from PACF plot, q from ACF plot. auto_arima (pmdarima) selects parameters automatically.',
    interview:'ARIMA is a classical statistical method for forecasting. AR means the model uses past values to predict the next value. I means we difference the data to make it stationary. MA means the model also looks at past prediction errors to correct itself. We choose parameters p, d, q using ACF and PACF plots or use auto_arima to find them automatically.',
    code:'from statsmodels.tsa.arima.model import ARIMA\nfrom pmdarima import auto_arima\n\n# Manual ARIMA(p,d,q)\nmodel  = ARIMA(train, order=(1, 1, 1))\nfitted = model.fit()\nforecast = fitted.forecast(steps=12)\n\n# Auto ARIMA - finds best p,d,q\nauto_model = auto_arima(\n    train,\n    seasonal=True,\n    m=12,\n    stepwise=True,\n    information_criterion="aic"\n)\nforecast = auto_model.predict(n_periods=12)',
    realworld:'A bank uses ARIMA to forecast monthly loan defaults. auto_arima selects ARIMA(2,1,1) — the model uses past 2 months of defaults, one round of differencing to remove trend, and 1 lag of forecast errors. The model produces 3-month-ahead forecasts that help the risk team set aside appropriate loan loss reserves.' },

  { id:'fm_02', topic:'Forecasting Models', subtopic:'SARIMA',
    theory:'SARIMA (Seasonal ARIMA) extends ARIMA to handle seasonal patterns. Adds seasonal components (P, D, Q, m): P=seasonal AR order, D=seasonal differencing, Q=seasonal MA order, m=seasonal period (12 for monthly, 7 for daily with weekly seasonality). Written as ARIMA(p,d,q)(P,D,Q)[m]. For data with clear seasonality, SARIMA is significantly better than plain ARIMA.',
    interview:'SARIMA extends ARIMA by adding seasonal components. If we have monthly sales data that follows the same pattern every year, SARIMA captures both month-to-month patterns and the yearly seasonal pattern. We add seasonal orders P, D, Q with the period m. For monthly data m=12. This makes SARIMA much better than plain ARIMA for data with clear yearly or weekly patterns.',
    code:'from statsmodels.tsa.statespace.sarimax import SARIMAX\nfrom pmdarima import auto_arima\n\n# Manual SARIMA\nmodel = SARIMAX(\n    train,\n    order=(1, 1, 1),\n    seasonal_order=(1, 1, 1, 12)\n)\nfitted   = model.fit(disp=False)\nforecast = fitted.forecast(steps=12)\n\n# Auto SARIMA:\nauto_model = auto_arima(\n    train, seasonal=True, m=12,\n    d=1, D=1, stepwise=True)\nforecast = auto_model.predict(n_periods=12)',
    realworld:'An airline uses SARIMA(1,1,1)(1,1,1)[12] to forecast monthly passengers. The non-seasonal component captures month-to-month trends. The seasonal component (m=12) captures summer peaks and winter troughs that repeat every year. MAPE: 4.2% vs 11.7% for plain ARIMA on the same data.' },

  { id:'fm_03', topic:'Forecasting Models', subtopic:'Prophet',
    theory:'Prophet is an open-source forecasting library by Meta for business time series. Designed to handle common challenges: missing data, multiple seasonalities, holidays, and trend changes. Requires a DataFrame with columns "ds" (datestamp) and "y" (value). Very easy to use and robust — works well without deep time series expertise. Best for business metrics like sales, user counts, revenue.',
    interview:'Prophet is a forecasting library from Meta designed for business use. It is very easy to use — just rename columns to "ds" for date and "y" for value, fit the model, and call predict. It automatically handles trends, weekly patterns, and yearly patterns. We can also add holidays. It is robust to missing data and a great starting point for any business forecasting problem.',
    code:'from prophet import Prophet\nimport pandas as pd\n\ndf_prophet = df.rename(columns={\n    "date": "ds", "sales": "y"})\n\nmodel = Prophet(\n    yearly_seasonality=True,\n    weekly_seasonality=True,\n    seasonality_mode="multiplicative"\n)\nmodel.add_country_holidays(\n    country_name="IN")\nmodel.fit(df_prophet)\n\nfuture   = model.make_future_dataframe(\n    periods=90)\nforecast = model.predict(future)\n\nmodel.plot(forecast)\nmodel.plot_components(forecast)',
    realworld:'Meta uses Prophet internally to forecast daily active users, ad revenue, and infrastructure load. The tool was open-sourced because most business forecasting problems share common patterns — trends, weekly rhythms, annual seasonality — that Prophet handles automatically without manual tuning.' },

  { id:'fm_04', topic:'Forecasting Models', subtopic:'Exponential Smoothing',
    theory:'Exponential Smoothing methods are simple, fast, and effective for many business tasks. Simple (SES): weighted average of past values, recent values get higher weight. Double (Holt): adds trend. Triple (Holt-Winters): adds seasonality. Good baseline models — often beat complex ML models on short series with clear patterns.',
    interview:'Exponential Smoothing gives more weight to recent values and less to older ones. Holt-Winters adds both trend and seasonality handling. These are fast, simple, and work well for many business problems. They are often used as baseline models that more complex models must beat to justify extra complexity.',
    code:'from statsmodels.tsa.holtwinters import (\n    ExponentialSmoothing)\n\n# Holt-Winters (Triple Exp Smoothing)\nmodel = ExponentialSmoothing(\n    train,\n    trend="add",\n    seasonal="add",\n    seasonal_periods=12\n)\nfitted   = model.fit(optimized=True)\nforecast = fitted.forecast(steps=12)\n\n# Simple baseline:\nfrom statsmodels.tsa.holtwinters import (\n    SimpleExpSmoothing)\nses      = SimpleExpSmoothing(train).fit(\n    smoothing_level=0.3)\nforecast = ses.forecast(12)',
    realworld:'A supermarket uses Holt-Winters to forecast weekly fruit and vegetable sales. The model captures the trend (growing health awareness) and weekly seasonality (Friday-Saturday purchases 40% higher). It runs in milliseconds for thousands of products every Sunday night to plan Monday deliveries.' },

  { id:'fm_05', topic:'Forecasting Models', subtopic:'ML Models for Forecasting',
    theory:'ML models can be applied to time series by transforming the problem into supervised learning using lag features. Create features: lag values, rolling means, rolling std, date features (day of week, month, is_holiday). Train any regression model on these features. XGBoost and LightGBM are most popular for tabular time series. LSTM for complex multi-step or multi-variate forecasting. ML often outperforms classical methods on complex multi-variate data.',
    interview:'We can use ML models for time series by converting the problem into regular supervised learning. We create features from past values — yesterday\'s value, last week\'s value, rolling averages. Then we train XGBoost on these features just like any other regression problem. These ML models often outperform ARIMA because they can capture non-linear patterns and use many features at once.',
    code:'import pandas as pd\nfrom xgboost import XGBRegressor\n\ndf["lag_1"]  = df["sales"].shift(1)\ndf["lag_7"]  = df["sales"].shift(7)\ndf["lag_30"] = df["sales"].shift(30)\ndf["roll_7"] = df["sales"].rolling(7).mean()\ndf["month"]  = df.index.month\ndf["dow"]    = df.index.dayofweek\ndf.dropna(inplace=True)\n\ntrain = df[df.index < "2024-01-01"]\ntest  = df[df.index >= "2024-01-01"]\n\nfeatures = [\n    "lag_1","lag_7","lag_30","roll_7","month","dow"]\nmodel = XGBRegressor(\n    n_estimators=300, learning_rate=0.05)\nmodel.fit(train[features], train["sales"])\npreds = model.predict(test[features])',
    realworld:'Uber uses XGBoost with hundreds of lag and rolling features to forecast ride demand per city zone per hour. The ML model handles non-linear interactions — demand responds differently to rain on a weekday vs weekend. ARIMA could not capture these complex interactions across 3000+ city zones simultaneously.' },

  // TEMPORAL PATTERN RECOGNITION
  { id:'tpr_01', topic:'Temporal Pattern Recognition', subtopic:'Definition',
    theory:'Temporal pattern recognition is finding meaningful patterns in time-ordered data. Broader than forecasting — includes detecting anomalies, identifying change points, recognising events, and classifying sequences. Key patterns: seasonality (repeating cycles), trend (long-term direction), structural breaks (sudden change in behaviour), anomalies (unusual spikes or dips), and motifs (recurring short sequences).',
    interview:'Temporal pattern recognition is about finding patterns in time-ordered data. It is not just forecasting — it also includes detecting when something unusual happens (anomaly detection), finding when behaviour changed (change point detection), and classifying types of sequences. The first step is always to plot the data and visually inspect it for trends, seasonality, and unusual behaviour.',
    code:'import pandas as pd\nimport matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(3, 1,\n                          figsize=(12, 9))\ndf["val"].plot(\n    ax=axes[0], title="Raw Time Series")\ndf["val"].rolling(30).mean().plot(\n    ax=axes[1], title="30-day Rolling Mean")\n(df["val"] - df["val"].rolling(30).mean()\n ).plot(ax=axes[2], title="Residuals")\nplt.tight_layout()\nplt.show()',
    realworld:'Credit card companies use temporal pattern recognition to detect fraud. A customer\'s spending follows a temporal pattern — weekday coffee, weekend restaurants, monthly bills. When the pattern suddenly shows large purchases in a foreign country at 3am, the anomaly detector flags it. The detection is based on what is normal for that specific customer over time.' },

  { id:'tpr_02', topic:'Temporal Pattern Recognition', subtopic:'Trend Detection',
    theory:'Trend detection identifies the long-term direction of a time series. Approaches: rolling mean over a long window. Linear regression on time to quantify direction and strength. Mann-Kendall test is a statistical test for monotonic trend. Decomposition extracts the trend component. Detecting when a metric is genuinely trending vs just noisy fluctuation is critical for business decisions.',
    interview:'Trend detection tells us if something is genuinely going up or down over time or just fluctuating randomly. We use a rolling mean to smooth out noise and see the direction. We can fit a linear regression on time to get the slope — a positive slope means upward trend. The Mann-Kendall test tells us if the trend is statistically significant or just random noise.',
    code:'import numpy as np\nfrom scipy import stats\n\ntime_index = np.arange(len(df))\nslope, intercept, r, p, se = stats.linregress(\n    time_index, df["sales"])\nprint(f"Slope: {slope:.4f}")\nprint(f"R2:    {r**2:.4f}")\nprint(f"p-val: {p:.4f}")\n\n# Smooth with rolling mean\ndf["trend"] = df["sales"].rolling(\n    window=30, center=True).mean()\n\n# Mann-Kendall test:\nimport pymannkendall as mk\nresult = mk.original_test(df["sales"])\nprint(result.trend)',
    realworld:'A product analytics team tracks daily active users for a new feature. Linear regression on the 90-day index gives slope=+150 users/day with p=0.002 — statistically significant upward trend. This confirms the feature is genuinely growing and the team projects when it will reach 1 million daily users.' },

  { id:'tpr_03', topic:'Temporal Pattern Recognition', subtopic:'Anomaly Detection',
    theory:'Anomaly detection in time series identifies data points that deviate significantly from the expected pattern. Methods: Z-score (flag values beyond 3 std deviations), IQR method, rolling statistics (flag points far from rolling mean), STL residuals, Isolation Forest, LSTM autoencoders. Context matters — a spike during a sale is not an anomaly; a spike on a random Tuesday might be.',
    interview:'Anomaly detection finds data points that are unusually different from what we expect. The simplest method is rolling mean and rolling standard deviation, then flag anything more than 3 standard deviations away. Isolation Forest is a machine learning approach that works well without assuming any distribution. Anomalies can be real events to investigate or data quality issues to fix.',
    code:'import numpy as np\nimport pandas as pd\n\n# Rolling Z-score\ndef rolling_zscore(series, window=30):\n    rolling_mean = series.rolling(window).mean()\n    rolling_std  = series.rolling(window).std()\n    return (series - rolling_mean) / rolling_std\n\ndf["zscore"]  = rolling_zscore(df["sales"])\ndf["anomaly"] = df["zscore"].abs() > 3\n\n# Isolation Forest\nfrom sklearn.ensemble import IsolationForest\niso = IsolationForest(contamination=0.05)\ndf["anomaly_if"] = iso.fit_predict(\n    df[["sales"]]) == -1',
    realworld:'AWS monitors millions of servers using automated anomaly detection. When one server\'s CPU suddenly spikes to 95% at 3am on a Saturday — far outside its normal pattern — an alert fires automatically. Without temporal anomaly detection, engineers would need to manually watch dashboards 24/7.' },

  { id:'tpr_04', topic:'Temporal Pattern Recognition', subtopic:'Change Point Detection',
    theory:'Change point detection identifies moments when the underlying statistical properties of the series change — a sudden shift in mean, variance, or trend. Examples: a marketing campaign that permanently increased sales, a product defect that shifted error rates upward. Methods: CUSUM, PELT algorithm, Bayesian change point detection. The ruptures library implements several methods.',
    interview:'Change point detection finds moments in time when the behaviour of the data permanently changed. For example if a company ran a TV ad and sales jumped to a new higher level and stayed there, that is a change point. The ruptures library makes this easy. This is useful for understanding what events caused permanent changes in business metrics.',
    code:'import ruptures as rpt\nimport matplotlib.pyplot as plt\n\nsignal_array = df["sales"].values\n\nmodel = rpt.Pelt(model="rbf").fit(signal_array)\n# pen: penalty, higher = fewer changes\nbreakpoints = model.predict(pen=10)\nprint(f"Change points: {breakpoints}")\n\nrpt.display(signal_array, breakpoints)\nplt.title("Change Point Detection")\nplt.show()\n\n# Simple CUSUM:\nimport numpy as np\ncusum = np.cumsum(\n    df["sales"] - df["sales"].mean())',
    realworld:'A mobile app company uses change point detection on their daily crash rate. The algorithm finds a change point on June 15. The team checks git history and finds a release on June 14 that introduced a memory leak. The crash rate shifted from 0.2% to 1.8% and stayed elevated. Change point detection pinpointed exactly when the regression was introduced.' },
];
