/* batch8_data.js — Computer Vision: OpenCV & Tesseract OCR */

window.BATCH_ID    = 'batch8';
window.BATCH_TITLE = 'Batch 8 — Computer Vision';

window.TOPIC_COLORS = {
  'OpenCV':        '#1A237E',
  'Tesseract OCR': '#4A148C',
};

window.FLASHCARD_DATA = [

  { id:'cv_01', topic:'OpenCV', subtopic:'Definition',
    theory:'OpenCV is the most widely used open-source library for real-time computer vision and image processing. Written in C++ with Python bindings. Key difference from other image libraries: OpenCV uses BGR colour order (Blue-Green-Red) not the more common RGB — this is a common source of bugs. Used in everything from simple image filters to production-grade real-time video analysis.',
    interview:'OpenCV is the main Python library for working with images and video. We use it to load images, resize them, change colour formats, detect edges, and do image processing. One important thing: OpenCV loads images in BGR format not RGB, so if we display with matplotlib or pass to a neural network we need to convert the colour order first.',
    code:'import cv2\nimport numpy as np\n\n# Read image (BGR format by default)\nimg = cv2.imread("image.jpg")\nprint(img.shape)  # (height, width, channels)\nprint(img.dtype)  # uint8\n\n# Display image\ncv2.imshow("Image", img)\ncv2.waitKey(0)\ncv2.destroyAllWindows()\n\n# Save image\ncv2.imwrite("output.jpg", img)\n\n# Webcam capture\ncap = cv2.VideoCapture(0)\nret, frame = cap.read()\ncap.release()',
    realworld:'Instagram\'s filter processing uses OpenCV-style operations — brightness, contrast, blur, and colour grading. Every time a user applies a filter, the app performs a series of image processing operations. Netflix uses video frame analysis to generate thumbnails and detect scene changes.' },

  { id:'cv_02', topic:'OpenCV', subtopic:'Colour Spaces',
    theory:'Colour space is the way colours are represented numerically. BGR (default in OpenCV): Blue, Green, Red, 0-255 each. RGB: same but channel order reversed — used by matplotlib, PIL, neural networks. Grayscale: single channel. HSV (Hue, Saturation, Value): separates colour from brightness — much better for colour-based object detection because lighting changes affect Value not Hue.',
    interview:'Colour spaces are different ways to represent colour as numbers. OpenCV uses BGR which is like RGB but with the channel order reversed. We convert to RGB when displaying with matplotlib. HSV separates the actual colour from brightness which makes colour detection easier — we can detect a red object regardless of whether the lighting is bright or dim by looking at just the hue channel.',
    code:'import cv2, numpy as np\n\nimg = cv2.imread("image.jpg")\n\n# BGR to RGB (for matplotlib)\nimg_rgb  = cv2.cvtColor(\n    img, cv2.COLOR_BGR2RGB)\n\n# Grayscale\ngray     = cv2.cvtColor(\n    img, cv2.COLOR_BGR2GRAY)\n\n# HSV (for colour detection)\nhsv      = cv2.cvtColor(\n    img, cv2.COLOR_BGR2HSV)\n\n# Detect red in HSV space\nlower = np.array([0,   120, 70])\nupper = np.array([10,  255, 255])\nmask  = cv2.inRange(hsv, lower, upper)\nresult = cv2.bitwise_and(\n    img, img, mask=mask)',
    realworld:'Traffic light detection uses HSV colour space. In BGR, a red light under different lighting looks very different. In HSV, red always has a similar hue value (around 0-10 or 170-180) regardless of brightness changes from time of day or weather. This makes detection far more robust.' },

  { id:'cv_03', topic:'OpenCV', subtopic:'Image Transformations',
    theory:'Image transformations change the size, orientation, or geometry of an image. Resize: change dimensions — very commonly needed before feeding to neural networks which expect fixed input sizes. Crop: extract a region using array slicing. Flip: mirror horizontally or vertically — common data augmentation. Rotate using getRotationMatrix2D and warpAffine. Perspective warp: correct perspective distortion for document scanning.',
    interview:'Image transformations change the shape or orientation of an image. Resize is the most common — neural networks need fixed input sizes so we resize images to 224x224 before feeding them in. Crop extracts a specific region. Flip mirrors the image and is used for data augmentation — flipping a cat image still shows a cat, so we get double the training data.',
    code:'import cv2, numpy as np\n\nimg    = cv2.imread("image.jpg")\nh, w   = img.shape[:2]\n\n# Resize to fixed dimensions\nresized = cv2.resize(img, (224, 224))\n\n# Crop [y1:y2, x1:x2]\ncrop = img[100:300, 150:400]\n\n# Flip horizontal\nflip_h = cv2.flip(img, 1)\nflip_v = cv2.flip(img, 0)\n\n# Rotate 45 degrees\ncenter  = (w//2, h//2)\nM       = cv2.getRotationMatrix2D(\n    center, angle=45, scale=1.0)\nrotated = cv2.warpAffine(img, M, (w, h))',
    realworld:'A document scanning app uses perspective transformation to correct photos of documents. When you photograph a receipt at an angle, OpenCV detects the four corners, computes a perspective transform, and warps the image so the document appears flat and straight. This is the same technology used in CamScanner and Adobe Scan.' },

  { id:'cv_04', topic:'OpenCV', subtopic:'Image Filtering and Enhancement',
    theory:'Filtering modifies pixel values based on their neighbourhood. Gaussian blur: averages pixels weighted by a bell curve, reduces noise. Median blur: replaces each pixel with the median — very effective at removing salt-and-pepper noise while preserving edges. Bilateral filter: blurs noise while preserving sharp edges. Histogram equalisation / CLAHE: improve contrast. These are all done by convolving the image with a kernel.',
    interview:'Filtering improves image quality before further processing. Gaussian blur reduces noise by averaging pixels with their neighbours. Median blur removes salt and pepper noise by taking the middle value — very effective for noisy images. Bilateral filter blurs noise but keeps edges sharp which is important before edge detection. We almost always apply some blur before edge detection to reduce false edges from noise.',
    code:'import cv2, numpy as np\n\nimg = cv2.imread("image.jpg")\n\n# Gaussian blur\nblurred = cv2.GaussianBlur(\n    img, (5, 5), sigmaX=0)\n\n# Median blur (salt-and-pepper)\nmedian   = cv2.medianBlur(img, 5)\n\n# Bilateral (blur noise, keep edges)\nbilateral = cv2.bilateralFilter(\n    img, d=9, sigmaColor=75, sigmaSpace=75)\n\n# CLAHE (adaptive contrast)\ngray  = cv2.cvtColor(\n    img, cv2.COLOR_BGR2GRAY)\nclahe = cv2.createCLAHE(\n    clipLimit=2.0, tileGridSize=(8,8))\nenhanced = clahe.apply(gray)',
    realworld:'Medical imaging preprocessing uses bilateral filtering before tumour detection. Raw MRI scans have Gaussian noise from the scanner hardware. Bilateral filtering removes noise while preserving the sharp boundaries between tissue types that the detection algorithm needs to identify.' },

  { id:'cv_05', topic:'OpenCV', subtopic:'Edge Detection',
    theory:'Edge detection identifies boundaries between regions of different intensity. Canny edge detector is most widely used: (1) Apply Gaussian blur. (2) Compute gradient magnitude and direction. (3) Non-maximum suppression to thin edges. (4) Double threshold to classify strong, weak, and non-edges. (5) Edge tracking by hysteresis. Two threshold values control sensitivity.',
    interview:'Edge detection finds the boundaries between different regions in an image — where one object ends and another begins. Canny is the most popular. We first blur the image to reduce noise, then Canny finds pixels where intensity changes sharply. Two threshold values control sensitivity. After finding edges we use findContours to get the actual boundary shapes.',
    code:'import cv2, numpy as np\n\nimg  = cv2.imread("image.jpg")\ngray = cv2.cvtColor(\n    img, cv2.COLOR_BGR2GRAY)\n\n# Blur first to reduce noise\nblur  = cv2.GaussianBlur(gray, (5,5), 0)\n\n# Canny edge detection\nedges = cv2.Canny(\n    blur,\n    threshold1=50,\n    threshold2=150\n)\n\n# Find contours\ncontours, _ = cv2.findContours(\n    edges,\n    cv2.RETR_EXTERNAL,\n    cv2.CHAIN_APPROX_SIMPLE\n)\nprint(f"Found {len(contours)} contours")\n\n# Draw contours\ncv2.drawContours(\n    img, contours, -1, (0,255,0), 2)',
    realworld:'A quality control system uses Canny edge detection to find boundaries of circuit board components. Each detected contour is measured and compared against specifications. A component whose contour falls outside the allowed size range is flagged as defective. The system processes 200 boards per minute with higher accuracy than human visual inspection.' },

  { id:'cv_06', topic:'OpenCV', subtopic:'Drawing and Annotations',
    theory:'OpenCV provides functions for drawing shapes and text on images. Used for: visualising bounding boxes from object detection, drawing detected contours, annotating images with labels and scores, creating overlays. Drawing functions modify the image in-place so always work on a copy. Coordinates are (x, y) in OpenCV — x is horizontal (column) and y is vertical (row).',
    interview:'Drawing in OpenCV adds shapes and text onto images. We use this to visualise results — drawing bounding boxes around detected objects, labelling them with their class and confidence score. We always copy the image before drawing so we keep the original clean. Coordinates in OpenCV are always x first then y.',
    code:'import cv2, numpy as np\n\nimg = cv2.imread("image.jpg").copy()\n\n# Rectangle (bounding box)\ncv2.rectangle(\n    img,\n    pt1=(50, 30),\n    pt2=(200, 150),\n    color=(0, 255, 0),  # BGR green\n    thickness=2\n)\n\n# Text label\ncv2.putText(\n    img,\n    text="Person: 0.95",\n    org=(50, 25),\n    fontFace=cv2.FONT_HERSHEY_SIMPLEX,\n    fontScale=0.7,\n    color=(255, 255, 255),\n    thickness=2\n)\n\ncv2.imwrite("annotated.jpg", img)',
    realworld:'A retail store\'s people counting system draws a semi-transparent overlay over the counting line. When a person crosses the line, a green bounding box appears with a confidence score. Entry and exit counts are displayed as white text in the top corner. Security staff can verify the system on a live monitor.' },

  { id:'cv_07', topic:'OpenCV', subtopic:'Video Processing',
    theory:'OpenCV handles video as a sequence of frames. VideoCapture reads from: camera (index 0), video file (path string), or network stream (URL). VideoWriter saves processed frames to a video file. Main pattern: read frame, process it, optionally write or display, repeat. Always release VideoCapture and VideoWriter to free resources.',
    interview:'Video processing in OpenCV is a loop that reads one frame at a time, processes it, and saves or displays it. VideoCapture opens a camera or video file. VideoWriter saves the processed frames back to a video. We always call release() at the end to free the camera. The main loop is: read frame, process it, write it to output, check if we should stop.',
    code:'import cv2\n\ncap    = cv2.VideoCapture("video.mp4")\nfps    = cap.get(cv2.CAP_PROP_FPS)\nwidth  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))\nheight = int(cap.get(\n    cv2.CAP_PROP_FRAME_HEIGHT))\n\nfourcc = cv2.VideoWriter_fourcc(*"mp4v")\nout    = cv2.VideoWriter(\n    "output.mp4", fourcc, fps, (width,height))\n\nwhile True:\n    ret, frame = cap.read()\n    if not ret:\n        break\n    gray = cv2.cvtColor(\n        frame, cv2.COLOR_BGR2GRAY)\n    out.write(frame)\n    cv2.imshow("Video", frame)\n    if cv2.waitKey(1) & 0xFF == ord("q"):\n        break\n\ncap.release()\nout.release()\ncv2.destroyAllWindows()',
    realworld:'A highway traffic monitoring system processes live camera feeds. For each frame it detects vehicles, counts them by lane, estimates speed from frame displacement, and identifies plate numbers. Processed frames with overlaid counts are streamed to a dashboard. The system processes 30 FPS on each of 50 cameras simultaneously.' },

  { id:'cv_08', topic:'OpenCV', subtopic:'Contours and Shape Analysis',
    theory:'Contours are curves joining continuous points along an image boundary with the same colour or intensity. After thresholding, findContours extracts contour points. Useful operations: contourArea measures size, arcLength measures perimeter, boundingRect gets bounding box, approxPolyDP approximates as a polygon. Shape analysis is used for object detection and measurement without neural networks.',
    interview:'Contours are the outlines of objects in an image. After converting to binary, findContours gives us the boundary points of each separate object. We can measure area, perimeter, and bounding box. By counting the corners of an approximated polygon we can identify basic shapes — 3 corners is a triangle, 4 is a rectangle. This works without any neural network.',
    code:'import cv2, numpy as np\n\nimg   = cv2.imread("shapes.jpg")\ngray  = cv2.cvtColor(\n    img, cv2.COLOR_BGR2GRAY)\n_, thresh = cv2.threshold(\n    gray, 127, 255, cv2.THRESH_BINARY)\n\ncontours, _ = cv2.findContours(\n    thresh, cv2.RETR_EXTERNAL,\n    cv2.CHAIN_APPROX_SIMPLE)\n\nfor cnt in contours:\n    area = cv2.contourArea(cnt)\n    if area < 100:\n        continue\n\n    x, y, w, h = cv2.boundingRect(cnt)\n    peri    = cv2.arcLength(cnt, True)\n    approx  = cv2.approxPolyDP(\n        cnt, 0.02*peri, True)\n    corners = len(approx)\n\n    label = (\n        "Triangle" if corners == 3 else\n        "Rectangle" if corners == 4 else "Circle")\n    cv2.putText(img, label, (x,y-10),\n        cv2.FONT_HERSHEY_SIMPLEX, 0.7,\n        (255,0,0), 2)',
    realworld:'A pharma packaging line uses contour analysis to count and verify tablets in blister packs. Each tablet appears as a bright circular contour. The system counts contours, measures each contour area to detect broken tablets, and flags packs where the count is wrong. Runs at 500 packs per minute with 99.9% accuracy.' },

  // TESSERACT OCR
  { id:'ocr_01', topic:'Tesseract OCR', subtopic:'Definition',
    theory:'Tesseract is an open-source OCR (Optical Character Recognition) engine maintained by Google. OCR converts images of text into machine-readable strings. pytesseract is the Python wrapper. It works by preprocessing the image, detecting text regions, segmenting characters, and classifying each character using a neural network. Best on clean, printed text with good contrast. Struggles with handwriting, low resolution, and complex backgrounds.',
    interview:'Tesseract is a free OCR engine that reads text from images. We wrap it with pytesseract in Python. We give it an image and it returns the text it found. image_to_string gives plain text. image_to_data gives detailed information including the position of each word and its confidence score. It works best on clean printed text. Before running OCR we always preprocess the image to improve accuracy.',
    code:'import pytesseract\nimport cv2\n\n# Basic OCR\nimg  = cv2.imread("document.png")\ntext = pytesseract.image_to_string(img)\nprint(text)\n\n# Detailed data (boxes + confidence)\ndata = pytesseract.image_to_data(\n    img,\n    output_type=pytesseract.Output.DICT\n)\n# Keys: level, left, top, width,\n#        height, conf, text\n\n# With config\ntext = pytesseract.image_to_string(\n    img, lang="eng",\n    config="--psm 6"\n)',
    realworld:'Banks use OCR to process thousands of cheques and forms daily. Tesseract reads account numbers, amounts, and signatures from scanned cheques automatically. What used to require a data entry clerk reading each cheque now runs automatically at scanner speed. HDFC and SBI process millions of cheques monthly using automated OCR pipelines.' },

  { id:'ocr_02', topic:'Tesseract OCR', subtopic:'Preprocessing for OCR',
    theory:'Image quality is the most important factor for OCR accuracy. Standard preprocessing pipeline: (1) Grayscale — remove colour complexity. (2) Denoise — Gaussian or median blur. (3) Binarisation — adaptive thresholding handles uneven lighting better than simple threshold. (4) Deskew — correct tilted images. (5) Morphological operations — close small gaps in characters. Good preprocessing can improve accuracy from 60% to 95%.',
    interview:'OCR accuracy depends heavily on image quality. The preprocessing pipeline converts to grayscale, removes noise, and converts to clean black and white. Adaptive thresholding handles uneven lighting — like when one part of a document is brighter than another — much better than a fixed threshold. Good preprocessing can dramatically improve OCR accuracy. Without it we might get 60%, with it 95%.',
    code:'import cv2, numpy as np, pytesseract\n\ndef preprocess_for_ocr(img_path):\n    img  = cv2.imread(img_path)\n\n    # 1. Grayscale\n    gray = cv2.cvtColor(\n        img, cv2.COLOR_BGR2GRAY)\n\n    # 2. Denoise\n    denoised = cv2.fastNlMeansDenoising(\n        gray, h=10)\n\n    # 3. Adaptive threshold\n    # Better for uneven lighting\n    binary = cv2.adaptiveThreshold(\n        denoised, 255,\n        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\n        cv2.THRESH_BINARY, 11, 2\n    )\n    return binary\n\nprocessed = preprocess_for_ocr("scan.jpg")\ntext      = pytesseract.image_to_string(\n    processed)',
    realworld:'A startup digitising old government land records uses preprocessing: detect document angle with Hough lines and deskew, then CLAHE for contrast enhancement, then adaptive thresholding. This improved Tesseract accuracy from 54% on raw scans to 87% on preprocessed images — making the difference between unusable and usable output.' },

  { id:'ocr_03', topic:'Tesseract OCR', subtopic:'Page Segmentation Modes (PSM)',
    theory:'PSM tells Tesseract how to interpret the image layout. Key modes: PSM 3 (default): fully automatic. PSM 6: assume single uniform block of text — good for paragraphs. PSM 7: treat as single text line — good for license plates. PSM 8: single word. PSM 11: sparse text — find text anywhere without imposing layout. Choosing the right PSM for your image type is important.',
    interview:'PSM tells Tesseract how the text is arranged in the image. If we have a full page of paragraphs, PSM 3 (auto) works well. If the image only contains one line like a licence plate, PSM 7 works much better. PSM 11 is useful for images where text is scattered around without a clear layout. Getting PSM right is one of the most impactful things we can tune.',
    code:'import pytesseract, cv2\n\nimg = cv2.imread("document.png")\n\n# Full document:\ntext = pytesseract.image_to_string(\n    img, config="--psm 3")\n\n# Single paragraph:\ntext = pytesseract.image_to_string(\n    img, config="--psm 6")\n\n# Licence plate (single line):\nplate_text = pytesseract.image_to_string(\n    plate_img,\n    config="--psm 7 --oem 3"\n    " -c tessedit_char_whitelist="\n    "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"\n)\n\n# Sparse text:\ntext = pytesseract.image_to_string(\n    img, config="--psm 11")',
    realworld:'An ANPR system uses PSM 7 (single line) with a character whitelist containing only uppercase letters and digits. Without PSM 7, Tesseract tries to find multiple lines and columns in the small plate image and fails. With PSM 7 and the whitelist, accuracy improves from 67% to 91%.' },

  { id:'ocr_04', topic:'Tesseract OCR', subtopic:'Bounding Boxes and Confidence',
    theory:'image_to_data() returns detailed information about each detected text element including position, size, and confidence score. Confidence is 0-100, where higher is better. Filtering by confidence removes false detections. The output includes hierarchy levels: page, block, paragraph, line, word. Useful for building structured extraction, drawing bounding boxes around specific text regions, or extracting text from specific areas.',
    interview:'image_to_data gives us the position and confidence score for every word detected. We filter by confidence above 60 to keep only reliable detections. The position information (left, top, width, height) tells us exactly where each word is on the image. We can use this to draw bounding boxes or to extract text only from a specific area like the total amount on an invoice.',
    code:'import pytesseract, cv2, pandas as pd\n\nimg  = cv2.imread("invoice.jpg")\ndata = pytesseract.image_to_data(\n    img, output_type=pytesseract.Output.DICT\n)\n\ndf       = pd.DataFrame(data)\nhigh_conf = df[df["conf"] > 60]\nprint(high_conf[["text","conf",\n                  "left","top",\n                  "width","height"]])\n\n# Draw bounding boxes\nfor _, row in df.iterrows():\n    if (int(row["conf"]) > 60 and\n            str(row["text"]).strip()):\n        x,y,w,h = (int(row["left"]),\n            int(row["top"]),\n            int(row["width"]),\n            int(row["height"]))\n        cv2.rectangle(\n            img, (x,y), (x+w,y+h),\n            (0,255,0), 1)',
    realworld:'A document processing company extracts data from thousands of invoice images daily. image_to_data with confidence filtering identifies invoice number (high confidence near top), line items (medium confidence in table), and total amount (high confidence at bottom). Confidence below 50 is flagged for human review, cutting processing time by 80%.' },

  { id:'ocr_05', topic:'Tesseract OCR', subtopic:'OCR Pipeline with OpenCV',
    theory:'A complete OCR pipeline combines OpenCV preprocessing with Tesseract text extraction. Pipeline: (1) Load. (2) Upscale if needed (minimum 300 DPI). (3) Grayscale. (4) Denoise. (5) Adaptive threshold. (6) Run Tesseract with appropriate PSM. (7) Post-process text with regex to extract structured fields. Good preprocessing + right PSM + post-processing = production-quality OCR.',
    interview:'A complete OCR pipeline loads the image, preprocesses it with OpenCV to improve quality, runs Tesseract to extract text, then post-processes the raw text to extract structured fields. Upscaling small images before OCR significantly improves accuracy. Post-processing uses regex to find specific patterns like invoice numbers or amounts. The output is a structured dictionary ready for the database.',
    code:'import cv2, pytesseract, numpy as np, re\n\ndef full_ocr_pipeline(image_path):\n    img  = cv2.imread(image_path)\n\n    # Upscale if small\n    h, w = img.shape[:2]\n    if max(h, w) < 1000:\n        scale = 1000 / max(h, w)\n        img   = cv2.resize(\n            img, None, fx=scale, fy=scale,\n            interpolation=cv2.INTER_CUBIC)\n\n    gray     = cv2.cvtColor(\n        img, cv2.COLOR_BGR2GRAY)\n    binary   = cv2.adaptiveThreshold(\n        gray, 255,\n        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,\n        cv2.THRESH_BINARY, 11, 2)\n\n    text = pytesseract.image_to_string(\n        binary, config="--psm 6 --oem 3")\n\n    invoice_no = re.search(\n        r"Invoice[:#\\s]+(\\w+)", text,\n        re.IGNORECASE)\n    total = re.search(\n        r"Total[:\\s]+([\\d,\\.]+)", text,\n        re.IGNORECASE)\n\n    return {"invoice_no":\n            invoice_no.group(1)\n            if invoice_no else None,\n            "total": total.group(1)\n            if total else None}',
    realworld:'A logistics company processes 10,000 delivery receipts daily. OpenCV handles variety of image qualities from driver photos — some blurry, some at angles. Tesseract extracts text. Regex patterns extract tracking number, recipient name, and delivery timestamp. Data goes directly to the tracking database, eliminating manual entry.' },
];
