/* batch7p2_data.js — LLM Application Layer */

window.BATCH_ID    = 'batch7p2';
window.BATCH_TITLE = 'Batch 7 Part 2 — LLM Application Layer';

window.TOPIC_COLORS = {
  'Context-Aware Response': '#1A237E',
  'Hallucination':          '#4A148C',
  'Prompt Engineering':     '#004D40',
  'LangChain':              '#BF360C',
  'LangGraph':              '#880E4F',
  'Orchestration':          '#E65100',
  'Hugging Face Transformers': '#1B5E20',
  'Gemini':                 '#0D47A1',
};

window.FLASHCARD_DATA = [

  { id:'car_01', topic:'Context-Aware Response', subtopic:'Definition',
    theory:'A context-aware response uses specific information from the prompt context rather than relying on general training knowledge. The LLM is instructed to ground its answer in retrieved documents. It also means maintaining conversation history — knowing what was asked in previous turns. Without conversation memory, each question is answered in isolation and follow-up questions lose their context.',
    interview:'Context-aware response means the LLM uses the retrieved documents to answer, not just its general knowledge. Memory is also important — in a conversation, the LLM needs to remember what was said earlier. ConversationBufferMemory stores all previous messages. When the user asks "How long does it take?" after asking about return policy, the memory lets the LLM understand that "it" refers to the return process.',
    code:'from langchain.chains import (\n    ConversationalRetrievalChain)\nfrom langchain.memory import (\n    ConversationBufferMemory)\nfrom langchain_openai import ChatOpenAI\n\nmemory = ConversationBufferMemory(\n    memory_key="chat_history",\n    return_messages=True,\n    output_key="answer"\n)\nchain = ConversationalRetrievalChain\\\n    .from_llm(\n        llm=ChatOpenAI(\n            model="gpt-4o-mini",\n            temperature=0),\n        retriever=vectorstore.as_retriever(\n            search_kwargs={"k": 4}),\n        memory=memory,\n        return_source_documents=True\n    )\n\nr1 = chain({"question": "What is the return policy?"})\nr2 = chain({"question": "How long does it take?"})  # memory carries context',
    realworld:'Intercom\'s AI support bot uses context-aware responses with memory. A customer asks "What is my current plan?" then asks "Can I upgrade it?" The memory carries context that "it" means their plan. Without memory the bot would ask "Upgrade what?" degrading the experience.' },

  { id:'car_02', topic:'Context-Aware Response', subtopic:'Conversation Memory Types',
    theory:'ConversationBufferMemory: stores full conversation verbatim. Simple but grows indefinitely. ConversationBufferWindowMemory: keeps only last K turns. ConversationSummaryMemory: LLM summarises older parts, keeping context without growing indefinitely but costs extra LLM calls. ConversationSummaryBufferMemory: full buffer up to token limit then summarises. Best for long conversations.',
    interview:'Memory stores the conversation history so follow-up questions make sense. Buffer memory stores everything but gets large. Window memory keeps only the last K turns to save tokens. Summary memory uses an LLM to summarise old turns so we keep key points without all the detail. We choose based on how long conversations typically are.',
    code:'from langchain.memory import (\n    ConversationBufferMemory,\n    ConversationBufferWindowMemory,\n    ConversationSummaryMemory,\n    ConversationSummaryBufferMemory)\nfrom langchain_openai import ChatOpenAI\n\n# Keep only last 5 turns\nmem_win = ConversationBufferWindowMemory(k=5)\n\n# Summarise old turns\nmem_sum = ConversationSummaryMemory(\n    llm=ChatOpenAI(),\n    max_token_limit=500\n)\n\n# Best for long conversations:\nmem_hyb = ConversationSummaryBufferMemory(\n    llm=ChatOpenAI(),\n    max_token_limit=1000\n)\n\nprint(mem_win.load_memory_variables({}))',
    realworld:'A medical documentation assistant uses ConversationSummaryBufferMemory for patient consultations. The full conversation is kept for the first 10 exchanges. As it grows, older exchanges are summarised. The doctor can ask follow-up questions 30 minutes in and the bot correctly references context from early in the session.' },

  // HALLUCINATION
  { id:'hal_01', topic:'Hallucination', subtopic:'Definition',
    theory:'Hallucination is when an LLM generates confident-sounding but factually incorrect or made-up information. LLMs are trained to produce fluent plausible text — they fill gaps with statistical patterns rather than actual knowledge. Types: intrinsic hallucination (contradicts the provided context), extrinsic hallucination (adds information not in context). RAG reduces hallucination by grounding responses in retrieved facts but does not eliminate it entirely.',
    interview:'Hallucination is when the LLM confidently says something wrong or made up. LLMs are trained to sound fluent so they generate a plausible-sounding answer even when they do not know the correct one. RAG reduces this by giving the LLM real documents to answer from. We also tell the LLM in the system prompt to only use the provided context and say "I do not know" if the answer is not there.',
    code:'# Measure with RAGAS\nfrom ragas.metrics import faithfulness\n# faithfulness = 1.0: every claim in context\n# faithfulness = 0.5: half unsupported\n\n# Prevention - strong system prompt:\nSYSTEM = """\nAnswer ONLY using the context provided.\nRULES:\n1. Never add information not in context\n2. If not in context: say "I don\'t know"\n3. Cite the source for each claim\n"""\n\n# Low temperature helps:\nfrom langchain_openai import ChatOpenAI\nllm = ChatOpenAI(\n    model="gpt-4o-mini",\n    temperature=0\n)',
    realworld:'A lawyer used an AI legal research tool that cited three real-sounding but completely fabricated court cases in a filing. The judge discovered the hallucinated citations and sanctioned the lawyer. This highlighted the critical risk of hallucination in high-stakes settings and why RAG with verification is essential.' },

  { id:'hal_02', topic:'Hallucination', subtopic:'Mitigation Strategies',
    theory:'Multiple layers to reduce hallucination: (1) System prompt: instruct to only use context, say I don\'t know, cite sources. (2) temperature=0: reduces randomness. (3) RAG: provide relevant context. (4) Faithfulness checking: second LLM call to verify claims are in context. (5) Structured output with citations. (6) Better retrieval: more relevant context means less need to fill gaps.',
    interview:'We fight hallucination on multiple levels. A strong system prompt tells the LLM to only use context. temperature=0 gives consistent answers. RAG provides accurate context. For high-stakes applications we run a second LLM call to check if the answer is supported by the retrieved documents. This adds latency but catches hallucinations before they reach the user.',
    code:'from langchain_openai import ChatOpenAI\n\nSYSTEM = """\nAnswer ONLY from the provided context.\nCite source document for EACH claim.\nIf missing: "Not found in documents."\nDo NOT use general knowledge.\n"""\n\nllm = ChatOpenAI(temperature=0)\n\n# Post-generation verification\ndef verify_answer(answer, context, llm):\n    check = f"""\n    Context: {context}\n    Answer:  {answer}\n    Is every claim supported by context?\n    Return JSON:\n    {{"verified": true/false,\n     "unsupported_claims": [...]}}\n    """\n    return llm.invoke(check).content',
    realworld:'A healthcare company\'s medication chatbot implements three-layer mitigation: RAG with verified medical databases, temperature=0 with strict system prompt, and a post-generation faithfulness check that rejects answers below 0.9. The rejection triggers: "I cannot confidently answer. Please consult a pharmacist." Reducing hallucination near-zero is non-negotiable in medical contexts.' },

  // PROMPT ENGINEERING
  { id:'pe_01', topic:'Prompt Engineering', subtopic:'Definition',
    theory:'Prompt engineering is designing and optimising the text instructions given to an LLM to get better outputs. Quality of the prompt directly determines quality of the response. Good prompts are specific, provide context, give examples, define output format, and handle edge cases. In production RAG systems, the prompt template is one of the highest-leverage components to optimise.',
    interview:'Prompt engineering is writing good instructions for the LLM. The same LLM gives very different quality answers depending on how we write the prompt. A good prompt has a clear system instruction with the LLM\'s role and rules, a place for the retrieved context, the conversation history, and the user question. Improving the prompt is often the fastest way to improve RAG quality.',
    code:'from langchain_core.prompts import ChatPromptTemplate\nfrom langchain_openai import ChatOpenAI\nfrom langchain_core.output_parsers import StrOutputParser\n\nprompt = ChatPromptTemplate.from_messages([\n    ("system",\n     """You are a helpful support assistant.\n     Rules:\n     - Answer ONLY from the context below\n     - Be concise and friendly\n     - If unsure, say so honestly\n     - Format steps as numbered list"""),\n    ("human",\n     """Context: {context}\n\nHistory: {history}\n\nQuestion: {question}\n\nAnswer:""")\n])\n\nchain = prompt | ChatOpenAI(temperature=0) | StrOutputParser()',
    realworld:'Anthropic\'s Constitutional AI uses carefully engineered prompts to make Claude helpful, harmless, and honest. A poorly engineered system prompt for a customer service bot might allow the LLM to discuss competitor products or give unauthorised refunds. Prompt engineering defines the behaviour and boundaries of the entire system.' },

  { id:'pe_02', topic:'Prompt Engineering', subtopic:'Few-shot Prompting',
    theory:'Few-shot prompting provides examples of desired input-output pairs in the prompt to guide the LLM\'s response format and style. Zero-shot: no examples. One-shot: one example. Few-shot: 2-5 examples. Very effective for: consistent formatting, specific tone, structured output like JSON, handling edge cases. Examples should cover diverse cases including the edge cases you care about.',
    interview:'Few-shot prompting means giving the LLM examples of what we want before asking it to do the real task. Like showing a student a few solved problems before asking them to solve a new one. If we want JSON output, we show examples of correct JSON. The LLM follows the pattern from the examples. Much more reliable than just describing what we want in words.',
    code:'prompt = ChatPromptTemplate.from_template(\n"""\nExtract info as JSON.\n\nExample 1:\nTicket: Order #12345 not arrived\nOutput: {"issue": "delayed delivery",\n         "order_id": "12345",\n         "urgency": "high"}\n\nExample 2:\nTicket: I want to change my email\nOutput: {"issue": "account update",\n         "order_id": null,\n         "urgency": "low"}\n\nNow extract from:\nTicket: {ticket}\nOutput:\n""")',
    realworld:'Stripe classifies customer support messages without examples at 73% accuracy. With five few-shot examples per category matching their specific ticket language, accuracy jumped to 91%. The examples effectively tuned the general LLM to their business vocabulary without any model training.' },

  { id:'pe_03', topic:'Prompt Engineering', subtopic:'Chain of Thought',
    theory:'Chain-of-thought (CoT) prompting asks the LLM to reason step by step before giving the final answer. Adding "Think step by step" or providing examples that show reasoning dramatically improves performance on complex reasoning and multi-step problems. Zero-shot CoT: just add "think step by step". Few-shot CoT: provide examples that show reasoning steps. In RAG, CoT helps when the answer requires synthesising information from multiple documents.',
    interview:'Chain of thought means asking the LLM to think step by step before giving the answer. Just adding "think step by step" to the prompt can significantly improve accuracy on complex questions. Instead of jumping to an answer, the LLM reasons through the problem. This helps especially for questions that need multiple pieces of information combined or logical reasoning.',
    code:'prompt_cot = ChatPromptTemplate.from_template(\n"""\nContext: {context}\nQuestion: {question}\n\nLet\'s think through this step by step:\n1. Identify relevant information from context\n2. Reason about the answer\n3. State the conclusion clearly\n\nReasoning:\n""")\n\n# Few-shot CoT with examples:\nprompt_few = ChatPromptTemplate.from_template(\n"""\nQ: Product costs 500, 20% discount. Price?\nA: Step 1: Original = 500\n   Step 2: Discount = 100\n   Step 3: Final = 400\n   Answer: 400\n\nQ: {question}\nA: Let me think step by step.\n""")',
    realworld:'Google DeepMind\'s research showed CoT prompting improved GPT-3\'s accuracy on math word problems from 17% to 58% by simply adding "Let\'s think step by step". For a medical diagnosis chatbot, CoT makes reasoning transparent — showing step-by-step how symptoms lead to a diagnosis — which helps doctors verify the logic.' },

  { id:'pe_04', topic:'Prompt Engineering', subtopic:'Structured Output',
    theory:'Instructing the LLM to output in a specific format — JSON, bullet points, tables — makes responses consistent, parseable, and useful programmatically. LangChain\'s with_structured_output() with a Pydantic model enforces schemas and returns typed Python objects. Always provide an example of the desired format. Add error handling for cases where the LLM fails to follow the format.',
    interview:'Structured output means telling the LLM exactly how to format its response. If we need to use the response in code, we ask for JSON. LangChain\'s with_structured_output() with a Pydantic schema is the best approach — we define the exact fields we want and their types, and LangChain ensures the LLM returns data matching that schema. We get back a proper Python object with typed fields — no regex parsing needed.',
    code:'from langchain_openai import ChatOpenAI\nfrom langchain_core.pydantic_v1 import (\n    BaseModel, Field)\nfrom typing import List\n\nclass TicketAnalysis(BaseModel):\n    summary:    str   = Field(description="2-sentence summary")\n    category:   str   = Field(description="billing/tech/account")\n    urgency:    str   = Field(description="high/medium/low")\n    key_points: List[str] = Field(description="3-5 bullet points")\n    confidence: float = Field(description="0.0-1.0")\n\nllm        = ChatOpenAI(model="gpt-4o-mini")\nstructured = llm.with_structured_output(TicketAnalysis)\n\nresult = structured.invoke("Analyse: " + ticket_text)\nprint(result.category)   # typed field\nprint(result.urgency)\nprint(result.key_points)',
    realworld:'A resume parsing system uses structured output to extract name, email, years_experience, skills (list), education (list). The Pydantic schema ensures every resume returns a validated Python object with consistent types. Without structured output, parsing free-text LLM responses with regex broke on every format variation.' },

  // LANGCHAIN
  { id:'lc_01', topic:'LangChain', subtopic:'Definition',
    theory:'LangChain is an open-source framework for building LLM applications. It provides abstractions for: connecting to different LLM providers through a unified interface, building chains of LLM calls and processing steps, managing prompts as reusable templates, connecting to vector stores and retrievers, managing conversation memory, and building agents with tools. LCEL uses the | operator to compose components.',
    interview:'LangChain is a framework that makes it easier to build LLM applications. Without it we write lots of boilerplate code to connect LLMs, prompts, retrievers, and memory. LangChain provides ready-made components for all of these. LCEL is the modern way — we chain components together using the pipe operator: prompt | llm | parser means format with prompt, send to LLM, parse the output.',
    code:'from langchain_openai import ChatOpenAI\nfrom langchain_core.prompts import ChatPromptTemplate\nfrom langchain_core.output_parsers import StrOutputParser\n\nllm    = ChatOpenAI(model="gpt-4o-mini", temperature=0)\nprompt = ChatPromptTemplate.from_template(\n    "Answer based on context:\\n{context}\\n\\nQ: {question}")\n\nchain = prompt | llm | StrOutputParser()\n\nresponse = chain.invoke({\n    "context":  "LangChain is a framework...",\n    "question": "What is LangChain?"\n})\n\n# Streaming:\nfor chunk in chain.stream({"context": "...",\n                           "question": "?"}):\n    print(chunk, end="", flush=True)',
    realworld:'A document processing startup uses LangChain to build an invoice extraction pipeline: PDF loader → text splitter → embeddings → FAISS → retriever → prompt template → GPT-4o-mini → structured output parser → database. Without LangChain each step requires custom integration code. LangChain reduces 500 lines of boilerplate to 50 clean lines.' },

  { id:'lc_02', topic:'LangChain', subtopic:'LCEL',
    theory:'LCEL (LangChain Expression Language) is the modern way to compose LangChain components using the | pipe operator. Each component implements the Runnable interface with invoke(), stream(), and batch() methods. The pipe means: pass output of left component as input to right. Streaming works automatically end-to-end, batch processing is built-in, async support is native with ainvoke().',
    interview:'LCEL chains components with the pipe symbol. We can write a complete RAG pipeline in a few lines: retriever | format_docs | prompt | LLM | output parser. The same chain automatically supports streaming, batch processing, and async. Swapping one component — like changing from OpenAI to Gemini — requires changing just one object in the chain.',
    code:'from langchain_core.runnables import (\n    RunnableLambda, RunnablePassthrough)\n\nretriever   = vectorstore.as_retriever(k=3)\nformat_docs = RunnableLambda(\n    lambda docs: "\\n\\n".join(\n        d.page_content for d in docs))\n\nrag_chain = (\n    {\n        "context":  retriever | format_docs,\n        "question": RunnablePassthrough()\n    }\n    | ChatPromptTemplate.from_template(\n        "Context: {context}\\nQ: {question}")\n    | ChatOpenAI(temperature=0)\n    | StrOutputParser()\n)\n\nrag_chain.invoke("What is RAG?")\nrag_chain.batch(["Q1", "Q2", "Q3"])\nfor c in rag_chain.stream("What is RAG?"):\n    print(c, end="")',
    realworld:'Perplexity AI\'s pipeline uses LCEL: query_analysis | retriever | reranker | prompt_builder | llm | citation_extractor | formatter. Streaming is enabled end-to-end so users see the answer word by word. Swapping from GPT-4 to Claude for cost optimisation required changing one line.' },

  // LANGGRAPH
  { id:'lg_01', topic:'LangGraph', subtopic:'Definition',
    theory:'LangGraph is built on LangChain for building stateful multi-step AI workflows as graphs. Unlike linear chains, LangGraph allows: loops (retry or iterate), conditional branching (different paths based on state), parallel execution, and human-in-the-loop checkpoints. Each step is a node (Python function). Connections are edges. Shared state flows through all nodes.',
    interview:'LangGraph builds AI workflows as graphs. Nodes are functions, edges are connections between them. Unlike a simple chain that goes A to B to C, a graph can loop back — the agent can try again if the answer is not good enough. It can branch — billing questions go to billing agent, technical questions go to tech agent. State flows through the graph and every node can read and update it.',
    code:'from langgraph.graph import StateGraph, END\nfrom typing import TypedDict, List\n\nclass AgentState(TypedDict):\n    question:   str\n    documents:  List[str]\n    answer:     str\n    iterations: int\n\ndef retrieve(state):\n    docs = retriever.invoke(state["question"])\n    return {"documents":\n            [d.page_content for d in docs]}\n\ndef generate(state):\n    answer = chain.invoke(state)\n    return {"answer":     answer,\n            "iterations": state["iterations"]+1}\n\ndef should_retry(state) -> str:\n    if (len(state["answer"]) < 50 and\n            state["iterations"] < 3):\n        return "retry"\n    return "done"\n\nbuilder = StateGraph(AgentState)\nbuilder.add_node("retrieve", retrieve)\nbuilder.add_node("generate", generate)\nbuilder.set_entry_point("retrieve")\nbuilder.add_edge("retrieve", "generate")\nbuilder.add_conditional_edges(\n    "generate", should_retry,\n    {"retry": "retrieve", "done": END})\ngraph = builder.compile()',
    realworld:'An autonomous coding assistant uses LangGraph: write code (node 1), run tests (node 2), if tests fail loop back to fix code (conditional edge), after 3 failed attempts escalate to human review. This loop-and-fix pattern is impossible with a simple chain.' },

  { id:'lg_02', topic:'LangGraph', subtopic:'Conditional Edges',
    theory:'Conditional edges route to different nodes based on the current state. A condition function inspects the state and returns the name of the next node. This enables: retry logic (loop back if quality is low), routing (send to different specialist agents), early termination (stop if confident enough), escalation (send to human if confidence is low). Conditional edges are what makes LangGraph agents intelligent.',
    interview:'Conditional edges are like if-else statements in the graph. After a node runs, a condition function looks at the state and decides which node to go to next. After generating an answer, we check if confidence is high enough. If yes we go to END. If no we loop back to retrieve more documents. This routing makes the agent adapt to the situation rather than following a fixed path.',
    code:'def route_question(state) -> str:\n    q = state["question"].lower()\n    if any(w in q for w in\n           ["bill","payment","refund"]):\n        return "billing_agent"\n    elif any(w in q for w in\n             ["bug","error","crash"]):\n        return "tech_agent"\n    else:\n        return "general_agent"\n\nbuilder.add_conditional_edges(\n    "classify",\n    route_question,\n    {\n        "billing_agent": "billing",\n        "tech_agent":    "tech",\n        "general_agent": "general"\n    }\n)',
    realworld:'A customer service platform: messages are classified then routed — billing complaints go to refund flow, technical issues go to troubleshooting, complex disputes go to human handoff. Billing disputes needing approval loop through billing_check → needs_approval → manager_review. This multi-path logic handles real service complexity that a simple chain cannot.' },

  // ORCHESTRATION
  { id:'orch_01', topic:'Orchestration', subtopic:'Definition',
    theory:'Orchestration in AI means coordinating multiple agents, tools, and LLM calls to complete complex tasks. A single LLM call cannot browse the web, execute code, query a database, and summarise findings simultaneously. An orchestrator decides which tool to call, in what order, and passes results between steps. Frameworks: LangGraph (stateful graphs), CrewAI (role-based multi-agent teams), AutoGen.',
    interview:'Orchestration means managing multiple AI components working together. One LLM cannot search the web, run code, and answer questions all at once. An orchestrator decides which tool to call for each step. For example an agent might search the web for current information, run code to analyse it, use RAG to add company context, then generate a final answer.',
    code:'from langchain.agents import (\n    create_react_agent, AgentExecutor)\nfrom langchain.tools import Tool\nfrom langchain_community.tools import (\n    DuckDuckGoSearchRun)\n\nsearch = DuckDuckGoSearchRun()\ntools  = [\n    Tool(\n        name="WebSearch",\n        func=search.run,\n        description="Search the internet"\n    ),\n    Tool(\n        name="DocumentSearch",\n        func=retriever.invoke,\n        description="Search internal docs"\n    )\n]\n\nagent    = create_react_agent(\n    llm=ChatOpenAI(), tools=tools,\n    prompt=react_prompt)\nexecutor = AgentExecutor(\n    agent=agent, tools=tools,\n    verbose=True, max_iterations=5)',
    realworld:'Bloomberg\'s AI research assistant orchestrates web search, financial database queries, and document retrieval to answer complex questions like "Has any Indian IT company beaten earnings estimates three quarters in a row in 2024?" Each step builds on the previous result.' },

  // HUGGING FACE
  { id:'hf_01', topic:'Hugging Face Transformers', subtopic:'Definition',
    theory:'Hugging Face is the central hub for open-source AI models, datasets, and tools. The Transformers library provides a unified API to load and use 500,000+ pretrained models. Key components: Hub (model hosting), pipeline() (easiest inference API), AutoModel/AutoTokenizer (auto-load correct classes), Trainer (fine-tuning API). It democratised AI by making state-of-the-art models accessible to anyone.',
    interview:'Hugging Face is like GitHub for AI models. It hosts hundreds of thousands of pretrained models anyone can download and use for free. The pipeline() function is the easiest way to use them — specify the task and model name and it handles everything. It made powerful AI accessible without expensive API calls.',
    code:'from transformers import pipeline\n\n# Sentiment analysis\nsentiment = pipeline(\n    "sentiment-analysis",\n    model="distilbert-base-uncased"\n          "-finetuned-sst-2-english"\n)\nprint(sentiment("I love this!"))\n# [{"label": "POSITIVE", "score": 0.9998}]\n\n# Question answering\nqa = pipeline(\n    "question-answering",\n    model="deepset/roberta-base-squad2"\n)\nprint(qa(\n    question="What is RAG?",\n    context="RAG is Retrieval-Augmented..."\n))',
    realworld:'Zalando uses Hugging Face Transformers for product description generation and multilingual review analysis across 17 European markets. They fine-tuned a multilingual BERT on their fashion vocabulary and run it on their own servers, processing millions of descriptions monthly at a fraction of the API cost.' },

  { id:'hf_02', topic:'Hugging Face Transformers', subtopic:'AutoModel and Tokenizer',
    theory:'AutoTokenizer and AutoModel automatically load the correct classes for any Hugging Face model. Tokenizer converts raw text to token IDs, handles special tokens, truncation, and padding. AutoModel loads the base transformer. Task-specific variants: AutoModelForSequenceClassification, AutoModelForQuestionAnswering, AutoModelForSeq2SeqLM. Always use the same tokenizer the model was trained with.',
    interview:'AutoTokenizer and AutoModel load the right classes for any model automatically. The tokenizer converts text into numbers the model can read — we must use the same tokenizer the model was trained with. AutoModelForSequenceClassification adds a classification head on top of the base model. After the forward pass, logits gives us raw scores and argmax gives the predicted class.',
    code:'from transformers import (\n    AutoTokenizer,\n    AutoModelForSequenceClassification)\nimport torch\n\nmodel_name = "bert-base-uncased"\ntokenizer  = AutoTokenizer\\\n    .from_pretrained(model_name)\nmodel      = AutoModelForSequenceClassification\\\n    .from_pretrained(model_name, num_labels=2)\n\ninputs = tokenizer(\n    "Hello, how are you?",\n    return_tensors="pt",\n    truncation=True,\n    max_length=512,\n    padding=True\n)\n\nwith torch.no_grad():\n    outputs = model(**inputs)\n\npred = torch.argmax(outputs.logits, dim=1)\nprint(f"Predicted class: {pred.item()}")',
    realworld:'Swiggy fine-tunes Hugging Face multilingual BERT to classify customer complaints into delivery, food quality, app, and billing categories. AutoModelForSequenceClassification with num_labels=4 adds the classification head. The model runs in real time to route incoming tickets to the right support team.' },

  // GEMINI
  { id:'gem_01', topic:'Gemini', subtopic:'Definition',
    theory:'Gemini is Google\'s multimodal large language model family. Multimodal means it understands and generates text, images, audio, video, and code in a single model. Tiers: Gemini Ultra (most capable), Gemini Pro (balanced), Gemini Flash (fast and cheap), Gemini Nano (on-device). Gemini 1.5 Pro introduced a 1 million token context window — enough to process entire codebases or long documents.',
    interview:'Gemini is Google\'s LLM that handles text, images, audio, and video in one model. Gemini Flash is fast and cheap for high-volume applications. Gemini Pro is more capable for complex tasks. Gemini 1.5 Pro has a 1 million token context window — we can give it an entire book or codebase at once without chunking.',
    code:'import google.generativeai as genai\nimport os\n\ngenai.configure(\n    api_key=os.environ["GEMINI_API_KEY"])\n\nmodel    = genai.GenerativeModel(\n    "gemini-1.5-flash")\nresponse = model.generate_content(\n    "Explain transformer architecture")\nprint(response.text)\n\nresponse = model.generate_content(\n    "Summarise: " + long_text,\n    generation_config=genai.GenerationConfig(\n        temperature=0.1,\n        max_output_tokens=500\n    )\n)\nprint(response.text)',
    realworld:'Google Workspace uses Gemini across Gmail, Docs, Sheets, and Meet. In Google Meet, Gemini transcribes the meeting (audio input), generates action items (text output), and answers questions about meeting content using the full transcript as context. One multimodal model handles audio, understanding, and generation.' },

  { id:'gem_02', topic:'Gemini', subtopic:'Gemini with LangChain',
    theory:'Gemini integrates with LangChain through ChatGoogleGenerativeAI, making it a drop-in replacement for other LLMs. The same LCEL chains, prompts, retrievers, and memory work with Gemini as with OpenAI. Gemini embeddings are available through GoogleGenerativeAIEmbeddings. Useful for: cost optimisation (Flash is cheaper), long context tasks (1M tokens vs 128k for OpenAI), multimodal RAG.',
    interview:'Gemini works with LangChain through ChatGoogleGenerativeAI. Once we import the right class, everything else — prompts, chains, retrievers, memory — works the same as with OpenAI. We can switch from OpenAI to Gemini by changing one line. Gemini Flash is cheaper for the same quality on many tasks.',
    code:'from langchain_google_genai import (\n    ChatGoogleGenerativeAI,\n    GoogleGenerativeAIEmbeddings)\nfrom langchain_core.prompts import ChatPromptTemplate\nfrom langchain_core.output_parsers import StrOutputParser\nimport os\n\nllm = ChatGoogleGenerativeAI(\n    model="gemini-1.5-flash",\n    temperature=0,\n    google_api_key=os.environ["GEMINI_API_KEY"]\n)\n\nembeddings = GoogleGenerativeAIEmbeddings(\n    model="models/embedding-001"\n)\n\n# Same chain as OpenAI!\nprompt = ChatPromptTemplate.from_template(\n    "Answer: {question}")\nchain  = prompt | llm | StrOutputParser()\nresult = chain.invoke({"question": "What is LangGraph?"})',
    realworld:'A startup switches from OpenAI to Gemini 1.5 Pro for long-document analysis. A 500-page research report previously required complex chunking. With Gemini 1.5 Pro the entire report fits in one context. Answer quality on cross-document questions improved because the model has full context rather than retrieved fragments.' },
];
