/* batch2_data.js — Core ML: Supervised Learning, Model Training, Evaluation, RMSE, MAE, Hyperparameter Tuning, Model Dev, Inference */

window.BATCH_ID    = 'batch2';
window.BATCH_TITLE = 'Batch 2 — Core Machine Learning';

window.TOPIC_COLORS = {
  'Supervised Learning':      '#1A237E',
  'Model Training':           '#4A148C',
  'Model Evaluation':         '#004D40',
  'RMSE':                     '#BF360C',
  'MAE':                      '#E65100',
  'Hyperparameter Tuning':    '#880E4F',
  'Model Development':        '#1B5E20',
  'Inference':                '#0D47A1',
};

window.FLASHCARD_DATA = [

  // SUPERVISED LEARNING
  { id:'sl_01', topic:'Supervised Learning', subtopic:'Definition',
    theory:'Supervised learning is the most common type of machine learning. We train a model on labelled data — each input (X) has a known correct output (y). The model learns a mapping from input to output. Once trained, it can predict the output for new, unseen inputs. Called supervised because the correct answers guide the learning, like a teacher supervising a student.',
    interview:'Supervised learning means the model learns from labelled data — data where we already know the correct answer. We give the model examples like: here is a house with these features, and the price is X. The model learns from many examples and then predicts the price for houses it has never seen before.',
    code:'from sklearn.linear_model import (\n    LinearRegression, LogisticRegression)\nfrom sklearn.ensemble import (\n    RandomForestClassifier)\n\n# General pattern:\nmodel.fit(X_train, y_train)\npreds = model.predict(X_test)',
    realworld:'Gmail\'s spam filter is trained on millions of emails labelled as spam or not spam. The model learns what patterns indicate spam — certain words, sender behaviour, formatting. When a new email arrives, it predicts whether it is spam based on what it learned.' },

  { id:'sl_02', topic:'Supervised Learning', subtopic:'Regression vs Classification',
    theory:'These are the two types of supervised learning tasks. Regression predicts a continuous numerical value — like house price, temperature, or stock price. The output can be any number. Classification predicts a category or class — like spam/not spam, cat/dog/bird, or disease/no disease. The output is one of a fixed set of classes. The choice of algorithm and evaluation metrics differ between the two.',
    interview:'Regression is when the output is a number — like predicting house price or temperature. Classification is when the output is a category — like predicting if an email is spam or not. These are the two main types of supervised learning and they use different algorithms and different ways to measure performance.',
    code:'# Regression - predicts a number\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.ensemble import RandomForestRegressor\n\n# Classification - predicts a class\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.ensemble import RandomForestClassifier',
    realworld:'A real estate platform uses regression to predict house prices (a continuous number). The same platform uses classification to predict whether a listed property will sell within 30 days (yes or no). Both are supervised learning but require different model types and evaluation metrics.' },

  { id:'sl_03', topic:'Supervised Learning', subtopic:'How a Model Learns',
    theory:'During training the model makes predictions on training data, compares them to the true labels, calculates the error using a loss function, and adjusts its internal parameters (weights) to reduce that error. This process repeats for many iterations (epochs). The optimizer decides how to adjust the weights. The goal is to minimise the loss function — find the weights that produce the most accurate predictions.',
    interview:'During training the model makes a prediction, checks how wrong it is using a loss function, and then adjusts its weights to be less wrong next time. It does this thousands of times. Each full pass through the training data is called an epoch. The optimizer is the algorithm that decides how to adjust the weights.',
    code:'# Conceptual training loop\nfor epoch in range(num_epochs):\n    predictions = model(X_train)\n    loss = loss_fn(predictions, y_train)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()',
    realworld:'When training a fraud detection model at a bank, the model sees a transaction and predicts "not fraud". The actual label is "fraud". The loss is high. The model adjusts its weights to better recognise that pattern. After seeing millions of examples, it learns to detect fraud accurately.' },

  { id:'sl_04', topic:'Supervised Learning', subtopic:'Overfitting and Underfitting',
    theory:'Overfitting: the model performs very well on training data but poorly on new data. It has memorised the training examples including noise, instead of learning the general pattern. Signs: high training accuracy, low test accuracy. Fix: more data, regularisation (L1/L2), dropout, simpler model, cross-validation. Underfitting: the model is too simple and cannot even fit the training data. Signs: low accuracy on both train and test. Fix: more complex model, more features, more training.',
    interview:'Overfitting means the model memorised the training data but cannot generalise to new data. It gets 99% accuracy on training but 60% on test. It is like a student who memorises past papers but cannot answer a new question. Underfitting means the model is too simple — it does badly on both training and test data.',
    code:'# Regularisation to reduce overfitting\nfrom sklearn.linear_model import Ridge, Lasso\n\n# Check for overfitting:\nprint("Train:", model.score(X_train, y_train))\nprint("Test: ", model.score(X_test, y_test))\n# Large gap = overfitting',
    realworld:'A startup trains a fraud detection model that gets 99.5% accuracy on training data but only 72% on production data. Investigation shows it memorised specific transaction amounts rather than learning general fraud patterns. They add regularisation and more diverse training data to fix the overfitting.' },

  { id:'sl_05', topic:'Supervised Learning', subtopic:'Bias-Variance Tradeoff',
    theory:'Bias is error from wrong assumptions — a simple model that cannot capture complexity (underfitting). Variance is error from sensitivity to small fluctuations in training data — a complex model that changes a lot with different training data (overfitting). The tradeoff: reducing bias increases variance, reducing variance increases bias. The goal is to find the sweet spot with low bias AND low variance. This is why we tune model complexity carefully.',
    interview:'Bias means the model is too simple and misses important patterns. Variance means the model is too complex and changes too much based on which data it was trained on. We want both to be low. A very simple model has high bias. A very complex model has high variance. We tune the model to find the right balance.',
    code:'# High bias, low variance\nfrom sklearn.linear_model import LinearRegression\n\n# Low bias, high variance\nfrom sklearn.ensemble import RandomForestRegressor\n\n# Tuning complexity:\nRandomForestRegressor(\n    max_depth=5,\n    n_estimators=100)',
    realworld:'A doctor\'s assistant app predicts disease risk. A linear model (high bias) misses non-linear patterns in symptoms. A deep neural network (high variance) gives different diagnoses for the same symptoms depending on training data. A tuned Random Forest finds the balance — complex enough to be accurate, stable enough to be consistent.' },

  { id:'sl_06', topic:'Supervised Learning', subtopic:'Common Algorithms',
    theory:'Linear Regression: predicts continuous values using a straight line. Logistic Regression: classification despite the name, predicts probability of a class. Decision Tree: splits data into branches based on feature conditions. Random Forest: ensemble of many decision trees, reduces overfitting. SVM: finds the best boundary between classes. KNN: classifies based on majority class of K nearest neighbours.',
    interview:'The most common algorithms are: Linear Regression for predicting numbers, Logistic Regression for classification, Decision Tree which splits data based on conditions, Random Forest which combines many decision trees, and SVM which finds the best boundary between classes. Random Forest is often a good first choice because it works well on many problems without much tuning.',
    code:'from sklearn.linear_model import (\n    LinearRegression, LogisticRegression)\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import (\n    RandomForestClassifier,\n    GradientBoostingClassifier)\nfrom sklearn.svm import SVC\nfrom sklearn.neighbors import KNeighborsClassifier',
    realworld:'A loan approval system at a bank uses Logistic Regression as the baseline (interpretable for regulators), then tests Random Forest for better accuracy, and finally XGBoost for maximum performance. They compare all three and choose the one that balances accuracy with explainability requirements.' },

  // MODEL TRAINING
  { id:'mt_01', topic:'Model Training', subtopic:'Definition',
    theory:'Model training is the process where the model learns from data by adjusting its internal parameters (weights) to minimise a loss function. It is the core step of the ML workflow. For sklearn models, training is done with model.fit(). For neural networks, training involves forward pass, loss calculation, backpropagation, and weight update — repeated for many epochs.',
    interview:'Model training is where the model looks at training data, makes predictions, checks how wrong it is using a loss function, and adjusts its parameters to do better. For sklearn models we just call fit(). For neural networks we write a training loop that does this step by step for many passes through the data.',
    code:'# sklearn - one line\nmodel = RandomForestClassifier(n_estimators=100)\nmodel.fit(X_train, y_train)\n\n# Neural network loop\nfor epoch in range(epochs):\n    out  = model(X)\n    loss = criterion(out, y)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()',
    realworld:'Spotify trains a music recommendation model on billions of listening events. The model adjusts its weights to better predict which songs a user will enjoy. Training runs on GPU clusters for days. The trained model is then deployed to serve personalised recommendations to 500 million users.' },

  { id:'mt_02', topic:'Model Training', subtopic:'Loss Function',
    theory:'The loss function measures how wrong the model\'s predictions are. It is a single number — lower is better. The optimizer uses the gradient of the loss to update weights. Different tasks use different loss functions: MSE (Mean Squared Error) for regression, Binary Cross-Entropy for binary classification, Categorical Cross-Entropy for multi-class classification. Choosing the right loss function is critical.',
    interview:'The loss function measures how wrong the model is. The lower the loss the better. For regression we use Mean Squared Error which penalises big errors more. For classification we use Cross-Entropy which measures how confident the model was in the wrong direction. The training loop tries to minimise this number.',
    code:'import torch.nn as nn\n\n# Regression\nloss_fn = nn.MSELoss()\n\n# Binary classification\nloss_fn = nn.BCELoss()\n\n# Multi-class classification\nloss_fn = nn.CrossEntropyLoss()\n\nloss = loss_fn(predictions, targets)',
    realworld:'A self-driving car company trains an object detection model using Focal Loss — a variant of cross-entropy that focuses more on hard examples like small distant objects. Using standard cross-entropy caused the model to ignore difficult edge cases and focus too much on easy ones like clear road.' },

  { id:'mt_03', topic:'Model Training', subtopic:'Optimizer',
    theory:'The optimizer is the algorithm that updates model weights based on the gradient of the loss. SGD (Stochastic Gradient Descent): basic, updates weights using gradient. Adam: most commonly used, adapts learning rate for each parameter, combines momentum and RMSprop. Learning rate is the most important hyperparameter — how big a step to take when updating weights. Too high = unstable. Too low = slow convergence.',
    interview:'The optimizer updates the model weights after each batch to reduce the loss. Adam is the most popular optimizer because it works well for most problems without much tuning. The learning rate controls how big the update steps are. If it is too high the model jumps around and does not converge. If too low it trains very slowly.',
    code:'import torch.optim as optim\n\n# Adam - most commonly used\noptimizer = optim.Adam(\n    model.parameters(), lr=0.001)\n\n# SGD with momentum\noptimizer = optim.SGD(\n    model.parameters(),\n    lr=0.01, momentum=0.9)\n\noptimizer.zero_grad()\nloss.backward()\noptimizer.step()',
    realworld:'GPT models are trained using the Adam optimizer with a warmup schedule — the learning rate starts very small, increases for the first few thousand steps, then decreases. This prevents the model from making large destabilising updates early in training when the weights are random.' },

  { id:'mt_04', topic:'Model Training', subtopic:'Epochs and Batch Size',
    theory:'Epoch: one complete pass through the entire training dataset. Batch size: number of samples processed before the model weights are updated. Mini-batch gradient descent processes data in small batches (32, 64, 128) — faster than one sample at a time, uses less memory than all at once. More epochs = more learning but risk of overfitting. Use early stopping to stop when validation loss starts increasing.',
    interview:'An epoch is one full pass through the training data. Batch size is how many examples the model sees before updating its weights. We use mini-batches because processing all data at once uses too much memory. Typical batch sizes are 32 or 64. We train for many epochs but use early stopping to stop when the model stops improving.',
    code:'from torch.utils.data import DataLoader\nloader = DataLoader(dataset,\n    batch_size=32, shuffle=True)\n\nfor epoch in range(50):\n    for X_batch, y_batch in loader:\n        out  = model(X_batch)\n        loss = criterion(out, y_batch)\n        optimizer.zero_grad()\n        loss.backward()\n        optimizer.step()',
    realworld:'Training BERT on a single GPU with batch size 32 takes days. Google trains with batch size 2048 across hundreds of TPUs, completing the same training in hours. Larger batch sizes allow more parallelism but require careful learning rate scaling to maintain stability.' },

  { id:'mt_05', topic:'Model Training', subtopic:'Backpropagation',
    theory:'Backpropagation is the algorithm that computes how much each weight in the network contributed to the error. It works backwards through the network using the chain rule of calculus. The result is the gradient — a number for each weight telling us which direction and how much to change it to reduce the loss. This is automatic in PyTorch (autograd) and TensorFlow. You do not implement it manually.',
    interview:'Backpropagation is the algorithm that figures out how much each weight is responsible for the error. It goes backwards through the network and calculates the gradient for every weight. In PyTorch you just call loss.backward() and it does all of this automatically. You do not need to do the math yourself.',
    code:'# PyTorch autograd handles backprop\nx = torch.tensor([2.0],\n                 requires_grad=True)\ny = x ** 2 + 3 * x   # forward pass\ny.backward()          # backprop\nprint(x.grad)         # gradient: dy/dx\n\n# In training loop:\nloss.backward()       # auto backprop\noptimizer.step()      # use gradients',
    realworld:'When training a neural network for image recognition, backpropagation calculates that the filters in early layers should detect edges more strongly. The gradients flow backwards from the final wrong prediction all the way to the first layer, telling each layer how to adjust its weights.' },

  { id:'mt_06', topic:'Model Training', subtopic:'Early Stopping',
    theory:'Early stopping is a regularisation technique that stops training when the validation loss stops improving. Without it, the model keeps training and eventually overfits. You monitor validation loss after each epoch. If it does not improve for N epochs (called patience), training stops. The model at the best validation loss is saved. This prevents wasted training time and overfitting.',
    interview:'Early stopping monitors the validation loss after each epoch. If the loss stops improving for several epochs in a row, training stops automatically. This prevents overfitting by stopping before the model starts memorising training data. We set a patience value — like 5 epochs — meaning we stop if there is no improvement for 5 consecutive epochs.',
    code:'from tensorflow.keras.callbacks import (\n    EarlyStopping)\n\nes = EarlyStopping(\n    monitor="val_loss",\n    patience=5,\n    restore_best_weights=True)\n\nmodel.fit(X_tr, y_tr,\n    validation_split=0.1,\n    callbacks=[es],\n    epochs=200)  # will stop early',
    realworld:'A deep learning team trains an image classifier with early stopping, patience=10. Validation loss improves until epoch 47, then plateaus. Training stops at epoch 57. The model from epoch 47 is saved. Without early stopping they would have trained 200 epochs and the model would overfit.' },

  // MODEL EVALUATION
  { id:'me_01', topic:'Model Evaluation', subtopic:'Definition',
    theory:'Model evaluation measures how well a trained model performs on unseen data. We cannot just look at training accuracy — a model can memorise training data and get 100% there but fail completely on new data. Evaluation on a held-out test set gives an honest measure of real-world performance. Different tasks require different metrics.',
    interview:'Model evaluation is checking how well the model performs on data it has never seen before. Training accuracy is not enough because the model might have just memorised the training data. We use separate test data and measure performance with metrics like accuracy, precision, recall, and F1 score depending on the type of problem.',
    code:'from sklearn.metrics import (\n    accuracy_score, precision_score,\n    recall_score, f1_score,\n    confusion_matrix,\n    classification_report,\n    mean_squared_error, r2_score)\n\nprint(classification_report(\n    y_test, y_pred))',
    realworld:'A medical AI company evaluates their cancer detection model not just on accuracy but on recall — they want to catch as many real cancer cases as possible, even if it means some false alarms. Missing a real cancer case (false negative) is far more costly than a false alarm.' },

  { id:'me_02', topic:'Model Evaluation', subtopic:'Confusion Matrix',
    theory:'A confusion matrix shows the breakdown of predictions for a classification problem. For binary classification: True Positive (TP): correctly predicted positive. True Negative (TN): correctly predicted negative. False Positive (FP): predicted positive but was actually negative (Type 1 error). False Negative (FN): predicted negative but was actually positive (Type 2 error). All metrics — precision, recall, F1 — are calculated from these four values.',
    interview:'The confusion matrix breaks down predictions into four categories. True Positive means we predicted yes and it was actually yes. False Positive means we predicted yes but it was actually no — a false alarm. False Negative means we predicted no but it was actually yes — a miss. Which cells matter most depends on the business problem.',
    code:'from sklearn.metrics import (\n    confusion_matrix, ConfusionMatrixDisplay)\nimport matplotlib.pyplot as plt\n\ncm = confusion_matrix(y_test, y_pred)\nprint(cm)\n# [[TN, FP],\n#  [FN, TP]]\n\ndisp = ConfusionMatrixDisplay(cm)\ndisp.plot()\nplt.show()',
    realworld:'A spam filter confusion matrix: 950 TN (correct not-spam), 40 TP (correct spam caught), 5 FP (real emails wrongly marked spam), 5 FN (spam that got through). The 5 FP are concerning — users missing important emails. The team tunes the threshold to reduce FP even if it means more FN.' },

  { id:'me_03', topic:'Model Evaluation', subtopic:'Accuracy',
    theory:'Accuracy is the simplest metric: percentage of correct predictions. (TP + TN) / (TP + TN + FP + FN). Easy to understand but misleading for imbalanced datasets. If 95% of transactions are not fraud and 5% are fraud, a model that always predicts not-fraud gets 95% accuracy but is completely useless. Always check class distribution before relying on accuracy.',
    interview:'Accuracy is the percentage of correct predictions. Easy to understand but can be very misleading. If 99% of emails are not spam, a model that always says not-spam gets 99% accuracy but is useless. So we always check if the dataset is balanced before trusting accuracy, and use other metrics like precision and recall alongside it.',
    code:'from sklearn.metrics import accuracy_score\nacc = accuracy_score(y_test, y_pred)\nprint(f"Accuracy: {acc:.4f}")\n\n# Manual calculation:\ncorrect = (y_test == y_pred).sum()\ntotal   = len(y_test)\nprint(correct / total)',
    realworld:'A disease screening model claims 98% accuracy. But only 2% of the population has the disease. The model predicts "healthy" for everyone and gets 98% accuracy without learning anything. The team switches to F1 score which properly penalises the model for missing all actual disease cases.' },

  { id:'me_04', topic:'Model Evaluation', subtopic:'Precision and Recall',
    theory:'Precision: out of all the times we predicted positive, how many were actually positive? TP / (TP + FP). High precision means few false alarms. Recall (Sensitivity): out of all actual positives, how many did we correctly find? TP / (TP + FN). High recall means few misses. There is always a tradeoff: increasing one usually decreases the other. Which matters more depends on the business problem.',
    interview:'Precision is: out of all the positives we predicted, how many were actually positive? Recall is: out of all actual positives, how many did we find? If we are building a cancer detection model we want high recall — find every real case even if we have some false alarms. For a spam filter we might prefer high precision — do not mark real emails as spam.',
    code:'from sklearn.metrics import (\n    precision_score, recall_score)\n\np = precision_score(y_test, y_pred)\nr = recall_score(y_test, y_pred)\nprint(f"Precision: {p:.4f}")\nprint(f"Recall:    {r:.4f}")\n\n# Change threshold to control tradeoff:\ny_pred = (y_proba > 0.3).astype(int)',
    realworld:'A fraud detection system: high recall means catching more fraud (fewer fraudulent transactions slip through). High precision means fewer genuine transactions blocked. A bank chooses higher recall to protect customers, accepting that some real transactions will be temporarily flagged for manual review.' },

  { id:'me_05', topic:'Model Evaluation', subtopic:'F1 Score',
    theory:'F1 score is the harmonic mean of precision and recall. Formula: 2 * (Precision * Recall) / (Precision + Recall). It gives a single number that balances both metrics. Useful when both false positives and false negatives are costly. It is 0 when either precision or recall is 0, and reaches 1 only when both are high. For multi-class: macro-F1 (average across all classes) or weighted-F1 (weighted by class size).',
    interview:'F1 score combines precision and recall into one number. It is useful when we care about both false alarms and misses equally. F1 of 1 is perfect, F1 of 0 is worst. We prefer F1 over accuracy when the data is imbalanced. For problems with multiple classes we use macro-F1 which averages F1 across all classes.',
    code:'from sklearn.metrics import f1_score\n\n# Binary\nf1 = f1_score(y_test, y_pred)\n\n# Multi-class\nf1_macro    = f1_score(y_test, y_pred,\n                        average="macro")\nf1_weighted = f1_score(y_test, y_pred,\n                        average="weighted")\nprint(f"F1: {f1:.4f}")',
    realworld:'A multi-label text classifier tags support tickets as Bug, Feature Request, or Billing Issue. Classes are imbalanced — 70% Bug, 20% Feature, 10% Billing. Weighted F1 accounts for class frequency. Macro F1 treats each class equally, showing if the minority class (Billing) is being ignored by the model.' },

  { id:'me_06', topic:'Model Evaluation', subtopic:'ROC-AUC',
    theory:'ROC (Receiver Operating Characteristic) curve plots True Positive Rate vs False Positive Rate at different classification thresholds. AUC (Area Under the Curve) summarises the entire ROC curve as a single number from 0 to 1. AUC = 0.5 means random (no better than chance). AUC = 1.0 means perfect. AUC = 0.85 means the model correctly ranks a positive above a negative 85% of the time. Useful for imbalanced datasets and comparing models.',
    interview:'The ROC curve shows how the model performs at different decision thresholds. AUC is the area under this curve — a number between 0 and 1. AUC of 0.5 means the model is no better than random guessing. AUC of 1 means perfect. AUC of 0.85 is generally considered good. It is especially useful for imbalanced datasets.',
    code:'from sklearn.metrics import (\n    roc_auc_score, roc_curve)\nimport matplotlib.pyplot as plt\n\nauc = roc_auc_score(y_test, y_proba)\nprint(f"AUC: {auc:.4f}")\n\nfpr, tpr, _ = roc_curve(y_test, y_proba)\nplt.plot(fpr, tpr)\nplt.xlabel("False Positive Rate")\nplt.ylabel("True Positive Rate")\nplt.show()',
    realworld:'A credit scoring model achieves AUC of 0.89. This means if the model is given one actual defaulter and one non-defaulter, it correctly ranks the defaulter as higher risk 89% of the time. The bank uses this single number to compare three competing models before choosing which one to deploy.' },

  { id:'me_07', topic:'Model Evaluation', subtopic:'Cross-Validation',
    theory:'Cross-validation gives a more reliable estimate of model performance than a single train/test split. K-Fold CV splits data into K equal parts (folds). The model trains on K-1 folds and tests on the remaining 1. This repeats K times with each fold used as test once. Final score is the average across all K runs. Reduces variance in evaluation. Common: K=5 or K=10.',
    interview:'Cross-validation is a more reliable way to test a model than a single train-test split. We split data into 5 parts. The model trains on 4 parts and tests on 1, then repeats this 5 times with a different test part each time. We average the 5 scores. This gives a more honest picture because the model is tested on all the data eventually.',
    code:'from sklearn.model_selection import (\n    cross_val_score, StratifiedKFold)\n\nkf = StratifiedKFold(\n    n_splits=5, shuffle=True,\n    random_state=42)\n\nscores = cross_val_score(\n    model, X, y,\n    cv=kf, scoring="f1")\n\nprint(f"Mean F1: {scores.mean():.4f}")\nprint(f"Std:     {scores.std():.4f}")',
    realworld:'A Kaggle competitor uses 5-fold cross-validation. Their single train-test split gave F1=0.87. Cross-validation gives mean F1=0.84 with std=0.03. The lower but more stable score gives a more realistic picture of what the model will achieve on unseen data.' },

  // RMSE
  { id:'rmse_01', topic:'RMSE', subtopic:'Definition',
    theory:'RMSE (Root Mean Squared Error) measures the average error between predicted and actual values for regression problems. Formula: sqrt(mean((y_actual - y_predicted)^2)). The squaring penalises larger errors much more than smaller ones. The square root brings the result back to the same unit as the target variable, making it easy to interpret. Lower RMSE = better model.',
    interview:'RMSE tells us on average how far off our predictions are from the actual values, in the same unit as the target. So if we are predicting house prices in lakhs and RMSE is 5, our predictions are off by about 5 lakhs on average. RMSE punishes big errors more than small ones because of the squaring.',
    code:'from sklearn.metrics import mean_squared_error\nimport numpy as np\n\nrmse = np.sqrt(\n    mean_squared_error(y_test, y_pred))\nprint(f"RMSE: {rmse:.4f}")\n\n# Newer sklearn:\nrmse = mean_squared_error(\n    y_test, y_pred, squared=False)',
    realworld:'A house price prediction model has RMSE of 8 lakh rupees. This means on average the model\'s predictions are off by 8 lakhs. The business team can understand this directly — if a house is worth 50 lakhs, the model might predict anywhere from 42 to 58 lakhs.' },

  { id:'rmse_02', topic:'RMSE', subtopic:'RMSE vs R-squared',
    theory:'R-squared (R2) measures how much of the variance in the target the model explains, as a percentage from 0 to 1. R2=1 means perfect. R2=0 means the model is no better than predicting the mean every time. R2 is scale-independent which makes it easier to compare across different datasets. RMSE is scale-dependent but directly interpretable in business terms. Use both: RMSE for business communication, R2 for model comparison.',
    interview:'R-squared tells us what percentage of the variation in the target the model explains. R2 of 0.85 means the model explains 85% of why prices vary. RMSE tells us the average error in real units. We use both together. R2 is good for comparing models. RMSE is good for explaining performance to non-technical people.',
    code:'from sklearn.metrics import r2_score\nimport numpy as np\n\nr2   = r2_score(y_test, y_pred)\nrmse = np.sqrt(mean_squared_error(\n                y_test, y_pred))\n\nprint(f"R2:   {r2:.4f}")\nprint(f"RMSE: {rmse:.4f}")\n# R2 > 0.8 generally considered good',
    realworld:'A property valuation model reports R2=0.91 and RMSE=4.2 lakhs. The data science team uses R2 to compare their model against competitors. The business team uses RMSE to explain to agents: "Our model is typically accurate within 4.2 lakhs for properties in this range."' },

  // MAE
  { id:'mae_01', topic:'MAE', subtopic:'Definition',
    theory:'MAE (Mean Absolute Error) measures the average absolute difference between predicted and actual values. Formula: mean(|y_actual - y_predicted|). Unlike RMSE it does not square the errors, so all errors are weighted equally. Result is in the same unit as the target. More robust to outliers than RMSE. Easier to interpret: if MAE is 5, predictions are off by 5 units on average.',
    interview:'MAE is the average of how far off our predictions are, ignoring whether we predicted too high or too low. If MAE is 5, on average we are off by 5 units. Unlike RMSE, MAE treats all errors the same — a big error does not count extra. This makes it more robust when the data has outliers.',
    code:'from sklearn.metrics import mean_absolute_error\n\nmae = mean_absolute_error(y_test, y_pred)\nprint(f"MAE: {mae:.4f}")\n\n# Manual calculation:\nimport numpy as np\nmae = np.mean(\n    np.abs(y_test - y_pred))',
    realworld:'A food delivery app predicts delivery time. MAE of 4 minutes means predictions are off by 4 minutes on average. The product team uses this to communicate SLA: "Our delivery estimate is accurate within 4 minutes." RMSE would be misleading because a few extreme outliers during rain would inflate it.' },

  { id:'mae_02', topic:'MAE', subtopic:'MAE vs RMSE',
    theory:'RMSE penalises large errors more (due to squaring). MAE treats all errors equally. If your data has outliers that should be penalised, use RMSE. If outliers are noise that should not dominate the metric, use MAE. A large gap between MAE and RMSE means large outlier errors exist. If RMSE is much bigger than MAE, your model makes some very large errors on specific examples.',
    interview:'The main difference is how they handle big errors. RMSE squares the errors so big errors count much more. MAE just takes the absolute value so all errors are equal. If we see RMSE much higher than MAE, it means the model makes a few very large errors on certain inputs. This is a useful diagnostic to spot where the model is failing.',
    code:'import numpy as np\nfrom sklearn.metrics import (\n    mean_absolute_error,\n    mean_squared_error)\n\nmae  = mean_absolute_error(y_test, y_pred)\nrmse = np.sqrt(mean_squared_error(\n               y_test, y_pred))\n\nprint(f"MAE:  {mae:.4f}")\nprint(f"RMSE: {rmse:.4f}")\n# If RMSE >> MAE -> large outlier errors',
    realworld:'A retail demand forecasting model shows MAE=20 units but RMSE=85 units. The large gap means the model makes occasional very large errors on specific products — probably seasonal items like umbrellas or Christmas decorations. The team investigates and adds seasonal features.' },

  // HYPERPARAMETER TUNING
  { id:'ht_01', topic:'Hyperparameter Tuning', subtopic:'Definition',
    theory:'Hyperparameters are settings you choose before training begins — they control how the model learns, not what it learns. Examples: learning rate, number of trees in a forest, max depth of a tree, number of layers in a neural network. Parameters are learned during training (weights). Hyperparameters must be set by you. Tuning means finding the values that give the best model performance.',
    interview:'Hyperparameters are settings we choose before training — like how many trees to use in a Random Forest or how deep each tree can be. They are different from model weights which are learned automatically. Tuning means trying different combinations of these settings to find which ones give the best performance on validation data.',
    code:'# Hyperparameters you set:\nRF = RandomForestClassifier(\n    n_estimators=100,\n    max_depth=5,\n    min_samples_leaf=4\n)\n\n# Parameters learned during training\n# (weights, split thresholds) are set\n# automatically by fit()',
    realworld:'A fintech company builds a credit scoring model. Default n_estimators=10 gives F1=0.72. After tuning they find n_estimators=200, max_depth=8, min_samples_leaf=5 gives F1=0.81. This improvement comes purely from better hyperparameter choices, not from more data.' },

  { id:'ht_02', topic:'Hyperparameter Tuning', subtopic:'GridSearchCV',
    theory:'GridSearchCV tries every possible combination of hyperparameter values you specify. You define a grid of values for each hyperparameter. It trains and evaluates a model for every combination using cross-validation. Returns the best combination. Exhaustive but slow — if you have 3 params with 4 values each, it tries 64 combinations times K folds. Good for a small number of hyperparameters.',
    interview:'GridSearchCV tries every combination of hyperparameter values you define. If you give 3 options for n_estimators and 3 for max_depth, it tries all 9 combinations. Each combination is evaluated using cross-validation so the result is reliable. It tells you which combination worked best. Slow but thorough.',
    code:'from sklearn.model_selection import GridSearchCV\nfrom sklearn.ensemble import RandomForestClassifier\n\nparam_grid = {\n    "n_estimators": [50, 100, 200],\n    "max_depth":    [3, 5, None],\n    "max_features": ["sqrt", "log2"]\n}\ngs = GridSearchCV(\n    RandomForestClassifier(),\n    param_grid, cv=5,\n    scoring="f1", n_jobs=-1)\ngs.fit(X_train, y_train)\nprint(gs.best_params_)\nprint(gs.best_score_)',
    realworld:'A Kaggle participant runs GridSearchCV on XGBoost with a grid of learning_rate, max_depth, and n_estimators. It tries 81 combinations with 5-fold CV — 405 model fits overnight. The best params improve their score from 0.847 to 0.873, moving them up 200 places on the leaderboard.' },

  { id:'ht_03', topic:'Hyperparameter Tuning', subtopic:'RandomizedSearchCV',
    theory:'RandomizedSearchCV randomly samples from the hyperparameter distributions instead of trying every combination. You define a range or distribution for each parameter and specify n_iter (how many random combinations to try). Much faster than GridSearch for the same number of parameters. Often finds nearly as good results with 10-20% of the computation. Good first step before a focused GridSearch.',
    interview:'RandomizedSearchCV is like GridSearchCV but instead of trying every combination it randomly picks n_iter combinations. This is much faster. If GridSearch would try 500 combinations, RandomizedSearch might try only 50 and still find a good result. It is the better first step when you have many hyperparameters and a large search space.',
    code:'from sklearn.model_selection import (\n    RandomizedSearchCV)\nfrom scipy.stats import randint\n\nparam_dist = {\n    "n_estimators": randint(50, 300),\n    "max_depth":    randint(3, 15),\n    "max_features": ["sqrt","log2"],\n    "min_samples_leaf": randint(1, 10)\n}\nrs = RandomizedSearchCV(\n    RandomForestClassifier(),\n    param_dist, n_iter=50,\n    cv=5, scoring="f1",\n    random_state=42)\nrs.fit(X_train, y_train)\nprint(rs.best_params_)',
    realworld:'A data science team has 2 hours of compute before a client demo. GridSearchCV would take 8 hours. RandomizedSearchCV with n_iter=30 runs in 45 minutes and improves model F1 from 0.76 to 0.82 — good enough for the demo. They run a more thorough search later.' },

  { id:'ht_04', topic:'Hyperparameter Tuning', subtopic:'Learning Rate',
    theory:'Learning rate is the most important hyperparameter for neural networks and gradient boosting. It controls how big the weight update steps are during training. Too high: updates are too large, training becomes unstable, loss diverges. Too low: training is very slow, gets stuck in local minima. Typical starting value: 0.001 for Adam. Use learning rate schedulers to reduce it over time.',
    interview:'Learning rate controls how big the steps are when updating model weights. If too high, the model overshoots and never converges — like taking steps so large you jump past the target. If too low, training takes forever. We usually start with 0.001 for Adam and use a scheduler to reduce it automatically when training slows down.',
    code:'# Fixed learning rate:\noptimizer = torch.optim.Adam(\n    model.parameters(), lr=0.001)\n\n# Scheduler (reduce on plateau):\nfrom torch.optim.lr_scheduler import (\n    ReduceLROnPlateau)\nscheduler = ReduceLROnPlateau(\n    optimizer, mode="min",\n    factor=0.5, patience=5)\n\n# Call after each epoch:\nscheduler.step(val_loss)',
    realworld:'Training a ResNet with lr=0.1 causes the loss to explode in the first epoch. Reducing to lr=0.001 gives stable training but the model barely improves after epoch 30. Using a cosine annealing scheduler that starts at 0.001 and gradually reduces to 0.00001 achieves the best final accuracy.' },

  { id:'ht_05', topic:'Hyperparameter Tuning', subtopic:'Regularization',
    theory:'Regularization adds a penalty to the loss function to prevent overfitting by discouraging large weights. L1 (Lasso): adds sum of absolute weight values — drives some weights to exactly zero, performs feature selection. L2 (Ridge): adds sum of squared weights — shrinks all weights but rarely to zero. Strength controlled by alpha (sklearn) or lambda. Dropout is regularization for neural networks.',
    interview:'Regularization prevents overfitting by penalising large weights. L2 regularization shrinks all weights towards zero. L1 regularization can set some weights to exactly zero which effectively removes features. The alpha parameter controls the strength of the penalty. In neural networks we use Dropout which randomly switches off neurons during training.',
    code:'# Ridge (L2)\nfrom sklearn.linear_model import Ridge\nridge = Ridge(alpha=1.0)\nridge.fit(X_train, y_train)\n\n# Lasso (L1) - creates sparse weights\nfrom sklearn.linear_model import Lasso\nlasso = Lasso(alpha=0.01)\n\n# Dropout in neural networks:\nnn.Dropout(p=0.5)  # drop 50% randomly',
    realworld:'A linear regression for house prices without regularization assigns a huge weight to a noisy feature like "year the owner\'s car was bought", fitting training data perfectly. Adding Ridge regularization shrinks this irrelevant feature\'s weight towards zero, and the model generalises much better to new houses.' },

  // MODEL DEVELOPMENT
  { id:'md_01', topic:'Model Development', subtopic:'Definition',
    theory:'Model development is the full end-to-end process of building a machine learning model, from understanding the problem to deploying a working solution. It includes: defining the problem and success metrics, data collection and cleaning, EDA, feature engineering, baseline model, iterative improvement, evaluation, and deployment. A good development process is systematic and reproducible.',
    interview:'Model development is the whole process from start to finish. It includes understanding the problem, cleaning data, exploring it, creating features, training a simple baseline model first, then improving it step by step, evaluating it honestly, and finally deploying it. Doing this systematically makes the process reproducible and easier to debug.',
    code:'from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.ensemble import RandomForestClassifier\n\npipe = Pipeline([\n    ("scaler", StandardScaler()),\n    ("model",  RandomForestClassifier())\n])\npipe.fit(X_train, y_train)\nprint(pipe.score(X_test, y_test))',
    realworld:'A fraud detection team follows a structured process: week 1 define success metrics (catch 90% of fraud with less than 1% false positives), weeks 2-3 data prep and EDA, week 4 baseline Logistic Regression, weeks 5-6 iterate with XGBoost and feature engineering, week 7 evaluation and bias checks, week 8 deployment.' },

  { id:'md_02', topic:'Model Development', subtopic:'Baseline Model',
    theory:'Always build a simple baseline model first before trying complex models. A baseline sets the minimum bar — your complex model must beat it to be worth the extra complexity. Good baselines: predict the most common class (majority classifier), predict the mean of the target, a simple Logistic Regression, or a single Decision Tree. If your complex model barely beats baseline, question whether complexity is justified.',
    interview:'We always start with a simple baseline model. This is the minimum performance the real model must beat. For classification, the baseline might just always predict the most common class. If 80% of samples are class A, this baseline gets 80% accuracy without learning anything. Our real model must clearly beat this to be useful.',
    code:'from sklearn.dummy import DummyClassifier\nbaseline = DummyClassifier(\n    strategy="most_frequent")\nbaseline.fit(X_train, y_train)\nprint("Baseline:",\n      baseline.score(X_test, y_test))\n\n# Then compare real model:\nmodel.fit(X_train, y_train)\nprint("Model:", model.score(X_test, y_test))',
    realworld:'A team builds a recommendation system. Baseline: recommend the 10 most popular items to everyone — click-through rate 4.2%. Their personalised ML model achieves 6.8%. The 2.6% improvement justifies the complexity. If the model only achieved 4.5%, the business might not justify the engineering effort.' },

  { id:'md_03', topic:'Model Development', subtopic:'ML Pipeline',
    theory:'An ML Pipeline chains preprocessing steps and a model together into one object. When you call fit() it runs all steps in sequence. When you call predict() it applies preprocessing then model inference. Prevents data leakage because the pipeline handles fit/transform separation correctly. Makes deployment easier — you deploy one object. Essential for production code.',
    interview:'A Pipeline puts all the preprocessing steps and the model together in one object. When we train, it runs scaling, encoding, and model training in the right order. When we predict on new data, it automatically applies the same preprocessing. We only need to save one object and it handles everything correctly without data leakage.',
    code:'from sklearn.pipeline import Pipeline\nfrom sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import (\n    StandardScaler, OneHotEncoder)\n\npre = ColumnTransformer([\n    ("num", StandardScaler(), num_cols),\n    ("cat", OneHotEncoder(), cat_cols)\n])\npipe = Pipeline([\n    ("preprocessor", pre),\n    ("model", RandomForestClassifier())\n])\npipe.fit(X_train, y_train)\nimport joblib\njoblib.dump(pipe, "pipeline.pkl")',
    realworld:'A production ML system at a bank uses a single Pipeline: impute missing values → encode categoricals → scale numerics → train XGBoost. When a new loan application arrives, one call to pipeline.predict() handles all preprocessing and scoring automatically.' },

  { id:'md_04', topic:'Model Development', subtopic:'Experiment Tracking',
    theory:'Experiment tracking records every detail of each model training run: which data was used, what hyperparameters, what metrics were achieved, which code version. Without tracking, you cannot reproduce past results or compare experiments fairly. Tools: MLflow (open source), Weights & Biases, Neptune. Even a simple spreadsheet is better than nothing.',
    interview:'Experiment tracking means recording what we tried, how we set things up, and what results we got. Without this, after running 20 experiments we cannot remember which settings gave the best result. MLflow is the most common tool — it saves parameters, metrics, and the trained model for every run. We can then compare all runs and pick the best one.',
    code:'import mlflow\n\nwith mlflow.start_run():\n    mlflow.log_param("n_estimators", 100)\n    mlflow.log_param("max_depth", 5)\n\n    # Train model...\n\n    mlflow.log_metric("f1",   0.87)\n    mlflow.log_metric("rmse", 4.2)\n\n    mlflow.sklearn.log_model(\n        model, "model")',
    realworld:'A research team runs 150 experiments over 3 weeks. MLflow tracks every run. When a paper reviewer asks them to reproduce experiment #47 with a different random seed, they simply load the logged parameters from MLflow and rerun exactly. Without tracking this would be impossible.' },

  { id:'md_05', topic:'Model Development', subtopic:'Model Versioning',
    theory:'Model versioning means saving different versions of trained models and tracking which version is in production. This allows rollback if a new model performs worse. Tools: MLflow Model Registry, DVC, or simple file naming like model_v1.pkl. Best practice: never overwrite a deployed model — always save as a new version with date trained, data version, and performance metrics.',
    interview:'Model versioning means saving every version of the trained model, not just the latest one. If we deploy a new model and it performs worse in production, we need to quickly roll back to the previous version. We keep all versions saved with clear names or in a model registry. This is basic practice in any production ML system.',
    code:'import joblib\n\n# Save versions\njoblib.dump(model, "model_v1.pkl")\njoblib.dump(model, "model_v2.pkl")\n\n# Load specific version\nmodel = joblib.load("model_v1.pkl")\n\n# MLflow Registry:\nmlflow.register_model(\n    "runs:/run_id/model", "MyModel")',
    realworld:'A recommendation model is updated every week. After deploying model_v14, click-through rate drops 15%. The team immediately rolls back to model_v13 in 5 minutes. Without versioning, they would have to retrain from scratch which could take days and cost significant revenue.' },

  // INFERENCE
  { id:'inf_01', topic:'Inference', subtopic:'Definition',
    theory:'Inference is using a trained model to make predictions on new, unseen data. It is the deployment phase — the model is no longer learning, just predicting. Key difference from training: no gradients, no weight updates, no loss calculation. The model weights are frozen. In production, inference must be fast and reliable. Latency and throughput are the key performance metrics.',
    interview:'Inference means using the trained model to make predictions on new data. The model is not learning anymore — it just takes input and gives output. In production, we save the trained model to a file, load it when the server starts, and then call predict() for every incoming request. Speed is very important — users do not want to wait.',
    code:'import joblib\nmodel = joblib.load("pipeline.pkl")\n\n# Single prediction\nnew_sample = [[5.1, 3.5, 1.4, 0.2]]\npred  = model.predict(new_sample)\nproba = model.predict_proba(new_sample)\n\n# Batch prediction\npreds = model.predict(X_new)\nprint(preds)',
    realworld:'When you search on Google, their ranking model runs inference in under 100ms to score millions of web pages and return the most relevant ones. The model was trained offline on billions of past searches, but inference happens in real time with every single query.' },

  { id:'inf_02', topic:'Inference', subtopic:'Batch vs Real-time',
    theory:'Two main inference modes. Batch inference: process a large set of inputs all at once, offline, not time-sensitive. For example, generate credit scores for all customers every night. Real-time inference: process one input at a time, immediately, in response to a user action. For example, predict if a transaction is fraud the moment it occurs. Real-time requires low latency. Batch handles large volume efficiently.',
    interview:'Batch inference means making predictions for a large group of inputs all at once, usually scheduled at a fixed time. Real-time inference means making a prediction immediately when a user action happens. Fraud detection needs to be real-time because the transaction is happening right now. Generating monthly credit reports can be batch because there is no urgency.',
    code:'# Batch - process all at once\nimport pandas as pd\ndf = pd.read_csv("new_data.csv")\ndf["predictions"] = model.predict(df[features])\ndf.to_csv("predictions.csv")\n\n# Real-time - single record\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    pred = model.predict([data["features"]])\n    return jsonify({"pred": int(pred[0])})',
    realworld:'A bank runs batch inference every night at midnight: load all customer accounts, run the churn prediction model, save scores to the database. Marketing uses these scores next morning. Separately, their fraud model runs real-time inference: every transaction is scored within 50ms before being approved or flagged.' },

  { id:'inf_03', topic:'Inference', subtopic:'Model Serving',
    theory:'Model serving means making a trained model available to receive requests and return predictions, usually via a REST API. The model is loaded into memory when the server starts (not on every request — that would be too slow). Requests come in via HTTP POST, the server preprocesses the input, runs inference, and returns the prediction as JSON. Tools: Flask, FastAPI, TorchServe, TF Serving, BentoML.',
    interview:'Model serving means wrapping the trained model in an API so other systems can call it and get predictions. We load the model once when the server starts. When a request comes in, we take the input, preprocess it, run the model, and send back the prediction as JSON. This is how ML models are used in real applications — other services just send a request and get back a prediction.',
    code:'from flask import Flask, request, jsonify\nimport joblib\n\napp   = Flask(__name__)\nmodel = joblib.load("pipeline.pkl")  # once\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data  = request.get_json()\n    feats = [data["features"]]\n    pred  = model.predict(feats)\n    proba = model.predict_proba(feats)\n    return jsonify({\n        "prediction":  int(pred[0]),\n        "probability": float(proba[0][1])\n    })\n\nif __name__ == "__main__":\n    app.run(port=5000)',
    realworld:'PhonePe\'s fraud detection API receives transaction details via HTTP POST, runs the ML model in under 30ms, and returns fraud probability. If probability > 0.8, the transaction is blocked automatically. The API handles thousands of requests per second, 24/7.' },

  { id:'inf_04', topic:'Inference', subtopic:'Preprocessing at Inference',
    theory:'Whatever preprocessing was applied to training data MUST be applied to incoming data at inference time, using the same fitted parameters — not refit. If training data was scaled with StandardScaler, incoming data must be scaled with the same scaler (same mean and std). Using a Pipeline ensures this happens automatically. Mismatch between training and inference preprocessing is one of the most common production bugs.',
    interview:'Whatever we did to the training data we must do exactly the same to new data when making predictions. If we scaled training data with StandardScaler, we must use that same scaler on new data — not fit a new one. The easiest way to avoid mistakes is to use a sklearn Pipeline which automatically applies all preprocessing steps in the right order.',
    code:'# Pipeline handles this automatically:\npipe = Pipeline([\n    ("scaler", StandardScaler()),\n    ("model",  RandomForestClassifier())\n])\npipe.fit(X_train, y_train)\njoblib.dump(pipe, "pipeline.pkl")\n\n# At inference - no separate preprocessing:\nmodel = joblib.load("pipeline.pkl")\npred  = model.predict(new_data)\n# Same scaler applied automatically',
    realworld:'A team deploys a churn model but forgets to apply the same StandardScaler used in training. New data goes in unscaled. The model performs terribly in production despite great test results. This training-serving skew is caught only after customer complaints. Using a saved Pipeline would have prevented this entirely.' },

  { id:'inf_05', topic:'Inference', subtopic:'Monitoring',
    theory:'After deployment, models degrade over time because the real world changes. Data drift: the distribution of inputs changes (new customer demographics, new products). Concept drift: the relationship between inputs and outputs changes (what caused churn 2 years ago may not cause it today). Monitor: prediction distribution over time, model performance on labelled samples, feature statistics vs training baseline. Retrain when performance drops.',
    interview:'After we deploy a model, we need to keep watching it because the world changes. If we trained a fraud model on data from 2022 and deploy it in 2024, fraud patterns may have changed. We monitor the model\'s prediction distribution and accuracy over time. When performance drops below a threshold, we retrain the model on fresh data.',
    code:'# Simple drift detection\nimport numpy as np\n\ndef check_drift(train_data, new_data,\n                threshold=0.1):\n    train_mean = train_data.mean()\n    new_mean   = new_data.mean()\n    drift = abs(train_mean-new_mean)/train_mean\n    if drift > threshold:\n        print(f"Drift detected: {drift:.2%}")\n\n# Log predictions for monitoring\nimport logging\nlogging.info(f"Pred: {pred}, Features: {features}")',
    realworld:'Zomato\'s delivery time model performs well when trained. 6 months later, new bike delivery partners join with different speed profiles, and the city expands to new areas. The model starts giving poor estimates. Monitoring catches the drift. The team retrains monthly with fresh data to keep the model accurate.' },
];
