/* batch4_data.js — Backend & Deployment: API, REST, Flask, Production Deployment, Latency, Pipeline & Model Optimisation */

window.BATCH_ID    = 'batch4';
window.BATCH_TITLE = 'Batch 4 — Backend & Deployment';

window.TOPIC_COLORS = {
  'API':                    '#1A237E',
  'REST API':               '#4A148C',
  'Flask':                  '#004D40',
  'Production Deployment':  '#BF360C',
  'Latency':                '#880E4F',
  'API Response Latency':   '#E65100',
  'Pipeline Optimisation':  '#1B5E20',
  'Model Optimisation':     '#0D47A1',
};

window.FLASHCARD_DATA = [

  // API
  { id:'api_01', topic:'API', subtopic:'Definition',
    theory:'API stands for Application Programming Interface. It is a contract that defines how two software systems communicate. One system sends a request in a defined format, the other processes it and returns a response. In ML, we wrap a trained model in an API so other applications can send data and receive predictions without knowing anything about how the model works internally.',
    interview:'An API is a way for two software systems to talk to each other. One system sends a request saying here is my data, please give me a prediction. The other processes it and sends back the result. The caller does not need to know how the model works. They just follow the API contract — send data in this format, get result in that format.',
    code:'import requests\nresponse = requests.post(\n    "http://api.example.com/predict",\n    json={"age": 30, "income": 50000}\n)\nprint(response.status_code)  # 200\nprint(response.json())\n# {"prediction": 1, "probability": 0.87}',
    realworld:'When Swiggy shows you a Google Map, Swiggy is calling the Google Maps API. Swiggy sends coordinates, Maps API returns the map. Swiggy does not build its own maps — it just uses the API. Similarly, an ML prediction model can be wrapped in an API so any app can use it without knowing how it works.' },

  { id:'api_02', topic:'API', subtopic:'HTTP Methods',
    theory:'HTTP is the protocol used for web communication. Main methods: GET — retrieve data, no body, should not change server state. POST — send data to create something or trigger a process, most common for ML predictions. PUT — update an existing resource. DELETE — remove a resource. PATCH — partially update. For ML prediction endpoints, POST is almost always used because we send data in the request body.',
    interview:'HTTP methods tell the server what action we want to perform. GET means give me some information. POST means here is some data, do something with it. For ML APIs we almost always use POST because we are sending input features in the request body and asking for a prediction back. GET is used for things like checking if the API is running.',
    code:'import requests\n\n# GET - retrieve, no body\nr = requests.get(\n    "http://api.example.com/models")\n\n# POST - send data, get result\nr = requests.post(\n    "http://api.example.com/predict",\n    json={"features": [1.2, 3.4, 5.6]})\n\nprint(r.status_code)  # 200\nprint(r.json())',
    realworld:'A mobile banking app uses different methods: GET /account/balance to check balance (reading data), POST /transfer to send money (creating a transaction), PUT /account/settings to update preferences, DELETE /account/beneficiary/123 to remove a payee. Each method has a clear semantic meaning.' },

  { id:'api_03', topic:'API', subtopic:'Request and Response',
    theory:'Every API interaction has two parts. Request: method (GET/POST), URL, headers (metadata like Content-Type, Authorization), and body (data, usually JSON). Response: status code (number indicating success or failure), headers, and body (the result, usually JSON). Content-Type header tells the receiver how to interpret the body.',
    interview:'Every API call has a request and a response. The request has the URL, the HTTP method, headers with metadata, and the body with input data as JSON. The response comes back with a status code telling us if it worked and a body with the result. Content-Type in the header tells both sides the data is JSON format.',
    code:'import requests\n\nresponse = requests.post(\n    url="http://api.example.com/predict",\n    headers={\n        "Content-Type": "application/json",\n        "Authorization": "Bearer TOKEN"\n    },\n    json={"age": 30, "income": 50000}\n)\n\nprint(response.status_code)  # 200\nprint(response.headers)\nprint(response.json())',
    realworld:'When a food delivery app checks if a restaurant is open, it sends a GET request with the restaurant ID. The response comes back with status 200 and a JSON body containing open/closed status, estimated delivery time, and current menu availability. The app renders this information to the user.' },

  { id:'api_04', topic:'API', subtopic:'Status Codes',
    theory:'HTTP status codes are 3-digit numbers that tell the client what happened. 2xx = success (200 OK, 201 Created). 4xx = client error — the request was wrong (400 Bad Request, 401 Unauthorised, 403 Forbidden, 404 Not Found). 5xx = server error (500 Internal Server Error, 503 Service Unavailable). Always return the correct status code from your API.',
    interview:'Status codes tell the caller what happened. 200 means everything worked. 400 means the request was wrong — like missing a required field. 401 means not authorised — invalid API key. 404 means the endpoint does not exist. 500 means something went wrong on the server. As a developer you must return the right status code so the caller knows how to handle the response.',
    code:'from flask import Flask, jsonify, request\napp = Flask(__name__)\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    if not data or "features" not in data:\n        return jsonify(\n            {"error": "Missing features"}\n        ), 400  # Bad Request\n    try:\n        pred = model.predict([data["features"]])\n        return jsonify(\n            {"prediction": int(pred[0])}), 200\n    except Exception as e:\n        return jsonify(\n            {"error": str(e)}), 500',
    realworld:'A payment gateway returns codes merchants handle differently: 200 (payment approved — complete the order), 402 (card declined — ask user to retry), 422 (invalid card number — show validation error), 500 (gateway error — show try again later). Each code triggers a different user experience.' },

  { id:'api_05', topic:'API', subtopic:'Authentication',
    theory:'API authentication verifies the caller has permission to use the API. Without it, anyone could call your ML model and abuse it. Common methods: API Key — a secret string sent in the header, simple but less secure. Bearer Token (JWT) — a signed token that encodes user identity and expiry. OAuth2 — standard for third-party authorisation. Never hardcode API keys in code — store in environment variables.',
    interview:'Authentication means checking that the caller is allowed to use the API. The most common method is an API key — a secret string the caller sends in the request header. The server checks if the key is valid. If not, it returns 401 Unauthorised. We must never hardcode the API key in the code — store it in environment variables. Otherwise anyone who reads your code can steal your key.',
    code:'from flask import Flask, request, jsonify\nimport os\n\napp = Flask(__name__)\nAPI_KEY = os.environ.get("API_KEY")  # never hardcode\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    key = request.headers.get("X-API-Key")\n    if key != API_KEY:\n        return jsonify(\n            {"error": "Unauthorised"}), 401\n    # Process prediction...\n    return jsonify({"prediction": 1})',
    realworld:'OpenAI charges per API call and uses API keys for authentication. Each developer gets a unique key. A stolen or leaked API key means someone else can make calls and the owner gets the bill. This is why keys must never be in code or public repos.' },

  // REST API
  { id:'rest_01', topic:'REST API', subtopic:'Definition',
    theory:'REST (Representational State Transfer) is a set of architectural principles for designing APIs. It uses HTTP and follows conventions: resources identified by URLs, HTTP methods define actions, responses are stateless (server does not store session state between requests), responses are usually JSON. Most web APIs today are REST because they are simple, scalable, and language-agnostic.',
    interview:'REST is a set of rules for designing APIs. The main rules are: use URLs to identify resources like /predict or /models, use HTTP methods to say what you want to do, make each request self-contained so the server does not need to remember anything from previous calls. REST APIs are the most common type today because they are simple and work with any programming language.',
    code:'# REST API design principles:\n\n# Resources as nouns in URLs\n# GET    /models       -> list models\n# GET    /models/1     -> get model 1\n# POST   /predictions  -> create prediction\n# DELETE /models/1     -> delete model 1\n\n# Stateless: each request self-contained\n# Send all needed info in every request',
    realworld:'Twitter\'s API is REST. GET /tweets/12345 returns tweet 12345. POST /tweets creates a new tweet. DELETE /tweets/12345 deletes it. Each endpoint is a resource and the HTTP method says what to do with it. This consistent pattern makes the API easy to learn and use from any language.' },

  { id:'rest_02', topic:'REST API', subtopic:'Statelessness',
    theory:'Stateless means the server does not store any information about the client between requests. Each request must contain all the information needed to process it. The server processes it and forgets. Benefits: servers are simpler, can handle more users, easy to scale horizontally (any server can handle any request). For ML APIs this means sending all features with every prediction request.',
    interview:'Stateless means the server does not remember anything about previous requests. Each request must have everything the server needs to respond. This is important for scaling because if we have 5 servers behind a load balancer, any of them can handle any request — they do not need to share memory about previous calls. For our ML API this means sending all input features in every single request.',
    code:'# STATEFUL (bad):\n# Request 1: send features\n# Request 2: "predict using features I sent"\n# Problem: different server handles\n# Request 2 and has no memory!\n\n# STATELESS (correct):\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    features = data["features"]  # all here\n    pred = model.predict([features])\n    return jsonify({"pred": int(pred[0])})',
    realworld:'Google Search is stateless — each search request includes your full query, language, and location. The server does not remember what you searched 5 seconds ago. This allows Google to distribute billions of daily searches across thousands of servers. Any server can handle any search because no session state is needed.' },

  { id:'rest_03', topic:'REST API', subtopic:'Endpoints',
    theory:'An endpoint is a specific URL in the API that handles a specific type of request. Use nouns not verbs for resources because the HTTP method already says the action. Use plural nouns: /predictions not /prediction. Use hierarchical paths for related resources. For ML APIs, common endpoints: POST /predict, GET /health, GET /model/info.',
    interview:'An endpoint is a URL in the API that handles a specific action. /predict handles prediction requests, /health checks if the server is running, /model/info returns information about the model. We use nouns in URLs not verbs because the HTTP method already tells us the action. POST /predict is better than POST /makePrediction.',
    code:'from flask import Flask, jsonify, request\napp = Flask(__name__)\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    pred = model.predict([data["features"]])\n    return jsonify({"prediction": int(pred[0])})\n\n@app.route("/health", methods=["GET"])\ndef health():\n    return jsonify({"status": "ok"})\n\n@app.route("/model/info", methods=["GET"])\ndef model_info():\n    return jsonify({\n        "version":  "v2",\n        "features": FEATURE_NAMES,\n        "trained":  "2024-01-15"\n    })',
    realworld:'A ride-sharing company exposes: POST /rides (request a ride), GET /rides/456 (track ride), PUT /rides/456/cancel (cancel), GET /drivers/nearby (find drivers), POST /payments (process payment). Each endpoint has one clear responsibility.' },

  { id:'rest_04', topic:'REST API', subtopic:'JSON Format',
    theory:'JSON (JavaScript Object Notation) is the standard data format for REST APIs. It is human-readable, language-agnostic, and lightweight. Key-value pairs in curly braces (objects), arrays in square brackets. In Flask, request.get_json() parses incoming JSON, jsonify() converts Python dicts to JSON. Always validate incoming JSON before using it.',
    interview:'JSON is the standard way to send data in REST APIs. It uses key-value pairs like a Python dictionary. We send input features as JSON in the request body and receive the prediction as JSON in the response. In Flask, request.get_json() reads the incoming JSON and jsonify() converts our result back to JSON. We must always validate the incoming data before using it.',
    code:'from flask import request, jsonify\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n\n    if not data:\n        return jsonify(\n            {"error": "No JSON body"}), 400\n    if "features" not in data:\n        return jsonify(\n            {"error": "Missing features"}), 400\n\n    pred  = model.predict([data["features"]])\n    proba = model.predict_proba(\n                [data["features"]])[0][1]\n    return jsonify({\n        "prediction":  int(pred[0]),\n        "probability": round(float(proba), 4)\n    })',
    realworld:'A weather API returns nested JSON: {"location": "Hyderabad", "current": {"temp_c": 32, "humidity": 65}, "forecast": [...]}. Any app in any language can parse this — iOS in Swift, Android in Kotlin, web in JavaScript. They all understand JSON.' },

  // FLASK
  { id:'flask_01', topic:'Flask', subtopic:'Definition',
    theory:'Flask is a lightweight Python web framework for building web applications and APIs. Called a micro-framework because it has minimal built-in features — just routing and request handling. For ML, Flask is commonly used to wrap a trained model in a REST API. For production, Flask itself is not a server — run it behind gunicorn or uvicorn.',
    interview:'Flask is a simple Python library for building APIs. We define routes — like /predict — and write a Python function that handles requests to that route. Flask receives the HTTP request, calls our function, and sends back whatever we return. It is very easy to learn and is the most common way to deploy ML models as APIs in Python.',
    code:'from flask import Flask, request, jsonify\nimport joblib\n\napp   = Flask(__name__)\nmodel = joblib.load("model.pkl")  # load once\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    pred = model.predict([data["features"]])\n    return jsonify({"prediction": int(pred[0])})\n\n@app.route("/health")\ndef health():\n    return jsonify({"status": "ok"})\n\nif __name__ == "__main__":\n    app.run(debug=True, port=5000)',
    realworld:'A data science team at a startup wraps their churn model in a Flask API with a single /predict endpoint. The mobile app team can now call this API without knowing anything about the ML model. The two teams work independently — the ML team owns the API, the app team consumes it.' },

  { id:'flask_02', topic:'Flask', subtopic:'Routing',
    theory:'A route in Flask maps a URL pattern to a Python function. When a request arrives at that URL, Flask calls the function and returns its result as the HTTP response. Define routes with the @app.route() decorator, specifying the URL pattern and allowed HTTP methods. URL variables capture parts of the URL: /model/<version> captures the version.',
    interview:'Routing in Flask means connecting a URL to a Python function. When someone calls /predict, Flask runs the predict function. We use @app.route to define this connection and also specify which HTTP methods are allowed — usually POST for prediction endpoints. URL variables let us pass information directly in the URL like /model/v2.',
    code:'from flask import Flask\napp = Flask(__name__)\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    return jsonify({"result": 1})\n\n@app.route("/model/<version>")\ndef model_info(version):\n    return jsonify({"version": version})\n\n@app.route("/data",\n           methods=["GET", "POST"])\ndef data():\n    if request.method == "GET":\n        return jsonify({"data": []})\n    else:\n        return jsonify({"saved": True})',
    realworld:'A multi-model ML platform uses URL routing to serve different models: /models/sentiment/predict, /models/fraud/predict, /models/churn/predict. Each route maps to a different function that loads a different model. One Flask application serves all three, and the URL tells Flask which function to call.' },

  { id:'flask_03', topic:'Flask', subtopic:'Request Object',
    theory:'The Flask request object gives access to all parts of the incoming HTTP request. request.method tells if it is GET or POST. request.get_json() parses the JSON body. request.args gives URL query parameters. request.headers gives HTTP headers. request.files gives uploaded files. Always validate request data before using it — never trust user input.',
    interview:'The request object gives us access to everything the client sent. request.get_json() reads the JSON body with the input features. request.args reads URL parameters like ?threshold=0.5. request.headers reads the headers where the API key might be. We always validate the data first — if required fields are missing we return a 400 error.',
    code:'from flask import Flask, request, jsonify\napp = Flask(__name__)\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data    = request.get_json()\n    verbose = request.args.get(\n        "verbose", "false")\n    api_key = request.headers.get(\n        "X-API-Key")\n\n    if not data or "features" not in data:\n        return jsonify(\n            {"error": "Invalid input"}), 400\n\n    pred = model.predict([data["features"]])\n    result = {"prediction": int(pred[0])}\n    if verbose == "true":\n        result["features"] = data["features"]\n    return jsonify(result)',
    realworld:'A fraud detection API uses multiple parts of the request: JSON body contains transaction details, URL parameter ?explain=true triggers SHAP explanations in the response, and the Authorization header contains the merchant\'s API key. The request object gives access to all three in one place.' },

  { id:'flask_04', topic:'Flask', subtopic:'Error Handling',
    theory:'Proper error handling makes APIs robust. Without it, an unhandled exception gives a 500 error with a confusing HTML error page instead of a clean JSON response. Flask lets you register error handlers for specific error codes. Use try/except around model inference. Always return JSON error responses with descriptive messages.',
    interview:'Error handling means returning a proper JSON error response when something goes wrong, instead of crashing or returning an HTML page. We wrap prediction code in try/except. If input is missing we return 400 with a message explaining what is missing. If the model crashes we return 500. This makes our API much easier to debug and use.',
    code:'from flask import Flask, jsonify\napp = Flask(__name__)\n\n@app.errorhandler(404)\ndef not_found(e):\n    return jsonify(\n        {"error": "Endpoint not found"}), 404\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    try:\n        data = request.get_json()\n        if not data:\n            return jsonify(\n                {"error": "No JSON body"}), 400\n        pred = model.predict(\n            [data["features"]])\n        return jsonify(\n            {"prediction": int(pred[0])})\n    except KeyError as e:\n        return jsonify(\n            {"error": f"Missing: {e}"}), 400\n    except Exception as e:\n        return jsonify(\n            {"error": "Prediction failed"}), 500',
    realworld:'A fintech company\'s payment API returns structured errors: {"error": "INSUFFICIENT_FUNDS", "message": "Balance 450, requested 600", "code": 4001}. The mobile app handles each code differently — show top-up screen for INSUFFICIENT_FUNDS, show retry for NETWORK_ERROR. Without structured errors, the app cannot give users helpful guidance.' },

  { id:'flask_05', topic:'Flask', subtopic:'Running Flask in Production',
    theory:'Flask\'s built-in development server (app.run()) is not suitable for production. It is single-threaded and lacks security features. In production use gunicorn (WSGI/sync) or uvicorn (ASGI/async). Gunicorn creates multiple worker processes to handle concurrent requests. Typically run behind a reverse proxy like Nginx. Use environment variables for all configuration.',
    interview:'Flask\'s built-in server is only for development — it can only handle one request at a time. In production we use gunicorn which runs multiple worker processes that can handle many requests simultaneously. The rule of thumb is 2 times the number of CPU cores plus 1. We also set a timeout so if a model takes too long to predict it does not block the server.',
    code:'# Development only:\napp.run(debug=True, port=5000)\n\n# Production with gunicorn:\n# gunicorn --workers 4 \\\n#          --bind 0.0.0.0:8000 \\\n#          app:app\n#\n# workers = 2 * CPU_cores + 1\n# For 2 CPUs: 5 workers\n#\n# With timeout for slow models:\n# gunicorn --workers 4 \\\n#          --timeout 120 \\\n#          --bind 0.0.0.0:8000 app:app',
    realworld:'Zomato\'s recommendation API runs Flask behind gunicorn with 8 workers on a 4-core server. During dinner rush, multiple users open the app simultaneously. Gunicorn distributes requests across all 8 workers, each running the model independently. Without gunicorn, the second user would wait until the first user\'s request finished.' },

  // PRODUCTION DEPLOYMENT
  { id:'prod_01', topic:'Production Deployment', subtopic:'Definition',
    theory:'Production deployment means making your ML model available to real users in a reliable, scalable, and maintainable way. Production requirements: stay up 24/7 (availability), handle many users at once (scalability), recover from failures automatically (reliability), easy to update (maintainability), and secure (no data leaks, no unauthorised access).',
    interview:'Production deployment means putting your model in a real system that real users interact with. Unlike a local test, production must run 24/7, handle many users at the same time, recover if something crashes, and be easy to update. There are many more things to think about than just making the model work — security, monitoring, scaling, and rollback.',
    code:'# Production deployment checklist:\n# 1. Containerise with Docker\n# 2. Use gunicorn not app.run()\n# 3. Load model at startup\n# 4. Env vars for all secrets\n# 5. Health check: GET /health\n# 6. Logging: every request and error\n# 7. Monitoring: latency and errors\n# 8. Load balancer for scaling\n# 9. CI/CD pipeline\n# 10. Rollback plan ready',
    realworld:'A bank deploys a credit scoring model to production. It must evaluate 10,000 loan applications per day, stay online 24/7, comply with regulations requiring audit trails, handle peaks during business hours, and allow model updates without downtime. This is very different from a local Flask server on a laptop.' },

  { id:'prod_02', topic:'Production Deployment', subtopic:'Docker',
    theory:'Docker packages your application and all its dependencies into a container — an isolated, self-contained unit that runs identically everywhere. The Dockerfile defines how to build the image. Benefits: eliminates "works on my machine" problems, easy to deploy to any cloud, consistent environments across dev/staging/production. Container images can be versioned like code.',
    interview:'Docker packages your code, the model, and all the libraries into one container that runs the same everywhere. Without Docker, you might build on Python 3.9 but the production server has Python 3.7, causing errors. With Docker you define exactly what goes in the container and it runs identically on your laptop, test server, and production. It solves the "it works on my machine" problem.',
    code:'# Dockerfile for ML API\nFROM python:3.11-slim\n\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\n\nCOPY . .\n\nCMD ["gunicorn",\n     "--workers", "4",\n     "--bind", "0.0.0.0:8000",\n     "app:app"]\n\n# docker build -t ml-api .\n# docker run -p 8000:8000 ml-api',
    realworld:'A healthcare startup deploys their diagnosis model to AWS. The same Docker image that passed QA testing is deployed to production — not a rebuild from source. If production has an issue, the previous Docker image is redeployed in 2 minutes. Without Docker, redeployment would require reconfiguring the server from scratch.' },

  { id:'prod_03', topic:'Production Deployment', subtopic:'Environment Variables',
    theory:'Environment variables are configuration values stored outside your code, in the operating system environment. Used for secrets (API keys, database passwords), environment-specific settings, and feature flags. Never hardcode secrets in code — they end up in version control where anyone can read them. Load with os.environ.get(). Use a .env file locally (never commit it).',
    interview:'Environment variables keep secrets out of your code. If you hardcode a database password in your Python file and push to GitHub, anyone who sees the code can access your database. Instead we store secrets in environment variables and read them with os.environ.get(). On your laptop you set them in a .env file. On production they are set in deployment configuration.',
    code:'import os\nfrom flask import Flask\n\napp = Flask(__name__)\n\n# WRONG - never do this:\n# API_KEY = "sk-abc123def456"\n\n# CORRECT:\nDB_PASSWORD = os.environ.get("DB_PASSWORD")\nAPI_KEY     = os.environ.get("API_KEY")\nMODEL_PATH  = os.environ.get(\n    "MODEL_PATH", "model.pkl")\n\n# Set in terminal:\n# export API_KEY=your_secret_key\n\n# Or use python-dotenv:\n# from dotenv import load_dotenv\n# load_dotenv()',
    realworld:'A developer accidentally commits AWS credentials to a public GitHub repo. Within minutes, bots scanning GitHub find the credentials and start spinning up GPU instances to mine cryptocurrency. The developer gets a $50,000 AWS bill. Using environment variables and adding .env to .gitignore would have completely prevented this.' },

  { id:'prod_04', topic:'Production Deployment', subtopic:'Health Check Endpoint',
    theory:'A health check endpoint is a simple GET endpoint that returns the current status of the service. Load balancers and monitoring systems call it regularly (every 30 seconds) to check if the service is running. If the health check fails, the load balancer stops sending traffic to that instance and alerts the team. A basic check returns 200 OK. A thorough one verifies model is loaded, DB is reachable, and memory is acceptable.',
    interview:'A health check endpoint is a simple URL that returns 200 OK if the service is running correctly. Load balancers check this every 30 seconds. If it returns an error, the load balancer stops sending traffic to that server and alerts the team. Every production service must have one. A basic one just checks the server is running. A better one also checks the model is loaded and can make a test prediction.',
    code:'from flask import Flask, jsonify\nimport joblib, time\n\napp        = Flask(__name__)\nmodel      = joblib.load("model.pkl")\nstart_time = time.time()\n\n@app.route("/health", methods=["GET"])\ndef health():\n    uptime = time.time() - start_time\n    return jsonify({\n        "status":  "ok",\n        "uptime":  f"{uptime:.0f}s",\n        "model":   "loaded",\n        "version": "v2"\n    }), 200\n\n@app.route("/ready", methods=["GET"])\ndef ready():\n    try:\n        model.predict([[0,0,0,0]])\n        return jsonify({"ready": True}), 200\n    except Exception:\n        return jsonify({"ready": False}), 503',
    realworld:'Kubernetes runs health checks on all pods every 30 seconds. If a pod returns 503 or times out three times in a row, Kubernetes automatically removes it from the load balancer and starts a replacement pod. Users never see a failed pod because traffic is rerouted before they notice.' },

  { id:'prod_05', topic:'Production Deployment', subtopic:'Logging',
    theory:'Logging records a structured record of everything that happens: requests received, predictions made, errors occurred, performance metrics. Essential for debugging production issues, auditing model decisions, and monitoring for problems. Use Python\'s logging module instead of print() — it adds timestamps, log levels, and can write to files or external systems. Never log sensitive data like passwords or personal information.',
    interview:'Logging means recording what is happening in the application so we can debug problems later. When something goes wrong in production at 2am, logs tell us exactly what happened. We use Python\'s logging module not print() because logging adds timestamps and severity levels. We log every request, every prediction, and every error. We never log sensitive data like passwords or credit card numbers.',
    code:'import logging\nfrom flask import Flask, request\n\nlogging.basicConfig(\n    level=logging.INFO,\n    format="%(asctime)s %(levelname)s %(message)s"\n)\nlogger = logging.getLogger(__name__)\n\napp = Flask(__name__)\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    logger.info(f"Prediction request received")\n    try:\n        pred = model.predict([data["features"]])\n        logger.info(f"Prediction: {int(pred[0])}")\n        return jsonify({"prediction": int(pred[0])})\n    except Exception as e:\n        logger.error(f"Prediction failed: {e}")\n        return jsonify({"error": str(e)}), 500',
    realworld:'A fraud detection system logs every prediction with: timestamp, transaction ID, features used, prediction score, and final decision. When a customer disputes a blocked transaction, the team pulls up the logs, sees the exact features and score, and can explain why the model flagged it. Without logs, explaining decisions to regulators is impossible.' },

  // LATENCY
  { id:'lat_01', topic:'Latency', subtopic:'Definition',
    theory:'Latency is the time from when a request is sent to when the response is received. In ML systems it has multiple components: network latency, preprocessing latency, inference latency, and serialisation latency. For user-facing applications, high latency directly hurts user experience. Users abandon pages that take more than 2-3 seconds to load.',
    interview:'Latency is how long it takes from sending a request to getting a response. For a prediction API it includes the time for data to travel over the network, the time to preprocess the features, and the time for the model to make a prediction. Low latency is critical for user-facing applications. A fraud detection system needs to respond in under 100ms because the user is waiting for their payment to go through.',
    code:'import time\nfrom flask import Flask, request, jsonify\n\napp = Flask(__name__)\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    t_start = time.perf_counter()\n    data    = request.get_json()\n    feats   = data["features"]\n\n    t_pre = time.perf_counter()\n    feats_scaled = scaler.transform([feats])\n\n    t_model = time.perf_counter()\n    pred    = model.predict(feats_scaled)\n    t_end   = time.perf_counter()\n\n    return jsonify({\n        "prediction": int(pred[0]),\n        "latency_ms": {\n            "preprocess": (t_model-t_pre)*1000,\n            "inference":  (t_end-t_model)*1000,\n            "total":      (t_end-t_start)*1000\n        }\n    })',
    realworld:'Google found that each 100ms increase in search load time reduces searches by 1%. Amazon found every 100ms of latency costs 1% in sales. These numbers mean latency is directly tied to revenue. This is why companies invest heavily in optimising every millisecond of their ML inference pipelines.' },

  { id:'lat_02', topic:'Latency', subtopic:'P50 P95 P99 Percentiles',
    theory:'Average latency is misleading because it hides worst-case experience. Percentile latency gives a more complete picture. P50 (median): 50% of requests are faster. P95: 95% of requests are faster — most users\' experience. P99: 99% of requests are faster — the worst normal experience. SLAs are usually defined at P95 or P99. The difference between P95 and P99 often reveals a slow path in your code.',
    interview:'Average latency hides the slow cases. If 99 requests take 10ms and 1 takes 10000ms, the average is 110ms which sounds okay. But that one slow request is a terrible experience. We use percentiles instead. P99 of 500ms means 99% of requests are faster than 500ms. 1% are slower. SLAs are usually set at P99.',
    code:'import numpy as np\n\nlatencies = []  # list of ms values\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    start = time.perf_counter()\n    # ... prediction ...\n    elapsed = (\n        time.perf_counter()-start)*1000\n    latencies.append(elapsed)\n    return jsonify({"prediction": 1})\n\ndef report():\n    arr = np.array(latencies)\n    print(f"P50: {np.percentile(arr,50):.1f}ms")\n    print(f"P95: {np.percentile(arr,95):.1f}ms")\n    print(f"P99: {np.percentile(arr,99):.1f}ms")',
    realworld:'A payments API SLA: P99 < 200ms. Monitoring shows P50=15ms, P95=45ms, P99=850ms. Average is only 20ms which looks fine. But P99=850ms means 1% of transactions take almost a second — 10,000 slow transactions per day at their scale. Investigation finds cold starts when a new container spins up without the model pre-loaded.' },

  { id:'lat_03', topic:'Latency', subtopic:'Common Causes of High Latency',
    theory:'High API latency is caused by: (1) Loading model per request instead of at startup. (2) Slow model — complex, not optimised for inference. (3) Synchronous database queries blocking prediction. (4) No caching — recomputing things that could be cached. (5) Large input/output — sending unnecessary data. (6) No connection pooling. (7) Running CPU-heavy inference without parallelism.',
    interview:'The most common cause of slow API responses is loading the model inside the request handler instead of at startup. This adds 2-5 seconds to every prediction. We fix this by loading the model once when the server starts. Other common causes are database queries that are not cached, sending too much unnecessary data, and not setting timeouts on external service calls.',
    code:'# WRONG: Load model per request\n@app.route("/predict")\ndef predict_wrong():\n    model = joblib.load("model.pkl")  # slow!\n    return model.predict(data)\n\n# RIGHT: Load once at startup\nmodel = joblib.load("model.pkl")  # once\n\n@app.route("/predict")\ndef predict_right():\n    return model.predict(data)  # fast\n\n# Always set timeouts:\nresult = requests.get(\n    slow_service_url, timeout=2.0)',
    realworld:'A churn prediction API was taking 8 seconds per request. Profiling revealed the 150MB model was being loaded on every request. Moving loading to startup reduced latency to 45ms. The next bottleneck was a SQL query — adding Redis cache for frequent customers reduced this from 200ms to 3ms.' },

  { id:'lat_04', topic:'Latency', subtopic:'Caching',
    theory:'Caching stores results of expensive operations so they can be returned quickly if the same request comes again. In-memory cache: store in Python dict — fast but lost when server restarts, not shared across workers. Redis: fast in-memory cache shared across all workers and servers, survives restarts. Cache repeated identical predictions, feature lookups for the same user, preprocessed data. Set TTL (time-to-live) to control freshness.',
    interview:'Caching means saving a result so if the same request comes again, we return the saved result instead of computing it again. For example, if we predict churn for customer 123 every time they log in and their features have not changed, we can cache the result for 1 hour. Redis is the most common cache for production — it is fast and shared across all server instances.',
    code:'# Simple cache\nfrom functools import lru_cache\n\n@lru_cache(maxsize=1000)\ndef predict_cached(features_tuple):\n    features = list(features_tuple)\n    return model.predict([features])[0]\n\n# Redis cache for production\nimport redis, json\nr = redis.Redis(host="localhost", port=6379)\n\ndef predict_with_cache(features):\n    key = f"pred:{hash(str(features))}"\n    cached = r.get(key)\n    if cached:\n        return json.loads(cached)\n    pred = model.predict([features])[0]\n    r.setex(key, 3600, json.dumps(int(pred)))\n    return int(pred)',
    realworld:'A news recommendation API serves 1 million daily active users. 60% open the app multiple times per day with the same session features. Without caching, each open triggers full model inference. With Redis caching (TTL=30 minutes), 60% of requests are served from cache in 2ms instead of 80ms. Infrastructure cost falls by 40%.' },

  // PIPELINE OPTIMISATION
  { id:'pipe_01', topic:'Pipeline Optimisation', subtopic:'Definition',
    theory:'Pipeline optimisation means making the entire end-to-end prediction flow — from receiving the request to returning the response — as fast and efficient as possible. Identify bottlenecks (the slowest step) and optimise that step first. Rule: profile before optimising. Never guess where the bottleneck is. The slowest step might be feature retrieval, preprocessing, model inference, or serialisation.',
    interview:'Pipeline optimisation is about making the full prediction process faster. The key rule is: measure first, then optimise. Do not guess where the slowdown is. Use a profiler to see exactly which step takes the most time. Then fix that step. Sometimes the model is fast but the database query is slow. Sometimes the opposite. Always fix the real bottleneck.',
    code:'import cProfile, pstats\nfrom io import StringIO\n\npr = cProfile.Profile()\npr.enable()\n\nfeats  = preprocess(raw_input)\nresult = model.predict([feats])\n\npr.disable()\ns  = StringIO()\nps = pstats.Stats(\n    pr, stream=s).sort_stats("cumulative")\nps.print_stats(10)  # top 10 slow functions\nprint(s.getvalue())',
    realworld:'A retail recommendation pipeline had 300ms total latency: database lookup 180ms, feature engineering 85ms, model inference 25ms. The team optimised the database query first (biggest bottleneck) by adding an index — latency dropped to 120ms. Then they vectorised feature engineering — total dropped to 45ms.' },

  { id:'pipe_02', topic:'Pipeline Optimisation', subtopic:'Batching',
    theory:'Batching means processing multiple inputs together in a single model call instead of one at a time. Models — especially neural networks — are optimised for batch processing and can process a batch of 32 items almost as fast as 1 item. This dramatically increases throughput. For real-time APIs, micro-batching: accumulate requests for a few milliseconds then process together. For offline tasks, always batch predict instead of looping.',
    interview:'Batching means making predictions for many inputs all at once instead of one by one. Neural networks are designed to process batches and it is almost as fast to process 64 items as to process 1. So instead of calling model.predict 1000 times in a loop, we call it once with all 1000 inputs. This can be 50-100x faster for neural networks.',
    code:'import numpy as np\n\n# SLOW: predict one at a time\npredictions = []\nfor sample in X_new:\n    pred = model.predict([sample])\n    predictions.append(pred[0])\n\n# FAST: batch predict all at once\npredictions = model.predict(X_new)\n\n# Neural network with batch size:\npreds = model.predict(\n    X_new,\n    batch_size=64)',
    realworld:'A content moderation system receives 10,000 image uploads per minute. Processing each image through a CNN individually takes 50ms = 8 minutes for 10,000 images. Batching 64 images together takes 80ms per batch = 13 seconds for 10,000 images. Batching makes this real-time instead of an 8-minute backlog.' },

  { id:'pipe_03', topic:'Pipeline Optimisation', subtopic:'Eager Loading',
    theory:'Eager loading means loading everything needed at startup before any requests arrive. Lazy loading means loading on first use. For ML models, always use eager loading — load the model at server startup, not on the first request. The first request to a lazy-loaded server is very slow (model loading time). Eager loading pays the startup cost once so every request is fast.',
    interview:'Eager loading means loading the model when the server starts, not when the first request arrives. If we load lazily, the first user after every server restart has to wait 3-5 seconds for the model to load while everyone else gets instant responses. We always load the model at startup so every user gets a fast response.',
    code:'from flask import Flask\nimport joblib\n\napp = Flask(__name__)\n\n# EAGER LOADING - correct for ML\nprint("Loading model...")\nmodel  = joblib.load("model.pkl")\nscaler = joblib.load("scaler.pkl")\nprint("Model loaded, ready to serve")\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data  = request.get_json()\n    feats = scaler.transform(\n        [data["features"]])\n    pred  = model.predict(feats)\n    return jsonify({"pred": int(pred[0])})',
    realworld:'An ML API serving a banking chatbot uses a 2GB NLP model that takes 8 seconds to load. Without eager loading, the first customer after every deployment waits 8 seconds, often triggering a timeout error. With eager loading, the server takes 8 seconds to start but every customer gets a sub-100ms response from the first request.' },

  // MODEL OPTIMISATION
  { id:'mopt_01', topic:'Model Optimisation', subtopic:'Definition',
    theory:'Model optimisation means making a trained model faster and smaller without significantly reducing accuracy, so it can be deployed efficiently. A model trained for best accuracy may be too slow or too large for production. Techniques: quantisation (reduce numerical precision), pruning (remove unnecessary weights), knowledge distillation (train a small model to mimic a large one), ONNX export (cross-framework efficient format).',
    interview:'Model optimisation means making the model faster and smaller so it can work in production within time and memory limits. A model that gets 95% accuracy but takes 2 seconds per prediction is not useful if we need responses in 100ms. We use techniques like quantisation to make the model smaller and faster, or ONNX to convert it to a format that runs faster on production hardware.',
    code:'import os, joblib, time, numpy as np\n\n# Check model size\njoblib.dump(model, "model.pkl")\nsize_mb = os.path.getsize("model.pkl") / 1e6\nprint(f"Model size: {size_mb:.1f} MB")\n\n# Benchmark inference speed\ntimes = []\nfor _ in range(100):\n    start = time.perf_counter()\n    model.predict(X_test[:1])\n    times.append(\n        (time.perf_counter()-start)*1000)\n\nprint(f"Avg: {np.mean(times):.2f}ms")\nprint(f"P99: {np.percentile(times,99):.2f}ms")',
    realworld:'GPT-4 is too large and slow for real-time chat. OpenAI creates GPT-4o-mini using distillation — 95% as capable but 100x cheaper and 10x faster. This makes it usable in products where cost and latency matter, while GPT-4 is reserved for complex tasks where quality is most important.' },

  { id:'mopt_02', topic:'Model Optimisation', subtopic:'Quantisation',
    theory:'Quantisation reduces numerical precision of model weights from float32 (32 bits) to int8 (8 bits) or float16. Reduces model size by 2-4x and speeds up inference by 2-4x because integer operations are faster than floating point. Quality loss is usually less than 1%. Dynamic quantisation: convert weights after training without retraining. Static quantisation: calibrate with representative data for better accuracy.',
    interview:'Quantisation makes the model smaller and faster by storing weights in lower precision numbers. Normally weights are 32-bit floats. Quantisation converts them to 8-bit integers. The model becomes 4x smaller and inference is faster because integer math is faster than floating point. The accuracy drop is usually less than 1% which is acceptable for most applications.',
    code:'import torch\nfrom torch.quantization import quantize_dynamic\n\n# Dynamic quantisation - easiest\n# No retraining needed\nquant_model = quantize_dynamic(\n    model,\n    {torch.nn.Linear},\n    dtype=torch.qint8\n)\n\n# Check size reduction\ndef get_size_mb(m):\n    torch.save(m.state_dict(), "tmp.pt")\n    size = os.path.getsize("tmp.pt")/1e6\n    os.remove("tmp.pt")\n    return size\n\nprint(f"Original:  {get_size_mb(model):.1f}MB")\nprint(f"Quantised: {get_size_mb(quant_model):.1f}MB")',
    realworld:'Meta deploys a 7-billion parameter language model to mobile phones for offline use. The float32 model is 28GB — impossible on a phone. INT4 quantisation reduces it to 3.5GB and inference runs at acceptable speed on a phone\'s CPU. Users get an on-device AI assistant that works without internet.' },

  { id:'mopt_03', topic:'Model Optimisation', subtopic:'ONNX Export',
    theory:'ONNX (Open Neural Network Exchange) is an open format for representing ML models. Exporting to ONNX makes the model run faster using ONNX Runtime, which is highly optimised for inference — 2-10x faster than native PyTorch/TensorFlow. Works on CPU, GPU, and specialised hardware. The model becomes framework-agnostic — a PyTorch model can be served by a C++ or Java application via ONNX without needing Python.',
    interview:'ONNX is a standard format that any ML model can be converted to. Once in ONNX format, we use ONNX Runtime to run inference which is much faster than running in PyTorch or TensorFlow directly. The model is also framework-agnostic so a Java or C++ application can use it without Python.',
    code:'import torch, onnxruntime as ort, numpy as np\n\n# Export PyTorch model to ONNX\ndummy_input = torch.randn(1, 10)\ntorch.onnx.export(\n    model, dummy_input, "model.onnx",\n    input_names=["features"],\n    output_names=["predictions"],\n    opset_version=11\n)\n\n# Run with ONNX Runtime (faster)\nsess = ort.InferenceSession("model.onnx")\ninput_name = sess.get_inputs()[0].name\n\npred = sess.run(\n    None,\n    {input_name: np.array(\n        features, dtype=np.float32\n    ).reshape(1,-1)}\n)',
    realworld:'Microsoft converts all production NLP models to ONNX for Azure Cognitive Services. A BERT model that takes 150ms in PyTorch takes 35ms in ONNX Runtime — a 4x speedup with zero accuracy loss. This allows them to serve millions of document analysis requests per day at a commercially viable price.' },

  { id:'mopt_04', topic:'Model Optimisation', subtopic:'Knowledge Distillation',
    theory:'Knowledge distillation trains a small, fast student model to mimic a large, accurate teacher model. The student learns not just from correct labels (hard targets) but from the teacher\'s output probabilities (soft targets). Soft targets carry more information — a teacher that gives 70% dog, 28% wolf, 2% cat is more informative than just the label "dog". Result: a small model that approaches the large model\'s accuracy.',
    interview:'Knowledge distillation is training a small model to behave like a large model. The large model is the teacher, the small model is the student. The student tries to match the teacher\'s full output probabilities, not just the correct answer. This extra information helps the student learn better. The result is a small fast model that is nearly as accurate as the large slow one.',
    code:'import torch.nn as nn\n\ndef distillation_loss(\n    student_logits,\n    teacher_logits,\n    true_labels,\n    temperature=3.0,\n    alpha=0.7\n):\n    soft_teacher = torch.softmax(\n        teacher_logits / temperature, dim=1)\n    soft_student = torch.log_softmax(\n        student_logits / temperature, dim=1)\n    kl_loss = nn.KLDivLoss()(\n        soft_student, soft_teacher)\n    ce_loss = nn.CrossEntropyLoss()(\n        student_logits, true_labels)\n    return alpha*kl_loss + (1-alpha)*ce_loss',
    realworld:'Google distils large BERT (340M parameters) into DistilBERT (66M parameters) — 60% smaller, 60% faster, while retaining 97% of BERT\'s performance. DistilBERT is used for latency-sensitive applications while full BERT handles tasks where quality is critical.' },
];
