/* batch3_data.js — MLOps & Experimentation: Reproducibility, Model Versions, MLflow */

window.BATCH_ID    = 'batch3';
window.BATCH_TITLE = 'Batch 3 — MLOps & Experimentation';

window.TOPIC_COLORS = {
  'Reproducibility': '#1A237E',
  'Model Versions':  '#4A148C',
  'MLflow':          '#004D40',
};

window.FLASHCARD_DATA = [

  // REPRODUCIBILITY
  { id:'rep_01', topic:'Reproducibility', subtopic:'Definition',
    theory:'Reproducibility means that if you run the same code on the same data with the same settings, you get exactly the same result every time. In ML this is critical because many operations involve randomness — train/test splits, weight initialisation, data shuffling, dropout. Without reproducibility you cannot compare experiments fairly, debug issues reliably, or prove your results to others.',
    interview:'Reproducibility means running the same code gives the same result every time. This matters because ML has a lot of randomness — how data is split, how weights are initialised, how dropout works. If two people run the same code and get different results, we cannot trust or compare experiments. Setting random seeds fixes the randomness so results are consistent.',
    code:'import random, numpy as np\nimport torch, tensorflow as tf\n\nSEED = 42\nrandom.seed(SEED)\nnp.random.seed(SEED)\ntorch.manual_seed(SEED)\ntf.random.set_seed(SEED)\n\ntrain_test_split(X, y, random_state=SEED)',
    realworld:'A pharmaceutical company builds a drug interaction prediction model. Regulators require the exact same model can be reproduced from scratch. Without reproducibility, they cannot prove to regulators that the deployed model matches the validated one. Full seed setting and environment pinning are mandatory for FDA approval.' },

  { id:'rep_02', topic:'Reproducibility', subtopic:'Random Seeds',
    theory:'Random seeds initialise the random number generator to a fixed state. After setting a seed, all random operations produce the same sequence of numbers every time. You need to set seeds for multiple libraries because they have independent random number generators: Python\'s random module, NumPy, PyTorch, TensorFlow/Keras. Set them all at the top of every script. Common value: 42 (conventional, no special meaning).',
    interview:'A random seed is a starting number for the random number generator. If we set seed to 42, the same random numbers are generated in the same order every time. We need to set it for Python, NumPy, and the deep learning framework separately because they each have their own generator. Without this, every run gives different results.',
    code:'import random, numpy as np\nimport torch, tensorflow as tf\n\ndef set_all_seeds(seed=42):\n    random.seed(seed)\n    np.random.seed(seed)\n    torch.manual_seed(seed)\n    torch.cuda.manual_seed_all(seed)\n    tf.random.set_seed(seed)\n    torch.backends.cudnn.deterministic = True\n    torch.backends.cudnn.benchmark = False\n\nset_all_seeds(42)',
    realworld:'A Kaggle team spends a week tuning a model. On submission day they rerun the code and get a different score. Investigation shows they forgot to set the random seed for the train/test split. Different validation data gave misleadingly optimistic results. Setting random_state=42 everywhere would have prevented this.' },

  { id:'rep_03', topic:'Reproducibility', subtopic:'Environment Management',
    theory:'Environment management means capturing and controlling all the software dependencies your code needs. Different versions of pandas, sklearn, or PyTorch can give different results or cause errors. A requirements.txt file pins exact package versions. A virtual environment (venv or conda) isolates project dependencies. Docker containerises the entire OS environment, ensuring identical runs everywhere.',
    interview:'Environment management means making sure the same versions of all libraries are used every time the code runs. If your code uses pandas 1.3 but someone else runs it with pandas 2.0, things might break or behave differently. We use a requirements.txt to record exact versions and a virtual environment to keep dependencies separate per project.',
    code:'python -m venv venv\nsource venv/bin/activate  # Linux/Mac\nvenv\\Scripts\\activate      # Windows\n\n# Save environment\npip freeze > requirements.txt\n\n# Recreate on another machine\npip install -r requirements.txt\n\nimport sklearn\nprint(sklearn.__version__)',
    realworld:'A data scientist builds a model on their laptop and it works perfectly. When deployed to production, predictions are wrong. Investigation reveals the production server has sklearn 0.24 while the laptop has sklearn 1.2 — StandardScaler behaviour changed between versions. Pinning versions in requirements.txt would have caught this immediately.' },

  { id:'rep_04', topic:'Reproducibility', subtopic:'Version Control for Code',
    theory:'Version control tracks every change made to your code over time. Git is the standard tool. Every commit is a snapshot you can return to. Branches allow experimentation without breaking working code. Good ML practice: commit before each experiment so you know exactly what code produced what results. Use .gitignore to exclude data files, model files, and virtual environments.',
    interview:'Version control means saving a history of every change we make to our code. Git is the tool everyone uses. Every time we make a meaningful change we commit it with a message. This means we can always go back to see what code we used for a specific experiment. Essential for reproducing past results and working in a team.',
    code:'git init\ngit add train.py features.py\ngit commit -m "feat: add lag features v1"\n\n# Before each experiment:\ngit commit -m "exp: test n_estimators=200"\n\n# .gitignore for ML:\n# data/\n# models/*.pkl\n# venv/\n# .env\n# __pycache__/',
    realworld:'A ML team runs 30 experiments over two weeks. Experiment 17 gave the best results but they continued and now cannot remember what code changes they made. With Git, they simply run git checkout to restore the exact code. Without version control they would have to recreate it from memory.' },

  { id:'rep_05', topic:'Reproducibility', subtopic:'Data Versioning',
    theory:'Code versioning is not enough — the data also changes over time. New rows are added, errors are corrected, columns are renamed. If you retrain on different data you get a different model. Data versioning means tracking which version of the dataset was used for each experiment. Tools: DVC (Data Version Control) works like Git but for large data files. At minimum, record file name, row count, and a hash/checksum in your experiment logs.',
    interview:'Data versioning means tracking which version of the data was used for each experiment. The code might be the same but if the data changed, the results will be different. We can compute a hash of the data file — a unique fingerprint — and record it with every experiment. DVC is a proper tool for this that works like Git but handles large files.',
    code:'import hashlib, pandas as pd\n\ndef data_hash(filepath):\n    with open(filepath, "rb") as f:\n        return hashlib.md5(f.read()).hexdigest()\n\nhash_val = data_hash("train.csv")\nprint(f"Data hash: {hash_val}")\n# Log this with your experiment!\n\n# DVC:\n# dvc add data/train.csv\n# git add data/train.csv.dvc\n# git commit -m "track training data"',
    realworld:'A fraud detection team retrains their model monthly. After a data pipeline bug was fixed in March, the training data changed slightly. Models trained before and after are not comparable. DVC tracks the exact data version used for each model, so when a model underperforms they can identify whether the issue was code, data, or hyperparameters.' },

  { id:'rep_06', topic:'Reproducibility', subtopic:'Reproducible Notebooks',
    theory:'Jupyter notebooks are a common source of reproducibility problems. Cells can be run out of order, leaving hidden state in memory. Best practices: restart kernel and run all cells before submitting results. Keep notebooks linear — no dependencies on out-of-order execution. Use nbconvert to run notebooks as scripts for automated pipelines. Clear outputs before committing to Git.',
    interview:'Jupyter notebooks can cause reproducibility problems because you can run cells in any order. If someone runs cell 5 then cell 2, they might get a result you cannot reproduce by running top to bottom. The rule is: always restart the kernel and run all cells from top to bottom before trusting results. Also clear outputs before committing to Git.',
    code:'# Run notebook cleanly:\n# Kernel -> Restart & Run All\n\n# Convert to script:\n# jupyter nbconvert --to script notebook.ipynb\n\n# Run as script:\n# python notebook.py\n\n# Clear outputs before git commit:\n# pip install nbstripout\n# nbstripout notebook.ipynb',
    realworld:'A data scientist shares a notebook with impressive results. A colleague cannot reproduce them. The issue: cell 7 used a variable set in cell 12 which had been run earlier during exploration. Running top-to-bottom fails because cell 7 runs before cell 12. Rewriting in logical order and running Restart & Run All fixes the issue.' },

  // MODEL VERSIONS
  { id:'mv_01', topic:'Model Versions', subtopic:'Definition',
    theory:'Model versioning is the practice of saving, labelling, and tracking different trained versions of a model over time. In production, models are retrained regularly as new data arrives. Each new version must be tested before replacing the current one. If a new version underperforms, you must be able to roll back instantly. Without versioning, rollback is impossible and you must retrain from scratch.',
    interview:'Model versioning means saving every version of the trained model with a clear name and not overwriting old ones. This is important because if we deploy a new model and it performs worse in production, we need to quickly switch back to the old one. Without versioning, going back would mean retraining from scratch which is slow and costly.',
    code:'import joblib\nfrom datetime import datetime\n\nversion = "v2_20240115"\njoblib.dump(model, f"model_{version}.pkl")\n\n# Load specific version\nmodel_v1 = joblib.load("model_v1_20240101.pkl")\nmodel_v2 = joblib.load("model_v2_20240115.pkl")\n\nprint("v1:", model_v1.score(X_test, y_test))\nprint("v2:", model_v2.score(X_test, y_test))',
    realworld:'A recommendation model at Flipkart is retrained every Sunday. Model v47 is deployed Monday. By Tuesday, click-through drops 8%. The team rolls back to v46 in 3 minutes. Root cause analysis runs while v46 serves users. Total user impact: under 2 hours. Without versioning: days of retraining and millions in lost revenue.' },

  { id:'mv_02', topic:'Model Versions', subtopic:'Saving Models',
    theory:'Different frameworks use different methods to save models. Scikit-learn: use joblib (preferred over pickle for large numpy arrays). PyTorch: save the state_dict (weights only — you need to recreate the model structure separately). TensorFlow/Keras: model.save() saves architecture + weights together. Always call model.eval() in PyTorch before inference to disable dropout and batch normalisation.',
    interview:'Saving a model means writing the trained weights to a file so we can load them later without retraining. For sklearn we use joblib. For PyTorch we save the state_dict which is just the weights. For Keras we save the whole model. After loading a PyTorch model we must call model.eval() to turn off dropout which behaves differently during training vs inference.',
    code:'import joblib\n# Sklearn\njoblib.dump(pipeline, "pipeline.pkl")\nmodel = joblib.load("pipeline.pkl")\n\n# PyTorch - save state_dict\ntorch.save(model.state_dict(), "weights.pt")\nmodel.load_state_dict(\n    torch.load("weights.pt"))\nmodel.eval()  # IMPORTANT\n\n# Keras\nmodel.save("model.keras")\nmodel = tf.keras.models.load_model(\n    "model.keras")',
    realworld:'A startup builds a sentiment model that takes 6 hours to train on a GPU costing 500 rupees/hour. They save with joblib immediately after training. Now it loads in 2 seconds for every API request. Without saving, they would need to retrain for 6 hours and 3000 rupees every time the server restarts.' },

  { id:'mv_03', topic:'Model Versions', subtopic:'Staging and Production',
    theory:'In a proper ML workflow, a newly trained model does not go directly to production. Stages: Development (training and experiments), Staging (testing in production-like environment, no user impact), Production (serving real users). Shadow mode: run the new model in parallel with production, compare outputs without affecting users. Canary deployment: send a small percentage of traffic to the new model first.',
    interview:'In real projects, a new model does not go straight to production. It first goes to staging where we test it with real data but without affecting real users. Once it passes all checks, we move it to production. If something goes wrong, we move the old model back. MLflow Model Registry manages these stages.',
    code:'import mlflow\n\nmlflow.register_model(\n    "runs:/RUN_ID/model",\n    "fraud-detector")\n\nclient = mlflow.tracking.MlflowClient()\nclient.transition_model_version_stage(\n    name="fraud-detector",\n    version=3,\n    stage="Staging"\n)\n\n# Load production model:\nmodel = mlflow.pyfunc.load_model(\n    "models:/fraud-detector/Production")',
    realworld:'Uber\'s surge pricing model goes through 3 stages: (1) Dev: trained and evaluated offline, (2) Staging: tested on 1% of ride requests with results logged but not shown to users, (3) Production: full rollout after staging metrics match expectations. This prevents a buggy pricing model from affecting millions of riders.' },

  { id:'mv_04', topic:'Model Versions', subtopic:'A/B Testing Models',
    theory:'A/B testing for models means running two versions simultaneously with different user groups to compare real-world performance. Group A gets model v1, Group B gets model v2. You measure actual business metrics (click rate, conversion, revenue) not just ML metrics. This is more reliable than offline evaluation because it measures real user behaviour. Statistical significance testing determines if the difference is real or random.',
    interview:'A/B testing means running two model versions at the same time with different users. Half the users get the old model, half get the new one. We compare real business outcomes like whether users clicked or bought something. This is more reliable than just comparing accuracy numbers because it shows how the model performs in the real world with real users.',
    code:'import random\n\n@app.route("/predict", methods=["POST"])\ndef predict():\n    data = request.get_json()\n    if random.random() < 0.5:\n        pred    = model_v1.predict(\n            [data["features"]])\n        version = "v1"\n    else:\n        pred    = model_v2.predict(\n            [data["features"]])\n        version = "v2"\n    log_prediction(version, pred)\n    return jsonify({"pred": int(pred[0])})',
    realworld:'Amazon tests a new recommendation model by showing it to 10% of users for two weeks. The new model shows 3.2% higher add-to-cart rate with p=0.001. This means the improvement is real, not random chance. They roll out to 100% of users, generating significant additional annual revenue.' },

  { id:'mv_05', topic:'Model Versions', subtopic:'Model Metadata',
    theory:'Model metadata is information stored alongside the model file: date trained, data version/hash, hyperparameters, performance metrics, feature names and order, preprocessing steps, person who trained it, git commit hash. Without metadata, a model file is a black box — you do not know if it is still valid or how to use it correctly.',
    interview:'Model metadata is all the information about how the model was built — when it was trained, what data was used, what the performance was, what features it expects. Without this, a model file is just a black box. If someone finds an old model file in 6 months, they need to know if it is still valid, what features to feed it, and how well it performed.',
    code:'import json, joblib\nfrom datetime import datetime\n\nmetadata = {\n    "version":     "v3",\n    "trained_at":  datetime.now().isoformat(),\n    "data_hash":   "abc123def456",\n    "features":    ["age","income","tenure"],\n    "metrics": {"f1": 0.87, "auc": 0.92},\n    "hyperparams": {\n        "n_estimators": 200,\n        "max_depth": 8\n    }\n}\njoblib.dump(model, "model_v3.pkl")\nwith open("model_v3_meta.json","w") as f:\n    json.dump(metadata, f, indent=2)',
    realworld:'A regulatory audit at a financial institution requires explaining every credit decision made in the past 3 years. Without model metadata they cannot tell which model was used on which date. With proper metadata logging they can show: on date X, model v7 was in production, trained on data from Y, with these features and this performance.' },

  // MLFLOW
  { id:'mlf_01', topic:'MLflow', subtopic:'Definition',
    theory:'MLflow is an open-source platform for managing the full ML lifecycle. Four main components: (1) Tracking — logs parameters, metrics, and artefacts for each run. (2) Projects — packages code for reproducible runs. (3) Models — standard format for packaging models. (4) Model Registry — central hub to manage model versions and lifecycle stages. It provides a UI to compare all experiments visually.',
    interview:'MLflow is a tool that helps manage machine learning experiments. It records every experiment run — what parameters we used, what results we got, and saves the trained model. We can open the MLflow UI in a browser and compare all experiments side by side in a table. This makes it easy to find which combination of settings gave the best result.',
    code:'# pip install mlflow\n# mlflow ui  (open http://localhost:5000)\n\nimport mlflow\n\nmlflow.set_experiment("churn-prediction")\n\nwith mlflow.start_run(run_name="rf-v1"):\n    mlflow.log_param("n_estimators", 100)\n    mlflow.log_metric("f1", 0.87)\n    mlflow.sklearn.log_model(\n        model, "model")',
    realworld:'A data science team at a bank runs 80 experiments tuning a loan default model over 3 weeks. Without MLflow they track results in a spreadsheet and lose track of which model file matches which experiment. With MLflow, the team opens the UI, sorts by AUC, and immediately identifies the best model to deploy.' },

  { id:'mlf_02', topic:'MLflow', subtopic:'Tracking Experiments',
    theory:'MLflow Tracking records every model training run. You log: parameters (hyperparameters set before training), metrics (performance scores), artefacts (model files, plots). All runs stored in a tracking server (local by default). You can log metrics at each epoch to see training curves. The UI shows all runs in a sortable table for easy comparison.',
    interview:'MLflow tracking records everything about each training run automatically. We wrap training code in a "with mlflow.start_run()" block. Inside we log parameters and metrics. MLflow saves all of this. Later we open the browser UI and see a table of all runs, sort by any metric, and compare them easily.',
    code:'import mlflow\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import f1_score\n\nmlflow.set_experiment("my-experiment")\n\nwith mlflow.start_run():\n    n_est, depth = 100, 5\n    mlflow.log_param("n_estimators", n_est)\n    mlflow.log_param("max_depth",    depth)\n\n    model = RandomForestClassifier(\n        n_estimators=n_est,\n        max_depth=depth)\n    model.fit(X_train, y_train)\n\n    f1 = f1_score(y_test,\n                  model.predict(X_test))\n    mlflow.log_metric("f1", f1)\n    mlflow.sklearn.log_model(model, "model")',
    realworld:'A competition team running 100+ experiments uses MLflow tracking. After 3 weeks they open the UI, filter runs where F1 > 0.85, sort by AUC, and in 30 seconds identify the best 5 runs. They compare hyperparameters and find that max_depth=7 consistently outperforms other values across different n_estimators settings.' },

  { id:'mlf_03', topic:'MLflow', subtopic:'Logging Parameters and Metrics',
    theory:'Parameters are the inputs to your experiment — hyperparameters set before training. Metrics are the outputs — performance scores after training. log_param() for a single parameter, log_params() for a dictionary. log_metric() with step for time series (e.g., loss per epoch). You can also log artefacts: any file like plots, data samples, feature importance charts.',
    interview:'log_param logs a setting we chose before training. log_metric logs a result we measured after training. We can also log metrics at each training step to see how the model improved over time — this shows up as a graph in the MLflow UI. log_artifact lets us save any file like a plot or data sample alongside the run.',
    code:'import mlflow\nimport matplotlib.pyplot as plt\n\nwith mlflow.start_run():\n    mlflow.log_params({\n        "n_estimators": 100,\n        "max_depth": 5,\n        "lr": 0.001\n    })\n\n    # Metric per epoch (shows as graph)\n    for epoch in range(10):\n        loss = train_one_epoch()\n        mlflow.log_metric(\n            "train_loss", loss,\n            step=epoch)\n\n    # Log a plot\n    plt.plot(history)\n    plt.savefig("loss_curve.png")\n    mlflow.log_artifact("loss_curve.png")',
    realworld:'A deep learning researcher logs training and validation loss at every epoch with the step parameter. In the MLflow UI they see training loss decreasing while validation loss starts increasing at epoch 35 — clear overfitting. They set early stopping patience=5 and retrain, achieving better generalisation.' },

  { id:'mlf_04', topic:'MLflow', subtopic:'Logging Models',
    theory:'MLflow saves trained models in a standardised format including the model file, dependencies, and a signature (input/output schema). This makes it easy to load the model later without remembering which library or format was used. mlflow.sklearn.log_model() for sklearn, mlflow.pytorch.log_model() for PyTorch. The saved model can be loaded with mlflow.pyfunc.load_model() regardless of the original framework.',
    interview:'We save the trained model inside the MLflow run using log_model. This stores the model file along with information about what inputs it expects and what outputs it produces. Later we can load it using just the run ID without needing to remember the file path or what library was used. The model signature documents the expected input format.',
    code:'import mlflow\nfrom mlflow.models.signature import (\n    infer_signature)\n\nwith mlflow.start_run() as run:\n    signature = infer_signature(\n        X_train, model.predict(X_train))\n\n    mlflow.sklearn.log_model(\n        model,\n        artifact_path="model",\n        signature=signature,\n        input_example=X_train[:3])\n\n# Load by run ID:\nloaded = mlflow.sklearn.load_model(\n    f"runs:/{run.info.run_id}/model")',
    realworld:'A team deploys a model saved with MLflow. Six months later a new engineer needs to update it. They find the run in MLflow, see the input signature showing 12 features in a specific order, load the model, and verify it works — all without reading any of the original training code.' },

  { id:'mlf_05', topic:'MLflow', subtopic:'Model Registry',
    theory:'The MLflow Model Registry is a centralised store for managing model versions and their lifecycle. Register a trained model from a run into the Registry. Each version is tracked separately. Stages: None (registered), Staging (being tested), Production (serving users), Archived (retired). Teams can add descriptions, tags, and comments. Enables workflow: train → register → review → staging → production.',
    interview:'The Model Registry is like a controlled store for model versions. When a model is ready, we register it. After testing we move it to Staging. After it passes all checks we move it to Production. The old production model moves to Archived. Our serving code always loads from "Production" so when we promote a new version, the deployment updates automatically without changing any serving code.',
    code:'import mlflow\nfrom mlflow.tracking import MlflowClient\n\nclient = MlflowClient()\n\nmlflow.register_model(\n    model_uri="runs:/RUN_ID/model",\n    name="loan-default-predictor")\n\nclient.transition_model_version_stage(\n    name="loan-default-predictor",\n    version=2,\n    stage="Production")\n\n# Always loads current production:\nmodel = mlflow.pyfunc.load_model(\n    "models:/loan-default-predictor/Production")',
    realworld:'A healthcare company uses MLflow Registry for their diagnosis assistance model. Version 8 is in Production. The team trains version 9, registers it, and moves it to Staging. Two doctors test it for a week on historical cases. It performs better on rare conditions. They transition v9 to Production — the API automatically serves v9 because it loads from the "Production" alias.' },

  { id:'mlf_06', topic:'MLflow', subtopic:'Autolog',
    theory:'MLflow autolog automatically logs parameters, metrics, and models without writing any manual logging code. Call mlflow.autolog() or framework-specific versions like mlflow.sklearn.autolog() before training. For sklearn it logs all hyperparameters, metrics, feature importance, and the model automatically. For Keras it logs per-epoch metrics and the final model. Great for quick experiments; explicit logging gives more control for production.',
    interview:'MLflow autolog is a shortcut that automatically records everything without us writing any logging code. We add one line — mlflow.sklearn.autolog() — and then train normally. MLflow captures all hyperparameters, metrics, and the model automatically. Very convenient for quick experiments. For production we usually log manually for more control.',
    code:'import mlflow\n\n# Enable autolog\nmlflow.sklearn.autolog()\n\n# Train normally — everything is logged:\nfrom sklearn.ensemble import (\n    RandomForestClassifier)\nmodel = RandomForestClassifier(\n    n_estimators=100, max_depth=5)\nmodel.fit(X_train, y_train)\n# Logged automatically:\n# hyperparameters, metrics,\n# model file, feature importances\n\n# For Keras:\nmlflow.tensorflow.autolog()\nmodel.fit(X_train, y_train, epochs=50)',
    realworld:'A data scientist exploring 20 different model architectures in one afternoon uses mlflow.autolog(). Each model.fit() call automatically creates a new MLflow run with all hyperparameters and metrics. At the end of the day they open the UI, compare all 20 runs, and identify the best 3 to investigate further — without writing a single line of logging code.' },
];
