/* batch5_data.js — Deep Learning: PyTorch, TensorFlow/Keras, CNN, LSTM, YOLO */

window.BATCH_ID    = 'batch5';
window.BATCH_TITLE = 'Batch 5 — Deep Learning';

window.TOPIC_COLORS = {
  'PyTorch':               '#1A237E',
  'TensorFlow / Keras':    '#4A148C',
  'CNN':                   '#004D40',
  'LSTM':                  '#BF360C',
  'YOLO':                  '#880E4F',
};

window.FLASHCARD_DATA = [

  // PYTORCH
  { id:'pt_01', topic:'PyTorch', subtopic:'Definition',
    theory:'PyTorch is an open-source deep learning framework by Meta. Its key feature is dynamic computation graphs — built as code runs, making it feel like normal Python and easy to debug. It has autograd (automatic differentiation) which computes gradients automatically for backpropagation. PyTorch is the preferred choice for custom architectures and research.',
    interview:'PyTorch is a deep learning library from Meta. It is the most popular framework in research and is used in production too. The best thing about PyTorch is that it feels like regular Python — we build the model step by step and can debug it easily. It handles all the gradient calculations automatically.',
    code:'import torch\nimport torch.nn as nn\nimport torch.optim as optim\n\nprint(torch.__version__)\n\ndevice = torch.device(\n    "cuda" if torch.cuda.is_available()\n    else "cpu")\nprint(f"Using: {device}")\n\nx = torch.tensor([1.0, 2.0, 3.0])\nprint(x.dtype)   # torch.float32\nprint(x.shape)   # torch.Size([3])',
    realworld:'Most state-of-the-art AI research papers release code in PyTorch — GPT, BERT, Stable Diffusion, LLaMA. Meta uses PyTorch for all their AI products including Instagram\'s recommendation system. Researchers almost always choose PyTorch for new architectures because of its flexibility.' },

  { id:'pt_02', topic:'PyTorch', subtopic:'Tensors',
    theory:'A tensor is the fundamental data structure in PyTorch — an n-dimensional array with GPU support and autograd. Tensors can live on CPU or GPU. Moving to GPU with .to(device) enables much faster computation. requires_grad=True tells PyTorch to track operations for gradient computation. All model inputs, outputs, and weights are tensors.',
    interview:'A tensor is like a NumPy array but it can run on a GPU and PyTorch can automatically calculate gradients for it. All data in PyTorch — inputs, outputs, model weights — are tensors. We move tensors to the GPU with .to("cuda") to speed up training. requires_grad=True tells PyTorch to remember operations so it can calculate the gradient later.',
    code:'import torch\n\na = torch.tensor([[1.0,2.0],[3.0,4.0]])\nb = torch.zeros(3, 4)\nc = torch.randn(5, 5)\n\nprint(a.shape)   # torch.Size([2, 2])\nprint(a.dtype)   # torch.float32\nprint(a.device)  # cpu\n\na = a.to("cuda")  # move to GPU\n\nx = torch.tensor([2.0], requires_grad=True)\ny = x ** 2\ny.backward()\nprint(x.grad)    # tensor([4.])',
    realworld:'Tesla\'s Autopilot processes camera frames as tensors of shape (batch, channels, height, width). Moving tensors to GPU reduces inference time from 50ms to 3ms per frame. At 30 frames per second, GPU tensor processing is what makes real-time driving decisions possible.' },

  { id:'pt_03', topic:'PyTorch', subtopic:'Defining a Model',
    theory:'In PyTorch you define a model as a class inheriting from nn.Module. Define layers in __init__ and the forward pass in forward(). The forward method describes how data flows through the model. PyTorch automatically computes the backward pass using autograd. nn.Sequential is a shortcut for simple linear stacks of layers.',
    interview:'We define a PyTorch model as a Python class. In __init__ we define the layers — like Linear layers, activation functions, and dropout. In the forward method we define how data flows through those layers. PyTorch handles the backward pass automatically. nn.Sequential is a shortcut when layers just run one after another.',
    code:'import torch.nn as nn\n\nclass MyModel(nn.Module):\n    def __init__(self, in_f, hidden, out_f):\n        super().__init__()\n        self.fc1  = nn.Linear(in_f, hidden)\n        self.relu = nn.ReLU()\n        self.drop = nn.Dropout(0.3)\n        self.fc2  = nn.Linear(hidden, out_f)\n\n    def forward(self, x):\n        x = self.relu(self.fc1(x))\n        x = self.drop(x)\n        return self.fc2(x)\n\nmodel = MyModel(10, 64, 2)\n\n# Quick Sequential version:\nmodel = nn.Sequential(\n    nn.Linear(10, 64), nn.ReLU(),\n    nn.Dropout(0.3), nn.Linear(64, 2))',
    realworld:'OpenAI\'s GPT models are defined as PyTorch nn.Module classes with hundreds of transformer layers. The modular class structure allows researchers to easily swap components — replace the attention mechanism, add new layer types — all by modifying __init__ and forward without changing the training code.' },

  { id:'pt_04', topic:'PyTorch', subtopic:'Training Loop',
    theory:'The PyTorch training loop is explicit — you write it yourself for full control. Steps: (1) Set model to train mode. (2) Loop over batches. (3) Forward pass. (4) Calculate loss. (5) Zero gradients — critical, PyTorch accumulates gradients by default. (6) Backward pass. (7) Optimizer step: update weights. (8) Track metrics. Repeat for each epoch.',
    interview:'The training loop in PyTorch is written by us step by step. For each batch: send data through the model to get predictions, calculate how wrong the predictions are, call optimizer.zero_grad() to clear old gradients, call loss.backward() to calculate new gradients, and call optimizer.step() to update the weights. We repeat this for every batch and every epoch.',
    code:'model.train()  # enable dropout\n\nfor epoch in range(num_epochs):\n    total_loss = 0\n    for X_batch, y_batch in train_loader:\n        X_batch = X_batch.to(device)\n        y_batch = y_batch.to(device)\n\n        predictions = model(X_batch)\n        loss = criterion(predictions, y_batch)\n\n        optimizer.zero_grad()  # clear gradients\n        loss.backward()        # compute gradients\n        optimizer.step()       # update weights\n\n        total_loss += loss.item()\n    print(f"Epoch {epoch}: "\n          f"Loss={total_loss/len(train_loader):.4f}")',
    realworld:'Hugging Face fine-tunes BERT using exactly this training loop pattern. Each epoch processes 50,000 tweets in batches of 32 for 3 epochs with Adam. The explicit loop allows researchers to add custom logging, gradient clipping, and learning rate warmup exactly where needed.' },

  { id:'pt_05', topic:'PyTorch', subtopic:'DataLoader',
    theory:'DataLoader handles loading data in batches during training: batching, shuffling, and parallel loading. You create a Dataset object defining how to load a single sample, then wrap it in a DataLoader. shuffle=True randomises order each epoch. num_workers uses multiple CPU processes to load data in parallel while GPU trains, preventing the GPU from waiting for data.',
    interview:'DataLoader takes our dataset and automatically splits it into batches, shuffles the data each epoch, and loads batches in the background while training continues. The num_workers parameter is important — it uses multiple CPU processes to load the next batch while the GPU is processing the current one, preventing the GPU from sitting idle.',
    code:'from torch.utils.data import (\n    TensorDataset, DataLoader)\nimport torch\n\nX = torch.tensor(X_train, dtype=torch.float32)\ny = torch.tensor(y_train, dtype=torch.long)\ndataset = TensorDataset(X, y)\n\ntrain_loader = DataLoader(\n    dataset,\n    batch_size=32,\n    shuffle=True,\n    num_workers=4,\n    pin_memory=True\n)',
    realworld:'ImageNet training requires loading millions of high-resolution images from disk. Without parallel loading, the GPU would be idle 70% of the time. DataLoader with num_workers=8 pre-loads the next batch while the GPU trains on the current one, keeping GPU utilisation above 95% and cutting training time from 3 days to 1 day.' },

  { id:'pt_06', topic:'PyTorch', subtopic:'Evaluation Mode',
    theory:'PyTorch models have two modes: train and eval. model.train() enables dropout and batch normalisation in training mode. model.eval() disables dropout (all neurons active) and fixes batch norm statistics. You must call model.eval() before inference or evaluation. Forgetting this is a common bug — dropout randomly zeros neurons, so predictions will be different every time in train mode.',
    interview:'PyTorch has two modes — train and eval. During training, dropout randomly switches off neurons to prevent overfitting. During evaluation we want the full model active so we call model.eval() to turn off dropout. We also use torch.no_grad() to tell PyTorch not to calculate gradients, saving memory and making inference faster. Forgetting model.eval() is a very common bug.',
    code:'# Training\nmodel.train()\nfor X_batch, y_batch in train_loader:\n    pred = model(X_batch)\n    loss = criterion(pred, y_batch)\n    optimizer.zero_grad()\n    loss.backward()\n    optimizer.step()\n\n# Evaluation - MUST switch mode\nmodel.eval()\nwith torch.no_grad():\n    for X_batch, y_batch in test_loader:\n        pred  = model(X_batch)\n        preds = torch.argmax(pred, dim=1)',
    realworld:'A sentiment analysis model in production was giving inconsistent results — the same tweet got different scores each time. The bug: model.eval() was never called. Dropout was randomly disabling 30% of neurons on each call. Adding model.eval() before serving fixed the non-determinism immediately.' },

  // TENSORFLOW / KERAS
  { id:'tf_01', topic:'TensorFlow / Keras', subtopic:'Definition',
    theory:'TensorFlow is an open-source deep learning framework by Google. Keras is the high-level API on top of TensorFlow (built in as tf.keras) making it much easier to use. Keras is the go-to choice for beginners and rapid prototyping — model.compile(), model.fit(), model.evaluate() makes training simple. TensorFlow is heavily used in production especially on mobile (TFLite) and web (TF.js).',
    interview:'TensorFlow is Google\'s deep learning framework. Keras is the easy-to-use API on top. With Keras we build models by stacking layers, call compile to set the optimizer and loss function, and call fit to train. It is much simpler than PyTorch for standard tasks. TensorFlow is very popular for production deployment especially on mobile devices using TFLite.',
    code:'import tensorflow as tf\nfrom tensorflow import keras\n\nprint(tf.__version__)\nprint(tf.config.list_physical_devices("GPU"))\n\nmodel = keras.Sequential([\n    keras.layers.Dense(\n        64, activation="relu",\n        input_shape=(10,)),\n    keras.layers.Dropout(0.3),\n    keras.layers.Dense(\n        32, activation="relu"),\n    keras.layers.Dense(\n        1,  activation="sigmoid")\n])',
    realworld:'Google uses TensorFlow everywhere — Gmail smart reply, Google Photos, Google Translate, YouTube recommendations. TFLite runs TensorFlow models on Android phones offline, powering features like real-time translation in Google Lens.' },

  { id:'tf_02', topic:'TensorFlow / Keras', subtopic:'Sequential vs Functional API',
    theory:'Keras offers two ways to build models. Sequential: simplest, stack layers one after another, works for straightforward linear architectures. Functional: more flexible, allows multiple inputs, multiple outputs, skip connections, shared layers. Define layers as functions and connect explicitly. For most standard problems Sequential is sufficient. For complex architectures like ResNet (skip connections) use Functional.',
    interview:'Keras has two main ways to build models. Sequential is the simple way — just stack layers one on top of another. Functional API is more flexible and lets us build complex architectures with multiple inputs, multiple outputs, or skip connections. Both work the same way once built — same compile, fit, and predict methods.',
    code:'from tensorflow import keras\n\n# Sequential\nseq = keras.Sequential([\n    keras.layers.Dense(64, activation="relu"),\n    keras.layers.Dense(1,  activation="sigmoid")\n])\n\n# Functional API\ninputs  = keras.Input(shape=(10,))\nx       = keras.layers.Dense(\n              64, activation="relu")(inputs)\noutputs = keras.layers.Dense(\n              1,  activation="sigmoid")(x)\nfunc_model = keras.Model(\n    inputs=inputs, outputs=outputs)',
    realworld:'A multi-modal recommendation system at Pinterest takes two inputs: image features and text. The Functional API builds two separate branches — one CNN for images, one LSTM for text — then merges them. This architecture is impossible with Sequential but straightforward with the Functional API.' },

  { id:'tf_03', topic:'TensorFlow / Keras', subtopic:'Compile and Fit',
    theory:'model.compile() configures the model for training: sets the optimizer, loss function, and metrics. model.fit() trains the model. Key parameters: epochs, batch_size, validation_split, callbacks. fit() returns a history object with training curves for plotting. The validation_split automatically holds out a fraction of training data to monitor validation performance.',
    interview:'compile() is where we tell the model how to train — which optimizer, which loss function, and what metrics to track. fit() is where training actually happens. We give it training data, number of epochs, and batch size. validation_split automatically holds out part of the training data to monitor validation performance. The history object from fit() lets us plot training curves to check for overfitting.',
    code:'model.compile(\n    optimizer="adam",\n    loss="binary_crossentropy",\n    metrics=["accuracy", "AUC"]\n)\n\nhistory = model.fit(\n    X_train, y_train,\n    epochs=50,\n    batch_size=32,\n    validation_split=0.2,\n    verbose=1\n)\n\nimport matplotlib.pyplot as plt\nplt.plot(history.history["loss"],\n         label="Train Loss")\nplt.plot(history.history["val_loss"],\n         label="Val Loss")\nplt.legend()\nplt.show()',
    realworld:'A Keras model for medical image classification is compiled with Adam and categorical_crossentropy. Training curves show training accuracy at 98% while validation plateaus at 87% from epoch 40 — clear overfitting. The team adds Dropout and L2 regularisation, retrains, and both curves converge to 92%.' },

  { id:'tf_04', topic:'TensorFlow / Keras', subtopic:'Callbacks',
    theory:'Callbacks are functions called automatically at specific points during training. Essential callbacks: EarlyStopping — stops training when validation metric stops improving (patience parameter). ModelCheckpoint — saves the model at its best validation performance. ReduceLROnPlateau — reduces learning rate when validation loss plateaus. TensorBoard — logs metrics for visualisation.',
    interview:'Callbacks are actions that happen automatically during training. EarlyStopping watches the validation loss and stops training if it does not improve for several epochs — prevents overfitting and saves time. ModelCheckpoint saves the best model automatically. ReduceLROnPlateau reduces the learning rate when the model stops improving.',
    code:'from tensorflow.keras.callbacks import (\n    EarlyStopping, ModelCheckpoint,\n    ReduceLROnPlateau)\n\nes = EarlyStopping(\n    monitor="val_loss",\n    patience=10,\n    restore_best_weights=True)\n\ncheckpoint = ModelCheckpoint(\n    filepath="best_model.keras",\n    monitor="val_loss",\n    save_best_only=True)\n\nreduce_lr = ReduceLROnPlateau(\n    monitor="val_loss",\n    factor=0.5, patience=5)\n\nmodel.fit(\n    X_train, y_train, epochs=200,\n    callbacks=[es, checkpoint, reduce_lr])',
    realworld:'A team sets epochs=500 but uses EarlyStopping with patience=15 and ModelCheckpoint. Training stops at epoch 83. ModelCheckpoint already saved the best weights from epoch 68. Without callbacks they would train 500 epochs, overfit heavily, and manually track which epoch had the best model.' },

  { id:'tf_05', topic:'TensorFlow / Keras', subtopic:'Saving and Loading',
    theory:'Keras models can be saved in two formats. SavedModel (recommended): saves full model including architecture, weights, and training config. Can be loaded without original code. HDF5 (.h5): older format. For production, SavedModel integrates with TF Serving. You can also save only weights with save_weights() to load into a different architecture.',
    interview:'Saving a Keras model stores the architecture and weights together so we can load it later without retraining. model.save() saves everything. load_model() restores the full model ready to use. After loading we should always verify the predictions match the original model on a few samples to confirm nothing was lost.',
    code:'model.save("my_model.keras")\n\nloaded = tf.keras.models.load_model(\n    "my_model.keras")\n\n# Weights only:\nmodel.save_weights("weights.h5")\nmodel.load_weights("weights.h5")\n\n# Verify:\nimport numpy as np\npred_orig   = model.predict(X_test[:5])\npred_loaded = loaded.predict(X_test[:5])\nprint(np.allclose(pred_orig, pred_loaded))',
    realworld:'A Keras NLP model trained for 2 days on a GPU is saved immediately after training. Months later, a new engineer loads the original model, modifies only the final layer for a new task, and fine-tunes for 2 hours instead of retraining from scratch — saving 46 hours of GPU compute time.' },

  // CNN
  { id:'cnn_01', topic:'CNN', subtopic:'Definition',
    theory:'CNN (Convolutional Neural Network) is designed for processing grid-structured data like images. Unlike fully connected networks where every neuron connects to every input, convolutional layers use small filters (kernels) that slide across the input, detecting local patterns like edges, corners, and textures. CNNs learn these filters automatically during training. Dominant architecture for image classification, object detection, and segmentation.',
    interview:'A CNN is a neural network designed for images. Instead of connecting every neuron to every pixel, it uses small filters that slide across the image looking for patterns. Early layers detect simple patterns like edges and corners. Later layers combine these into complex patterns like eyes or wheels. CNNs learn what patterns to look for automatically during training.',
    code:'import torch.nn as nn\n\nclass SimpleCNN(nn.Module):\n    def __init__(self, num_classes):\n        super().__init__()\n        self.conv = nn.Sequential(\n            nn.Conv2d(1, 32, kernel_size=3,\n                      padding=1),\n            nn.ReLU(),\n            nn.MaxPool2d(2),\n            nn.Conv2d(32, 64, kernel_size=3,\n                      padding=1),\n            nn.ReLU(),\n            nn.MaxPool2d(2)\n        )\n        self.fc = nn.Sequential(\n            nn.Flatten(),\n            nn.Linear(64*7*7, 128),\n            nn.ReLU(), nn.Dropout(0.5),\n            nn.Linear(128, num_classes)\n        )\n    def forward(self, x):\n        return self.fc(self.conv(x))',
    realworld:'Instagram uses CNNs to automatically detect inappropriate content in billions of images uploaded daily. Early layers detect basic visual features. Deeper layers recognise complex patterns indicating policy violations. The CNN processes each image in milliseconds and flags content for human review.' },

  { id:'cnn_02', topic:'CNN', subtopic:'Convolutional Layer',
    theory:'A convolutional layer applies learnable filters to the input. Each filter slides across the input and computes dot products between filter weights and input values, producing a feature map. Parameters: in_channels, out_channels (number of filters), kernel_size (filter size, e.g., 3x3), stride, padding. Each filter detects a different feature. Output size formula: (in - kernel + 2*padding)/stride + 1.',
    interview:'A convolutional layer has small filters — usually 3x3 — that slide across the image. Each filter multiplies its weights with the pixels it covers and sums them up, producing one number. As the filter slides it produces a grid of numbers called a feature map. Each filter learns to detect one specific pattern. With 32 filters we get 32 feature maps.',
    code:'import torch.nn as nn\n\n# Input: (batch, 3, 224, 224) - RGB\n# After conv: (batch, 32, 222, 222)\nconv = nn.Conv2d(\n    in_channels=3,\n    out_channels=32,\n    kernel_size=3,\n    stride=1,\n    padding=0\n)\n\n# With padding=1: same spatial size\nconv_same = nn.Conv2d(\n    3, 32, kernel_size=3, padding=1)\n# Output: (batch, 32, 224, 224)',
    realworld:'A self-driving car\'s lane detection system uses convolutional layers where early filters detect simple edges. These are combined in deeper layers to detect lane markings, road boundaries, and lane curvature. The CNN was trained on millions of labelled road images and detects lanes in real time at 30 FPS.' },

  { id:'cnn_03', topic:'CNN', subtopic:'Pooling Layer',
    theory:'Pooling layers reduce the spatial dimensions (height and width) of feature maps while keeping depth the same. MaxPooling takes the maximum value in each window — retains the strongest feature signal. Common: MaxPool2d(2) halves both dimensions (224x224 → 112x112). Benefits: reduces computation, makes the model more robust to small shifts (translation invariance), prevents overfitting.',
    interview:'Pooling reduces the size of the feature maps. MaxPooling takes the largest value from each small window. This shrinks the image while keeping the most important information. It also makes the model less sensitive to exactly where a feature appears — if an edge shifts a few pixels it still gets detected. After a few pooling layers the image is much smaller and faster to process.',
    code:'import torch.nn as nn\n\npool = nn.MaxPool2d(kernel_size=2)\n# Input:  (batch, 32, 224, 224)\n# Output: (batch, 32, 112, 112)\n\n# Global Average Pooling\ngap = nn.AdaptiveAvgPool2d((1, 1))\n# Input:  (batch, 512, 7, 7)\n# Output: (batch, 512, 1, 1)\n\n# Typical CNN block:\nblock = nn.Sequential(\n    nn.Conv2d(32, 64, 3, padding=1),\n    nn.ReLU(),\n    nn.MaxPool2d(2)\n)',
    realworld:'VGG16 uses 5 MaxPool2d(2) layers to progressively reduce a 224x224 image to 7x7. Without pooling, the network would process 50,176 spatial positions all the way through. With pooling, it processes 49 positions at the deep layers — a 1000x reduction in computation for the dense layers.' },

  { id:'cnn_04', topic:'CNN', subtopic:'Transfer Learning',
    theory:'Transfer learning uses a model pre-trained on a large dataset (like ImageNet with 1.2M images) as a starting point. The pre-trained model has already learned powerful feature detectors. Freeze early layers and replace/retrain only the final classification layers for your specific task. Works because low-level features (edges, textures) are useful across many vision tasks. Dramatically reduces training time and data requirements.',
    interview:'Transfer learning means taking a model already trained on millions of images and adapting it for our specific problem. The model has already learned to detect edges, shapes, and textures. We freeze those layers and just retrain the final layer for our new categories. Instead of training for weeks from scratch, we can fine-tune in hours with a small dataset and get great results.',
    code:'import torchvision.models as models\nimport torch.nn as nn\n\nmodel = models.resnet50(\n    weights="IMAGENET1K_V1")\n\n# Freeze all conv layers\nfor param in model.parameters():\n    param.requires_grad = False\n\n# Replace final layer\nnum_classes = 5\nmodel.fc = nn.Linear(2048, num_classes)\n# Only this new layer trains\n\n# Optionally unfreeze last block:\nfor param in model.layer4.parameters():\n    param.requires_grad = True',
    realworld:'A hospital wants to classify X-rays into 5 categories but only has 2,000 labelled X-rays. They load ResNet50 pretrained on ImageNet, freeze early layers, and fine-tune the last layers. Result: 91% accuracy in 2 hours vs 67% training from scratch.' },

  { id:'cnn_05', topic:'CNN', subtopic:'Common Architectures',
    theory:'Key CNN architectures: AlexNet (2012) — showed deep learning potential. VGG16/19 (2014) — simple 3x3 convs stacked deep, still used as feature extractor. ResNet (2015) — skip connections to train very deep networks (50, 101, 152 layers), solved vanishing gradient. EfficientNet (2019) — scales width, depth, and resolution together, best accuracy/compute tradeoff. Most production systems use ResNet or EfficientNet as backbone.',
    interview:'The most important CNN architectures are ResNet and EfficientNet. ResNet introduced skip connections which allow very deep networks to train without the vanishing gradient problem. EfficientNet is the best accuracy-per-compute architecture and is widely used in production. For transfer learning we almost always start with one of these pretrained architectures.',
    code:'import torchvision.models as models\n\nresnet50  = models.resnet50(\n    weights="IMAGENET1K_V1")\neffnet_b0 = models.efficientnet_b0(\n    weights="IMAGENET1K_V1")\nmobilenet = models.mobilenet_v3_small(\n    weights="IMAGENET1K_V1")\n\ndef count_params(m):\n    return sum(\n        p.numel() for p in m.parameters())\nprint(count_params(resnet50))   # ~25M\nprint(count_params(effnet_b0))  # ~5M',
    realworld:'Google Photos uses EfficientNet for face recognition and object detection. It was chosen over VGG because it achieves the same accuracy with 8x fewer parameters and 6x fewer operations. At 4 billion queries per day, a 6x compute reduction translates to hundreds of millions of dollars in annual infrastructure savings.' },

  // LSTM
  { id:'lstm_01', topic:'LSTM', subtopic:'Definition',
    theory:'LSTM (Long Short-Term Memory) is a type of RNN designed to learn from sequential data and capture long-range dependencies. Standard RNNs suffer from the vanishing gradient problem — gradients become tiny when backpropagating through many time steps. LSTMs solve this with a gating mechanism that controls what information to remember and forget across long sequences.',
    interview:'LSTM is a type of neural network designed for sequences — like text, time-series data, or any data where order matters. Regular RNNs forget things that happened early in the sequence. LSTM has a memory cell and gates that decide what to remember and what to forget. This allows it to learn patterns that depend on things far back in the sequence.',
    code:'import torch.nn as nn\n\nclass LSTMModel(nn.Module):\n    def __init__(self, input_size,\n                 hidden_size, num_layers,\n                 output_size):\n        super().__init__()\n        self.lstm = nn.LSTM(\n            input_size, hidden_size,\n            num_layers,\n            batch_first=True,\n            dropout=0.2)\n        self.fc = nn.Linear(\n            hidden_size, output_size)\n\n    def forward(self, x):\n        out, (hn, cn) = self.lstm(x)\n        return self.fc(out[:, -1, :])',
    realworld:'Google Translate originally used LSTM encoder-decoder models. The encoder LSTM reads an entire sentence and compresses it into a hidden state. The decoder LSTM generates the translated sentence word by word. The encoder needed to remember context from the beginning of a long sentence to correctly translate words at the end.' },

  { id:'lstm_02', topic:'LSTM', subtopic:'Gates and Cell State',
    theory:'LSTM has three gates: Forget gate — decides what to remove from the cell state. Input gate — decides what new information to add to the cell state. Output gate — decides what part of the cell state to output as the hidden state. The cell state (c_t) carries information across time steps like a conveyor belt. This gating mechanism allows LSTMs to learn very long-range dependencies.',
    interview:'LSTM has three gates. The forget gate decides which old information to throw away. The input gate decides which new information to store in memory. The output gate decides what to output based on what is in memory. The cell state is the long-term memory that flows through the whole sequence. These gates together allow the LSTM to remember important things from early in the sequence.',
    code:'# LSTM outputs explained:\n# output, (h_n, c_n) = lstm(x)\n#\n# output: (batch, seq_len, hidden)\n#   hidden state at every timestep\n# h_n: (layers, batch, hidden)\n#   final hidden state\n# c_n: (layers, batch, hidden)\n#   final cell state (long-term memory)\n\noutput, (h_n, c_n) = lstm(x)\n\n# For many-to-one (e.g. sentiment):\nlast_hidden = output[:, -1, :]\n# For many-to-many (e.g. translation):\nall_hidden = output',
    realworld:'In a language model predicting "The cat, which had been sleeping on the windowsill, was..." the LSTM needs to remember "cat" (subject) across 12 words to predict the next word correctly. The forget gate keeps "cat" in memory while discarding weather details. This long-range dependency is exactly what LSTMs were designed to solve.' },

  { id:'lstm_03', topic:'LSTM', subtopic:'Input Shape',
    theory:'LSTM input shape is (batch_size, sequence_length, input_features) with batch_first=True. batch_size: number of sequences per batch. sequence_length: number of time steps (e.g., 30 days of stock prices). input_features: number of features at each time step (e.g., OHLCV = 5 features). Getting shapes right is critical — shape mismatches are the most common LSTM bug.',
    interview:'LSTM expects input in a specific 3D shape: batch size, sequence length, and number of features at each time step. For example if we have 32 stock sequences, each 30 days long, with 5 features per day, the shape is (32, 30, 5). Getting this shape right is very important. Most LSTM errors are shape mismatches from incorrectly preparing the input data.',
    code:'import torch\n\nbatch_size  = 32\nseq_len     = 30\nn_features  = 5   # OHLCV\nhidden_size = 64\n\nX = torch.randn(batch_size, seq_len, n_features)\nprint(f"Input: {X.shape}")\n# torch.Size([32, 30, 5])\n\nlstm = torch.nn.LSTM(\n    input_size  = n_features,\n    hidden_size = hidden_size,\n    num_layers  = 2,\n    batch_first = True\n)\nout, (hn, cn) = lstm(X)\nprint(f"Output: {out.shape}")\n# torch.Size([32, 30, 64])',
    realworld:'A predictive maintenance system monitors 10 sensors every minute. To predict failure 24 hours ahead, engineers create sequences of the last 60 minutes: input shape (batch, 60, 10). The LSTM learns that certain sensor patterns occurring 45 minutes before failure are reliable warning signs.' },

  { id:'lstm_04', topic:'LSTM', subtopic:'Preparing Sequential Data',
    theory:'To use LSTM for time-series prediction you need to reshape flat data into overlapping sequences using a sliding window. For each sequence of length seq_len, the target is the value at the next time step. After creating sequences, split into train/test WITHOUT shuffling — time order must be preserved. shuffle=False in DataLoader maintains temporal order.',
    interview:'To use LSTM for time-series we need to create sliding windows of data. For each window of 30 days, the target is the value on day 31. We slide this window one step at a time across the whole dataset to create many training examples. Importantly, we do not shuffle time-series data when splitting train and test — future data must never be used to predict past data.',
    code:'import numpy as np\n\ndef create_sequences(data, seq_len):\n    X, y = [], []\n    for i in range(len(data)-seq_len):\n        X.append(data[i:i+seq_len])\n        y.append(data[i+seq_len])\n    return np.array(X), np.array(y)\n\nX, y = create_sequences(stock_prices, 30)\nprint(X.shape)  # (n_samples, 30, n_feat)\n\n# Do NOT shuffle time-series!\ntrain_size = int(len(X) * 0.8)\nX_train = X[:train_size]\nX_test  = X[train_size:]',
    realworld:'A weather forecasting model uses 14-day sliding windows of temperature, humidity, wind speed, and pressure. create_sequences turns 10 years of daily data into thousands of (14-day-window, next-day-target) pairs. Years 1-8 for training, year 9 for validation, year 10 for testing — strict temporal ordering prevents data leakage.' },

  // YOLO
  { id:'yolo_01', topic:'YOLO', subtopic:'Definition',
    theory:'YOLO (You Only Look Once) is a family of real-time object detection models. Unlike older methods that run a classifier multiple times on different regions, YOLO processes the entire image in a single forward pass — hence "you only look once". It simultaneously predicts bounding boxes and class labels for all objects. This makes it extremely fast — capable of 30+ FPS real-time detection. YOLOv8 by Ultralytics is the current popular version.',
    interview:'YOLO is a fast object detection model. It looks at the whole image once and detects all objects in it at the same time, drawing bounding boxes around each one and labelling what they are. Earlier methods had to look at hundreds of regions separately which was very slow. YOLO does everything in one pass so it is fast enough to work on live video.',
    code:'from ultralytics import YOLO\n\nmodel = YOLO("yolov8n.pt")  # nano/fastest\n\nresults = model("image.jpg")\n\nfor r in results:\n    print(r.boxes.xyxy)   # coordinates\n    print(r.boxes.conf)   # confidence\n    print(r.boxes.cls)    # class indices\n    r.show()              # visualise\n    r.save("result.jpg")\n\n# Run on video:\nresults = model("video.mp4", stream=True)',
    realworld:'Tesla Autopilot uses YOLO-style detection to identify cars, pedestrians, cyclists, and lane markings from 8 cameras simultaneously at 36 FPS. The model must process and respond in under 28ms for safe driving at highway speeds. This real-time requirement is exactly why single-pass detectors like YOLO were developed.' },

  { id:'yolo_02', topic:'YOLO', subtopic:'How YOLO Works',
    theory:'YOLO divides the image into an SxS grid. Each grid cell predicts bounding boxes (with x, y, width, height, confidence) and class probabilities. The confidence score reflects how likely an object is present and how accurate the box is. After all predictions, Non-Maximum Suppression (NMS) removes duplicate boxes by keeping only the highest confidence box when multiple boxes overlap above an IoU threshold.',
    interview:'YOLO splits the image into a grid. Each grid cell is responsible for detecting objects whose centre falls in that cell. For each cell it predicts possible bounding boxes with confidence scores and class probabilities. After all predictions are made, Non-Maximum Suppression removes duplicate boxes — if two boxes detect the same object, we keep only the most confident one.',
    code:'from ultralytics import YOLO\n\nmodel   = YOLO("yolov8n.pt")\nresults = model(\n    "image.jpg",\n    conf=0.5,   # min confidence\n    iou=0.45    # NMS IoU threshold\n)\n\nfor r in results:\n    for box in r.boxes:\n        coords = box.xyxy[0].tolist()\n        conf   = float(box.conf[0])\n        cls_id = int(box.cls[0])\n        label  = model.names[cls_id]\n        print(f"{label}: {conf:.2f}")\n        print(f"Box: {coords}")',
    realworld:'A retail store uses YOLO for checkout-free shopping. When a customer picks up a product, YOLO detects the category and bounding box in real-time from ceiling cameras. The grid-based approach detects all products across the whole shelf simultaneously. NMS prevents counting one box of cereal twice when it partially crosses two grid cells.' },

  { id:'yolo_03', topic:'YOLO', subtopic:'Fine-tuning YOLO',
    theory:'YOLO can be fine-tuned on custom datasets to detect domain-specific objects. Process: (1) Prepare dataset in YOLO format — images + annotation files with class_id and normalised coordinates. (2) Create data.yaml config listing class names and paths. (3) Run model.train(). Transfer learning applies — pretrained weights are updated for your classes. YOLOv8 by Ultralytics makes this straightforward.',
    interview:'Fine-tuning YOLO means training it to detect objects specific to our use case. We provide labelled images where each object is annotated with a bounding box and class label. YOLO starts from the pretrained weights and updates them to recognise our custom objects. Even with a few hundred images we can get good results because of the pretrained features.',
    code:'from ultralytics import YOLO\n\nmodel = YOLO("yolov8n.pt")\n\n# data.yaml defines:\n# train: path/to/train/images\n# val:   path/to/val/images\n# nc:    number of classes\n# names: [class1, class2, ...]\n\nresults = model.train(\n    data="data.yaml",\n    epochs=50,\n    imgsz=640,\n    batch=16,\n    patience=10,\n    device="cuda"\n)\n\n# YOLO annotation format per image:\n# class_id cx cy width height\n# (all values normalised 0-1)',
    realworld:'A manufacturing company fine-tunes YOLOv8 to detect defects in circuit boards. They label 500 images with bounding boxes around 6 defect types. After 50 epochs, the model detects defects with 94% mAP at 45ms per image — fast enough to flag boards in real-time before packaging.' },

  { id:'yolo_04', topic:'YOLO', subtopic:'Evaluation Metrics — IoU and mAP',
    theory:'Object detection uses different metrics than classification. IoU (Intersection over Union): measures overlap between predicted and ground truth boxes. IoU = area of overlap / area of union. IoU >= 0.5 is a common threshold for a correct detection. mAP (mean Average Precision): the standard benchmark. AP is computed per class as area under the precision-recall curve. mAP averages AP across all classes. mAP@50:95 averages over IoU thresholds from 0.5 to 0.95.',
    interview:'For object detection we use mAP — mean Average Precision. It measures both how accurate the bounding boxes are (IoU) and how well the model distinguishes between classes. IoU measures the overlap between our predicted box and the true box. mAP@50 means a detection counts as correct if the box overlaps with the true box by at least 50%. Higher mAP means better detection across all classes.',
    code:'from ultralytics import YOLO\n\nmodel   = YOLO("best.pt")\nmetrics = model.val(\n    data="data.yaml",\n    conf=0.5, iou=0.5)\n\nprint(metrics.box.map)    # mAP@50:95\nprint(metrics.box.map50)  # mAP@50\nprint(metrics.box.p)      # precision\nprint(metrics.box.r)      # recall\n\n# IoU calculation:\ndef iou(b1, b2):  # [x1,y1,x2,y2]\n    xi1 = max(b1[0], b2[0])\n    yi1 = max(b1[1], b2[1])\n    xi2 = min(b1[2], b2[2])\n    yi2 = min(b1[3], b2[3])\n    inter = max(0,xi2-xi1)*max(0,yi2-yi1)\n    union = ((b1[2]-b1[0])*(b1[3]-b1[1])\n           + (b2[2]-b2[0])*(b2[3]-b2[1])\n           - inter)\n    return inter / union',
    realworld:'COCO benchmark uses mAP@50:95 to rank object detection models. YOLOv8x achieves 53.9% mAP on COCO across 80 categories and multiple IoU thresholds. This standardised benchmark allows the community to track progress objectively, similar to how ImageNet accuracy is used for classification.' },
];
